project:
  type: book
  output-dir: _book

book:
  title: "Hansen中高级计量体系"
  author: "胡华平"
  date: "2022/9/16"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: cover.png
    code-link: true
  pdf:
    documentclass: scrreprt



