project:
  type: book
  output-dir: _book

book:
  title: "Hansen中高级计量体系"
  author: "胡华平"
  date: "2022/9/16"
  site-url: https://hansenem.netlify.app/
  repo-url: https://github.com/huhuaping/hansenEM/
  repo-branch: master
  repo-actions: [edit]
  chapters:
    - index.qmd
    - participate.qmd
    - chpt01-intro.qmd
    - chpt01-intro-chn.qmd
    - part: part01-reg.qmd
      chapters: 
        - chpt02-ce.qmd
        - chpt02-ce-chn.qmd
        - chpt03-algebra.qmd
        - chpt03-algebra-chn.qmd
        - chpt04-lsr.qmd
        - chpt05-normal-reg.qmd
    - part: part02-LSM.qmd
      chapters:
        - chpt06-review.qmd
        - chpt07-asymptotic-ls.qmd
        - chpt08-restricted-est.qmd
        - chpt09-hypothesit-test.qmd
        - chpt10-resample-method.qmd
    - part: part03-MEQ.qmd
      chapters:
        - chpt11-multi-reg.qmd
        - chpt12-iv.qmd
        - chpt13-gmm.qmd
    - part: part04-pannel.qmd
      chapters:
        - chpt14-time-series.qmd
        - chpt15-multiple-time-series.qmd
        - chpt17-panel-data.qmd
        - chpt18-did.qmd
    - part: part05-nonpar.qmd
      chapters:
        - chpt19-nonparameter.qmd
        - chpt20-series-reg.qmd
        - chpt21-rdd.qmd
        - chpt22-m-est.qmd
    - part: part06-nonlinear.qmd
      chapters: 
        - chpt23-nonliear-ls.qmd
        - chpt24-quantile-reg.qmd
        - chpt26-multiple-choice.qmd
        - chpt27-censor-selection.qmd
        - chpt28-model-selection.qmd
        - chpt29-ML.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - a1-notation.qmd
    
bibliography: references.bib
number-sections: true
number-depth: 4

format:
  html:
    theme: cosmo
    cover-image: pic/cover-hansen.jpg
    code-link: true
    toc: true
    toc-depth: 3
    toc_float: true
    toc-location: left
    toc-title: 目录
    #css: mycss/layout-style.css



