<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Hansen中高级计量体系 - 条件预期和预测</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chpt03-algebra.html" rel="next">
<link href="./chpt02-ce.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">条件预期和预测</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Hansen中高级计量体系</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/huhuaping/hansenEM/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">前言</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./participate.html" class="sidebar-item-text sidebar-link">如何参与？</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt01-intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt01-intro-chn.html" class="sidebar-item-text sidebar-link">介绍</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part01-reg.html" class="sidebar-item-text sidebar-link">回归</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt02-ce.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Conditional Expectation and Projection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt02-ce-chn.html" class="sidebar-item-text sidebar-link active">条件预期和预测</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt03-algebra.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Algebra of Least Squares</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt03-algebra-chn.html" class="sidebar-item-text sidebar-link">最小二乘代数</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt04-lsr.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Least Squares Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt05-normal-reg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Normal Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part02-LSM.html" class="sidebar-item-text sidebar-link">大样本方法</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt06-review.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">A Review of Large Sample Asymptotics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt07-asymptotic-ls.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Asymptotic Theory for Least Squares</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt08-restricted-est.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Restricted Estimation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt09-hypothesit-test.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt10-resample-method.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Resampling Methods</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part03-MEQ.html" class="sidebar-item-text sidebar-link">多方程模型</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt11-multi-reg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Multivariate Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt12-iv.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chpt13-gmm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Generalized Method of Moments</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">Summary</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a1-notation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">附录a1</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">目录</h2>
   
  <ul>
  <li><a href="#介绍" id="toc-介绍" class="nav-link active" data-scroll-target="#介绍">介绍</a></li>
  <li><a href="#工资分配" id="toc-工资分配" class="nav-link" data-scroll-target="#工资分配">工资分配</a></li>
  <li><a href="#有条件的期望" id="toc-有条件的期望" class="nav-link" data-scroll-target="#有条件的期望">有条件的期望</a></li>
  <li><a href="#日志和百分比" id="toc-日志和百分比" class="nav-link" data-scroll-target="#日志和百分比">日志和百分比</a></li>
  <li><a href="#条件期望函数" id="toc-条件期望函数" class="nav-link" data-scroll-target="#条件期望函数">条件期望函数</a></li>
  <li><a href="#连续变量" id="toc-连续变量" class="nav-link" data-scroll-target="#连续变量">连续变量</a></li>
  <li><a href="#迭代期望定律" id="toc-迭代期望定律" class="nav-link" data-scroll-target="#迭代期望定律">迭代期望定律</a></li>
  <li><a href="#cef-错误" id="toc-cef-错误" class="nav-link" data-scroll-target="#cef-错误">CEF 错误</a></li>
  <li><a href="#仅拦截模型" id="toc-仅拦截模型" class="nav-link" data-scroll-target="#仅拦截模型">仅拦截模型</a></li>
  <li><a href="#回归方差" id="toc-回归方差" class="nav-link" data-scroll-target="#回归方差">回归方差</a></li>
  <li><a href="#最佳预测者" id="toc-最佳预测者" class="nav-link" data-scroll-target="#最佳预测者">最佳预测者</a></li>
  <li><a href="#条件方差" id="toc-条件方差" class="nav-link" data-scroll-target="#条件方差">条件方差</a></li>
  <li><a href="#同方差和异方差" id="toc-同方差和异方差" class="nav-link" data-scroll-target="#同方差和异方差">同方差和异方差</a></li>
  <li><a href="#异方差还是异方差" id="toc-异方差还是异方差" class="nav-link" data-scroll-target="#异方差还是异方差">异方差还是异方差？</a></li>
  <li><a href="#回归导数" id="toc-回归导数" class="nav-link" data-scroll-target="#回归导数">回归导数</a></li>
  <li><a href="#线性-cef" id="toc-线性-cef" class="nav-link" data-scroll-target="#线性-cef">线性 CEF</a></li>
  <li><a href="#同方差线性-cef-模型" id="toc-同方差线性-cef-模型" class="nav-link" data-scroll-target="#同方差线性-cef-模型">同方差线性 CEF 模型</a></li>
  <li><a href="#具有非线性效应的线性-cef" id="toc-具有非线性效应的线性-cef" class="nav-link" data-scroll-target="#具有非线性效应的线性-cef">具有非线性效应的线性 CEF</a></li>
  <li><a href="#带有虚拟变量的线性-cef" id="toc-带有虚拟变量的线性-cef" class="nav-link" data-scroll-target="#带有虚拟变量的线性-cef">带有虚拟变量的线性 CEF</a></li>
  <li><a href="#最佳线性预测器" id="toc-最佳线性预测器" class="nav-link" data-scroll-target="#最佳线性预测器">最佳线性预测器</a></li>
  <li><a href="#可逆性和识别" id="toc-可逆性和识别" class="nav-link" data-scroll-target="#可逆性和识别">可逆性和识别</a></li>
  <li><a href="#最小化" id="toc-最小化" class="nav-link" data-scroll-target="#最小化">最小化</a></li>
  <li><a href="#最佳线性预测器的插图" id="toc-最佳线性预测器的插图" class="nav-link" data-scroll-target="#最佳线性预测器的插图">最佳线性预测器的插图</a></li>
  <li><a href="#线性预测误差方差" id="toc-线性预测误差方差" class="nav-link" data-scroll-target="#线性预测误差方差">线性预测误差方差</a></li>
  <li><a href="#回归系数" id="toc-回归系数" class="nav-link" data-scroll-target="#回归系数">回归系数</a></li>
  <li><a href="#回归子向量" id="toc-回归子向量" class="nav-link" data-scroll-target="#回归子向量">回归子向量</a></li>
  <li><a href="#系数分解" id="toc-系数分解" class="nav-link" data-scroll-target="#系数分解">系数分解</a></li>
  <li><a href="#省略变量偏差" id="toc-省略变量偏差" class="nav-link" data-scroll-target="#省略变量偏差">省略变量偏差</a></li>
  <li><a href="#最佳线性逼近" id="toc-最佳线性逼近" class="nav-link" data-scroll-target="#最佳线性逼近">最佳线性逼近</a></li>
  <li><a href="#回归均值" id="toc-回归均值" class="nav-link" data-scroll-target="#回归均值">回归均值</a></li>
  <li><a href="#反向回归" id="toc-反向回归" class="nav-link" data-scroll-target="#反向回归">反向回归</a></li>
  <li><a href="#最佳线性投影的局限性" id="toc-最佳线性投影的局限性" class="nav-link" data-scroll-target="#最佳线性投影的局限性">最佳线性投影的局限性</a></li>
  <li><a href="#随机系数模型" id="toc-随机系数模型" class="nav-link" data-scroll-target="#随机系数模型">随机系数模型</a></li>
  <li><a href="#因果效应" id="toc-因果效应" class="nav-link" data-scroll-target="#因果效应">因果效应</a></li>
  <li><a href="#条件期望的存在性和唯一性" id="toc-条件期望的存在性和唯一性" class="nav-link" data-scroll-target="#条件期望的存在性和唯一性">条件期望的存在性和唯一性*</a></li>
  <li><a href="#鉴别" id="toc-鉴别" class="nav-link" data-scroll-target="#鉴别">鉴别*</a></li>
  <li><a href="#技术证明" id="toc-技术证明" class="nav-link" data-scroll-target="#技术证明">技术证明*</a></li>
  <li><a href="#练习" id="toc-练习" class="nav-link" data-scroll-target="#练习">练习</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/huhuaping/hansenEM/edit/master/chpt02-ce-chn.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">条件预期和预测</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="介绍" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="介绍">介绍</h2>
<p>最常用的计量经济学工具是最小二乘估计，也称为回归。最小二乘法是一种工具，用于在给定另一组变量（回归变量、条件变量或协变量）的情况下估计一个变量（因变量）的条件均值。</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>The most commonly applied econometric tool is least squares estimation, also known as regression. Least squares is a tool to estimate the conditional mean of one variable (the dependent variable) given another set of variables (the regressors, conditioning variables, or covariates).</p>
</div></div><p>在本章中，我们从估计中抽象出来，重点讨论条件期望模型的概率基础及其投影近似。这包括对概率论的回顾。有关中级概率论的背景知识，请参阅《经济学家的概率与统计》第 1-5 章。</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>In this chapter we abstract from estimation and focus on the probabilistic foundation of the conditional expectation model and its projection approximation. This includes a review of probability theory. For a background in intermediate probability theory see Chapters 1-5 of Probability and Statistics for Economists.</p>
</div></div></section>
<section id="工资分配" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="工资分配">工资分配</h2>
<p>假设我们对美国的工资率感兴趣。由于工人的工资率各不相同，我们不能用一个数字来描述工资率。相反，我们可以使用概率分布来描述工资。形式上，我们将单个工人的工资视为具有概率分布的随机变量工资</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Suppose that we are interested in wage rates in the United States. Since wage rates vary across workers we cannot describe wage rates by a single number. Instead, we can describe wages using a probability distribution. Formally, we view the wage of an individual worker as a random variable wage with the probability distribution</p>
</div></div><p><span class="math display">\[
F(y)=\mathbb{P}[\text { wage } \leq y] .
\]</span></p>
<p>当我们说一个人的工资是随机的时，我们的意思是在测量之前我们不知道他们的工资，我们将观察到的工资率视为分布 <span class="math inline">\(F\)</span> 的实现。将未观察到的工资视为随机变量，将观察到的工资视为实现是一种强大的数学抽象，它允许我们使用数学概率工具。</p>
<p>一个有用的思想实验是想象拨打一个随机选择的电话号码，然后让接电话的人告诉我们他们的工资率。 （为简单起见，假设所有工人都可以平等地使用电话，并且接听电话的人会诚实接听。）在这个思想实验中，您所拨打电话的人的工资是工资分布 <span class="math inline">\(F\)</span> 的一次抽取在人口中。通过拨打许多这样的电话，我们可以了解完整的分布。</p>
<p>当分布函数 <span class="math inline">\(F\)</span> 可微时，我们定义概率密度函数</p>
<p><span class="math display">\[
f(y)=\frac{d}{d y} F(y) .
\]</span></p>
<p>密度包含与分布函数相同的信息，但密度通常更易于直观解释。</p>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-02.jpg" class="img-fluid"></p>
<ol type="a">
<li>工资密度</li>
</ol>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-02(1).jpg" class="img-fluid"></p>
<ol start="2" type="a">
<li>对数工资密度</li>
</ol>
<p>图 2.1：工资密度和对数工资</p>
<p>在图 2.1(a) 中，我们展示了 <span class="math inline">\(2009 .\)</span> 中美国工资率概率密度函数的估计 <span class="math inline">\({ }^{1}\)</span> 我们看到密度在 <span class="math inline">\(\$ 15\)</span>, and most of the probability mass appears to lie between <span class="math inline">\(\$ 10\)</span> 和 <span class="math inline">\(\$ 40 附近达到峰值\)</span>. These are ranges for typical wage rates in the U.S. population.</p>
<p>集中趋势的重要度量是中位数和平均值。连续分布 <span class="math inline">\(F\)</span> 的中位数 <span class="math inline">\(m\)</span> 是</p>
<p><span class="math display">\[
F(m)=\frac{1}{2} .
\]</span></p>
<p>美国工资中位数为 <span class="math inline">\(\$ 19.23\)</span>. The median is a robust <span class="math inline">\({ }^{2}\)</span> measure of central tendency, but it is tricky to use for many calculations as it is not a linear operator.</p>
<p>具有离散支持的随机变量 <span class="math inline">\(Y\)</span> 的均值或期望是</p>
<p><span class="math display">\[
\mu=\mathbb{E}[Y]=\sum_{j=1}^{\infty} \tau_{j} \mathbb{P}\left[Y=\tau_{j}\right] .
\]</span></p>
<p>对于密度为 <span class="math inline">\(f(y)\)</span> 的连续随机变量，期望为</p>
<p><span class="math display">\[
\mu=\mathbb{E}[Y]=\int_{-\infty}^{\infty} y f(y) d y .
\]</span></p>
<p>在这里，我们使用了使用单个字符 <span class="math inline">\(Y\)</span> 来表示随机变量的常见且方便的约定，而不是更繁琐的标签工资。包含离散和连续随机变量作为特殊情况的另一种表示法是将积分写为 <span class="math inline">\(\int_{-\infty}^{\infty} y d F(y)\)</span>。</p>
<p>期望是集中趋势的一种方便度量，因为它是一个线性算子，并且在许多经济模型中自然出现。期望的一个缺点是它不是健壮的 <span class="math inline">\({ }^{3}\)</span> 尤其是</p>
<p><span class="math inline">\({ }^{1}\)</span> 分布和密度是根据 2009 年 3 月当前人口调查中报告的 50,742 名全职非军事工薪者样本非参数估计的。工资率由个人年度工资和薪金收入除以工作时间构成。</p>
<p><span class="math inline">\({ }^{2}\)</span> 中位数对分布尾部的扰动不敏感。</p>
<p><span class="math inline">\({ }^{3}\)</span> 期望对分布尾部的扰动很敏感。如图 2.1(a) 所示，存在明显偏斜或厚尾，这两者都是工资分布的特征。另一种看法是，<span class="math inline">\(64 %\)</span> 工人的平均工资低于 <span class="math inline">\(\$ 23.90\)</span>, suggesting that it is incorrect to describe the mean <span class="math inline">\(\$ 23.90\)</span> 作为“典型”工资率。</p>
<p>在这种情况下，通过取自然对数“<span class="math inline">\({ }^{4}\)</span>”来转换数据是有用的。图 <span class="math inline">\(2.1\)</span> (b) 显示了相同人口的 <span class="math inline">\(\log\)</span> 小时工资 <span class="math inline">\(\log (\)</span> 工资 <span class="math inline">\()\)</span> 的密度。密度对数工资的偏斜和肥尾比工资水平的密度要小，所以它的均值</p>
<p><span class="math display">\[
\mathbb{E}[\log (\text { wage })]=2.95
\]</span></p>
<p>是分布集中趋势的更好（更稳健）的度量 <span class="math inline">\({ }^{5}\)</span>。出于这个原因，工资回归通常使用对数工资作为因变量，而不是工资水平。</p>
<p>总结概率分布 <span class="math inline">\(F(y)\)</span> 的另一种有用方法是根据其分位数。对于任何 <span class="math inline">\(\alpha \in(0,1)\)</span>，连续 <span class="math inline">\({ }^{6}\)</span> 分布 <span class="math inline">\(F\)</span> 的 <span class="math inline">\(\alpha^{t h}\)</span> 分位数是满足 <span class="math inline">\(F\left(q_{\alpha}\right)=\alpha\)</span> 的实数 <span class="math inline">\(q_{\alpha}\)</span>。分位数函数 <span class="math inline">\(q_{\alpha}\)</span>，被视为 <span class="math inline">\(\alpha\)</span> 的函数，是分布函数 <span class="math inline">\(F\)</span> 的倒数。最常用的分位数是中位数，即<span class="math inline">\(q_{0.5}=m\)</span>。我们有时通过 <span class="math inline">\(\alpha\)</span> 的百分位数表示来指代分位数，在这种情况下，它们被称为百分位数。例如。中位数是 <span class="math inline">\(50^{t h}\)</span> 百分位数。</p>
</section>
<section id="有条件的期望" class="level2">
<h2 class="anchored" data-anchor-id="有条件的期望">有条件的期望</h2>
<p>我们在图 2.1(b) 中看到了对数工资的密度。这种分布对所有工人来说都是一样的，还是工资分布在不同的子人群中有所不同？为了回答这个问题，我们可以比较不同群体的工资分布——例如，男性和女性。为了进行调查，我们在图 <span class="math inline">\(2.2\)</span> (a) 中绘制了美国男性和女性的对数工资密度。我们可以看到这两种工资密度具有相似的形状，但男性的密度稍微向右移动。</p>
<p>值 <span class="math inline">\(3.05\)</span> 和 <span class="math inline">\(2.81\)</span> 是男性和女性工人亚群的平均对数工资。它们被称为给定性别的对数工资的条件期望（或条件均值）。我们可以将它们的具体值写为</p>
<p><span class="math display">\[
\begin{gathered}
\mathbb{E}[\log (\text { wage }) \mid \text { gender }=\text { man }]=3.05 \\
\mathbb{E}[\log (\text { wage }) \mid \text { gender }=\text { woman }]=2.81 .
\end{gathered}
\]</span></p>
<p>我们将这些期望称为“有条件的”，因为它们以可变性别的固定值为条件。虽然您可能不会将一个人的性别视为随机变量，但从计量经济学分析的角度来看，它是随机的。如果你随机选择一个人，这个人的性别是未知的，因此是随机的。 （在美国工人群体中，工人是女性的概率恰好是 <span class="math inline">\(43 %\)</span>。）在观察数据中，将所有测量值视为随机变量是最合适的，然后子群体的平均值就是条件平均值。</p>
<p>在这一点上重要的是要提到，我们绝不会将因果关系或解释归因于男女之间对数工资的条件期望差异。有多种可能的解释。</p>
<p>由于图 2.2(a) 中的两个密度看起来相似，因此可以草率地推断男性和女性的工资分布之间没有有意义的差异。在得出这个结论之前，让我们更仔细地检查分布的差异。正如我们上面提到的，</p>
<p><span class="math inline">\({ }^{4}\)</span> 在整本书中，我们将使用 <span class="math inline">\(\log (y)\)</span> 或 <span class="math inline">\(\log y\)</span> 来表示 <span class="math inline">\(y\)</span> 的自然对数。</p>
<p><span class="math inline">\({ }^{5}\)</span> 更准确地说，几何平均值 <span class="math inline">\(\exp (\mathbb{E}[\log W])=\$ 19.11\)</span> is a robust measure of central tendency.</p>
<p><span class="math inline">\({ }^{6}\)</span> 如果 <span class="math inline">\(F\)</span> 不连续，则定义为 <span class="math inline">\(q_{\alpha}=\inf \{y: F(y) \geq \alpha\}\)</span></p>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-04.jpg" class="img-fluid"></p>
<ol type="a">
<li>妇女和男子</li>
</ol>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-04(1).jpg" class="img-fluid"></p>
<ol start="2" type="a">
<li>按性别和种族</li>
</ol>
<p>图 2.2：按性别和种族划分的对数工资密度</p>
<p>两种密度之间的主要区别似乎是它们的平均值。这个差等于</p>
<p><span class="math display">\[
\begin{aligned}
\mathbb{E}[\log (\text { wage }) \mid \text { gender }=\text { man }]-\mathbb{E}[\log (\text { wage }) \mid \text { gender }=\text { woman }] &amp;=3.05-2.81 \\
&amp;=0.24 .
\end{aligned}
\]</span></p>
<p><span class="math inline">\(0.24\)</span> 的预期对数工资差异通常被解释为男性和女性工资之间的平均 <span class="math inline">\(24 %\)</span> 差异，这是相当大的。 （有关更完整的解释，请参见第 2.4 节。）</p>
<p>考虑进一步按种族划分男性和女性亚群，将人口分为白人、黑人和其他种族。我们在图 <span class="math inline">\(2.2\)</span> (b) 中显示了其中四个组的对数工资密度函数。我们再次看到四个密度函数之间的主要区别在于它们的集中趋势。</p>
<p>关注这些分布的均值，表 <span class="math inline">\(2.1\)</span> 报告了六个子群体中每一个的平均对数工资。</p>
<p>表 2.1：按性别和种族划分的平均对数工资</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th>men</th>
<th>women</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">white</td>
<td><span class="math inline">\(3.07\)</span></td>
<td><span class="math inline">\(2.82\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Black</td>
<td><span class="math inline">\(2.86\)</span></td>
<td><span class="math inline">\(2.73\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">other</td>
<td><span class="math inline">\(3.03\)</span></td>
<td><span class="math inline">\(2.86\)</span></td>
</tr>
</tbody>
</table>
<p>我们再次强调，我们绝不会将因果关系或解释归因于表格条目之间的差异。我们之所以使用这些特定的亚群来说明条件期望，是因为美国（和其他地方）性别和种族群体之间的经济结果差异已被广泛讨论；社会科学的部分作用是仔细记录这些模式，其部分作用是制作模型和解释。有条件的期望（自己）可以帮助文档和描述；条件期望本身既不是模型也不是解释。</p>
<p>表 <span class="math inline">\(2.1\)</span> 中的条目是给定性别和种族的 <span class="math inline">\(\log (\)</span> 工资 <span class="math inline">\()\)</span> 的条件均值。例如</p>
<p><span class="math display">\[
\mathbb{E}[\log (\text { wage }) \mid \text { gender }=\text { man, race }=\text { white }]=3.07
\]</span></p>
<p>和</p>
<p><span class="math display">\[
\mathbb{E}[\log (\text { wage }) \mid \text { gender }=\text { woman, race }=\text { Black }]=2.73 \text {. }
\]</span></p>
<p>关注条件均值的一个好处是它们可以将复杂的分布简化为单一的汇总度量，从而促进跨组的比较。由于这种简化特性，条件均值是回归分析的主要兴趣点，也是计量经济学的主要关注点。</p>
<p>表 <span class="math inline">\(2.1\)</span> 使我们能够轻松计算各组之间的平均工资差异。例如，我们可以看到男女之间的工资差距在按种族分类后继续存在，因为白人男性和白人女性之间的平均差距是 <span class="math inline">\(25 %\)</span>，而黑人男性和黑人女性之间的平均差距是 <span class="math inline">\(13 %\)</span>。我们还可以看到存在种族差距，因为黑人的平均工资大大低于其他种族类别。特别是，白人男性和黑人男性之间的平均工资差距是 <span class="math inline">\(21 %\)</span>，白人女性和黑人女性之间的平均工资差距是 <span class="math inline">\(9 %\)</span>。</p>
</section>
<section id="日志和百分比" class="level2">
<h2 class="anchored" data-anchor-id="日志和百分比">日志和百分比</h2>
<p>在本节中，我们希望通过两个观察来激发和阐明回归分析中对数的使用。首先，当应用于数字时，对数的差异大约等于百分比差异。其次，当应用于平均值时，对数差异大约等于几何平均值的百分比差异。我们现在解释这些想法和所涉及的近似值的性质。</p>
<p>取两个正数 <span class="math inline">\(a\)</span> 和 <span class="math inline">\(b\)</span>。 <span class="math inline">\(a\)</span> 和 <span class="math inline">\(b\)</span> 之间的百分比差异是</p>
<p><span class="math display">\[
p=100\left(\frac{a-b}{b}\right) .
\]</span></p>
<p>重写，</p>
<p><span class="math display">\[
\frac{a}{b}=1+\frac{p}{100}
\]</span></p>
<p>取自然对数，</p>
<p><span class="math display">\[
\log a-\log b=\log \left(1+\frac{p}{100}\right) .
\]</span></p>
<p>小 <span class="math inline">\(x\)</span> 的有用近似值是</p>
<p><span class="math display">\[
\log (1+x) \simeq x .
\]</span></p>
<p>这可以从 <span class="math inline">\(\log (1+x)\)</span> 的无限级数展开推导出来：</p>
<p><span class="math display">\[
\log (1+x)=x-\frac{x^{2}}{2}+\frac{x^{3}}{3}-\frac{x^{4}}{4}+\cdots=x+O\left(x^{2}\right) .
\]</span></p>
<p>符号 <span class="math inline">\(O\left(x^{2}\right.\)</span> ) 表示余数以 <span class="math inline">\(A x^{2}\)</span> 为界，对于某些 <span class="math inline">\(A&lt;\infty\)</span>，则为 <span class="math inline">\(x \rightarrow 0\)</span>。在数值上，对于 <span class="math inline">\(|x| \leq 0.1\)</span>，近似值 <span class="math inline">\(\log (1+x) \simeq x\)</span> 在 <span class="math inline">\(0.001\)</span> 之内，并且近似误差随着 <span class="math inline">\(|x|\)</span> 的增加而增加</p>
<p>将 (2.3) 应用于 (2.2) 并乘以 100，我们发现</p>
<p><span class="math display">\[
p \simeq 100(\log a)-\log b) .
\]</span></p>
<p>这表明 100 乘以对数差值大约是百分比差值。在数值上，<span class="math inline">\(|p| \leq 10\)</span> 的近似误差小于 <span class="math inline">\(0.1\)</span> 个百分点。</p>
<p>现在考虑对数转换随机变量的期望差异。取两个随机变量 <span class="math inline">\(X_{1}, X_{2}&gt;0\)</span>。定义它们的几何平均值 <span class="math inline">\(\theta_{1}=\exp \left(\mathbb{E}\left[\log X_{1}\right]\right)\)</span> 和 <span class="math inline">\(\theta_{2}=\exp \left(\mathbb{E}\left[\log X_{2}\right]\right)\)</span> 以及它们的百分比差异</p>
<p><span class="math display">\[
p=100\left(\frac{\theta_{2}-\theta_{1}}{\theta_{1}}\right) .
\]</span></p>
<p>对数变换的期望差异（乘以 100）为</p>
<p><span class="math display">\[
100\left(\mathbb{E}\left[\log X_{2}\right]-\mathbb{E}\left[\log X_{1}\right]\right)=100\left(\log \theta_{2}-\log \theta_{1}\right) \simeq p
\]</span></p>
<p><span class="math inline">\(\theta_{2}\)</span> 和 <span class="math inline">\(\theta_{1}\)</span> 之间的百分比差异。换句话说，对数变换变量的平均值之间的差异（大约）是几何平均值的百分比差异。</p>
<p>后一种观察之所以重要，是因为许多计量经济学方程采用半对数形式</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\mathbb{E}[\log Y \mid \operatorname{group}=1]=\mu_{1} \\
&amp;\mathbb{E}[\log Y \mid \operatorname{group}=2]=\mu_{2}
\end{aligned}
\]</span></p>
<p>并且相当注意差异<span class="math inline">\(\mu_{1}-\mu_{2}\)</span>。例如，在上一节中，我们比较了男性和女性的平均对数工资，发现差异为 <span class="math inline">\(0.24\)</span>。在该部分中，我们指出这种差异通常被解释为平均百分比差异。这并不完全正确，但也不是完全错误。上面的计算表明，这个差异大约是几何平均值的百分比差异。所以 <span class="math inline">\(\mu_{1}-\mu_{2}\)</span> 是平均百分比差异，其中“平均”是指几何平均值而不是算术平均值。</p>
<p>要比较不同的百分比差异度量，请参见表 2.2。在前两列中，我们使用四个“平均值”报告 CPS 人群中男性和女性的平均工资：算术平均值、中位数、几何平均值和对数平均值。两组的算术平均值均高于中位数和几何平均值，后两者相似。这是偏态分布（例如工资分布）的共同特征。第三列报告前两列之间的百分比差异（以男性工资为基数）。例如，<span class="math inline">\(34 %\)</span> 的第一个条目表明男性的平均工资比女性的平均工资高 <span class="math inline">\(34 %\)</span>。下一个条目显示男性的中位数和几何平均值比女性高 <span class="math inline">\(26 %\)</span>。此列中的最后一项是平均对数工资之间的简单差值的 100 倍，即 <span class="math inline">\(24 %\)</span>。如上所示，对数变换均值的差异近似为几何均值的百分比差异，这种近似对于 <span class="math inline">\(10 %\)</span> 以下的差异非常有用。</p>
<p>让我们总结一下这个分析。通常取变量的对数并在条件均值之间进行比较。我们已经表明，这些差异是几何平均值百分比差异的度量。因此，预期对数转换之间的差异（例如男性和女性工资之间的 <span class="math inline">\(0.24\)</span> 差异）是近似百分比差异（例如男性工资相对于女性工资的 24% 差异）的常见描述是正确的，只要当我们意识到我们隐含地比较几何平均值时。</p>
</section>
<section id="条件期望函数" class="level2">
<h2 class="anchored" data-anchor-id="条件期望函数">条件期望函数</h2>
<p>工资的一个重要决定因素是教育。在许多实证研究中，经济学家通过受教育年数 <span class="math inline">\({ }^{7}\)</span> 来衡量教育程度。我们将把这个变量写成教育。</p>
<p><span class="math inline">\({ }^{7}\)</span> 在这里，教育被定义为幼儿园之后的教育年限。高中毕业生的教育=12，大学毕业生的教育=16，硕士学位的教育=18，专业学位（医学、法律或博士）的教育= 表2.2：平均工资和百分比差异</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th>men</th>
<th>women</th>
<th>% Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Arithmetic Mean</td>
<td><span class="math inline">\(\$ 26.80\)</span></td>
<td><span class="math inline">\(\$ 20.00\)</span></td>
<td><span class="math inline">\(34 %\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Median</td>
<td><span class="math inline">\(\$ 21.14\)</span></td>
<td><span class="math inline">\(\$ 16.83\)</span></td>
<td><span class="math inline">\(26 %\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Geometric Mean</td>
<td><span class="math inline">\(\$ 21.03\)</span></td>
<td><span class="math inline">\(\$ 16.64\)</span></td>
<td><span class="math inline">\(26 %\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean log Wage</td>
<td><span class="math inline">\(3.05\)</span></td>
<td><span class="math inline">\(2.81\)</span></td>
<td><span class="math inline">\(24 %\)</span></td>
</tr>
</tbody>
</table>
<p>在给定性别、种族和教育的情况下，<span class="math inline">\(\log (\)</span> 工资 <span class="math inline">\()\)</span> 的条件期望是每个类别的单个数字。例如</p>
<p><span class="math display">\[
\mathbb{E}[\log (\text { wage }) \mid \text { gender }=\text { man, race }=\text { white, education }=12]=2.84 .
\]</span></p>
<p>我们在图 <span class="math inline">\(2.3\)</span> 中显示了 <span class="math inline">\(\log\)</span>（工资）作为教育函数的条件期望，分别针对（白人）男性和女性。剧情相当有内涵。我们看到，有条件的期望在受教育年限中增加，但在九年以上和以下的学校教育水平上以不同的速度增长。图 <span class="math inline">\(2.3\)</span> 的另一个显着特点是男女之间的差距在所有教育水平上大致保持不变。由于变量是用对数来衡量的，这意味着无论受教育程度如何，男性和女性之间的平均百分比差距都是恒定的。</p>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-07.jpg" class="img-fluid"></p>
<p>图 2.3：预期对数工资与教育 tion=20 的函数关系。在许多情况下，通过使用单个字符（通常是 <span class="math inline">\(Y, X\)</span> 和/或 <span class="math inline">\(Z\)</span>）编写变量来简化符号是很方便的。计量经济学习惯用字母 <span class="math inline">\(Y\)</span> 表示因变量（例如 <span class="math inline">\(\log (\)</span> 工资 <span class="math inline">\()\)</span> ），用字母 <span class="math inline">\(X\)</span> 表示条件变量（例如性别），以及多个条件变量（例如种族，教育和性别）由下标字母 <span class="math inline">\(X_{1}, X_{2}, \ldots, X_{k}\)</span>。</p>
<p>条件期望可以用通用符号来写</p>
<p><span class="math display">\[
\mathbb{E}\left[Y \mid X_{1}=x_{1}, X_{2}=x_{2}, \ldots, X_{k}=x_{k}\right]=m\left(x_{1}, x_{2}, \ldots, x_{k}\right) \text {. }
\]</span></p>
<p>我们称之为条件期望函数（CEF）。 CEF 是 <span class="math inline">\(\left(x_{1}, x_{2}, \ldots, x_{k}\right)\)</span> 的函数，因为它随变量而变化。例如，<span class="math inline">\(Y=\log (\)</span> 工资 <span class="math inline">\()\)</span> 给定 <span class="math inline">\(\left(X_{1}, X_{2}\right)=(g e n d e r\)</span>,race) 的条件期望由表 <span class="math inline">\(2.1 .\)</span> 的六个条目给出</p>
<p>为了更紧凑，我们通常将条件变量写为 <span class="math inline">\(\mathbb{R}^{k}\)</span> 中的向量：</p>
<p><span class="math display">\[
X=\left(\begin{array}{c}
X_{1} \\
X_{2} \\
\vdots \\
X_{k}
\end{array}\right)
\]</span></p>
<p>给定这个符号，CEF 可以紧凑地写为</p>
<p><span class="math display">\[
\mathbb{E}[Y \mid X=x]=m(x) .
\]</span></p>
<p>CEF <span class="math inline">\(m(x)=\mathbb{E}[Y \mid X=x]\)</span> 是 <span class="math inline">\(x \in \mathbb{R}^{k}\)</span> 的函数。它说：“当 <span class="math inline">\(X\)</span> 取 <span class="math inline">\(x\)</span> 的值时，<span class="math inline">\(Y\)</span> 的平均值是 <span class="math inline">\(m(x)\)</span>。”有时将 CEF 视为随机变量 <span class="math inline">\(X\)</span> 的函数很有用。在这种情况下，我们在 <span class="math inline">\(X\)</span> 处评估函数 <span class="math inline">\(m(x)\)</span>，并写成 <span class="math inline">\(m(X)\)</span> 或 <span class="math inline">\(\mathbb{E}[Y \mid X]\)</span>。这是随机的，因为它是随机变量 <span class="math inline">\(X\)</span> 的函数。</p>
</section>
<section id="连续变量" class="level2">
<h2 class="anchored" data-anchor-id="连续变量">连续变量</h2>
<p>在前面的部分中，我们隐含地假设条件变量是离散的。然而，许多条件变量是连续的。在本节中，我们将采用这种情况并假设变量 <span class="math inline">\((Y, X)\)</span> 以联合密度函数 <span class="math inline">\(f(y, x)\)</span> 连续分布。</p>
<p>以 <span class="math inline">\(Y=\log (\)</span> 工资 <span class="math inline">\()\)</span> 和 <span class="math inline">\(X=\)</span> 经验为例，后者是潜在劳动力市场经验的年数 <span class="math inline">\({ }^{8}\)</span>。对于受过 12 年教育的白人男性人口，他们的联合密度等值线绘制在图 <span class="math inline">\(2.4\)</span> (a) 中。</p>
<p>给定联合密度 <span class="math inline">\(f(y, x)\)</span> 变量 <span class="math inline">\(x\)</span> 具有边际密度</p>
<p><span class="math display">\[
f_{X}(x)=\int_{-\infty}^{\infty} f(y, x) d y .
\]</span></p>
<p>对于任何 <span class="math inline">\(x\)</span> 使得 <span class="math inline">\(f_{X}(x)&gt;0\)</span> 给定 <span class="math inline">\(X\)</span> 的 <span class="math inline">\(Y\)</span> 的条件密度定义为</p>
<p><span class="math display">\[
f_{Y \mid X}(y \mid x)=\frac{f(y, x)}{f_{X}(x)} .
\]</span></p>
<p>条件密度是保持 <span class="math inline">\(x\)</span> 固定的联合密度 <span class="math inline">\(f(y, x)\)</span> 的重新归一化切片。切片被重新归一化（除以 <span class="math inline">\(f_{X}(x)\)</span> 以便积分为一），因此是一个密度。我们可以通过在与 <span class="math inline">\(y\)</span> 轴平行的特定值 <span class="math inline">\(x\)</span> 处切片联合密度函数来可视化这一点。例如，取图 2.4(a) 中的密度等值线，并在特定的经验值处切开等值线图，并且</p>
<p><span class="math inline">\({ }^{8}\)</span> 由于没有直接衡量经验，我们将经验定义为 age-education-6</p>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-09.jpg" class="img-fluid"></p>
<ol type="a">
<li>对数工资和经验的联合密度</li>
</ol>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-09(1).jpg" class="img-fluid"></p>
<ol start="2" type="a">
<li>给定经验的对数工资的条件密度</li>
</ol>
<p>图 2.4：日志工资和经验</p>
<p>然后重新归一化切片，使其具有适当的密度。这为我们提供了具有 12 年教育和这种经验水平的白人男性对数（工资）的条件密度。我们对三个级别的经验 <span class="math inline">\((5,10\)</span> 和 25 年执行此操作，并将这些密度绘制在图 <span class="math inline">\(2.4\)</span> (b) 中。我们可以看到，随着经验的增加，工资分布向右移动并变得更加分散。</p>
<p>给定 <span class="math inline">\(X=x\)</span> 的 <span class="math inline">\(Y\)</span> 的 CEF 是条件密度 (2.5) 的期望</p>
<p><span class="math display">\[
m(x)=\mathbb{E}[Y \mid X=x]=\int_{-\infty}^{\infty} y f_{Y \mid X}(y \mid x) d y .
\]</span></p>
<p>直观地说，<span class="math inline">\(m(x)\)</span> 是条件变量固定在 <span class="math inline">\(x\)</span> 的理想化子群体的 <span class="math inline">\(Y\)</span> 的期望值。当 <span class="math inline">\(X\)</span> 连续分布时，这个子群体无限小。</p>
<p>当条件密度（2.5）定义明确时，这个定义（2.6）是合适的。然而，<span class="math inline">\(2.31\)</span> 部分中的定理 <span class="math inline">\(2.13\)</span> 将表明 <span class="math inline">\(m(x)\)</span> 可以定义为任何随机变量 <span class="math inline">\((Y, X)\)</span>，只要 <span class="math inline">\(\mathbb{E}|Y|&lt;\infty\)</span></p>
<p>在图 2.4(a) 中，给定经验的 <span class="math inline">\(\log\)</span>（工资）的 CEF 绘制为实线。我们可以看到 CEF 是一个平滑但非线性的函数。 CEF 最初在经验上增加，在经验 <span class="math inline">\(=30\)</span> 附近趋于平缓，然后随着经验水平的提高而降低。</p>
</section>
<section id="迭代期望定律" class="level2">
<h2 class="anchored" data-anchor-id="迭代期望定律">迭代期望定律</h2>
<p>概率论中一个非常有用的工具是迭代期望定律。一个重要的特殊情况被称为简单定律。定理 2.1 迭代期望的简单定律</p>
<p>如果 <span class="math inline">\(\mathbb{E}|Y|&lt;\infty\)</span> 那么对于任何随机向量 <span class="math inline">\(X\)</span>，</p>
<p><span class="math display">\[
\mathbb{E}[\mathbb{E}[Y \mid X]]=\mathbb{E}[Y] .
\]</span></p>
<p>这表明有条件期望的期望是无条件期望。换句话说，条件平均值的平均值是无条件平均值。对于离散 <span class="math inline">\(X\)</span></p>
<p><span class="math display">\[
\mathbb{E}[\mathbb{E}[Y \mid X]]=\sum_{j=1}^{\infty} \mathbb{E}\left[Y \mid X=x_{j}\right] \mathbb{P}\left[X=x_{j}\right] .
\]</span></p>
<p>对于连续 <span class="math inline">\(X\)</span></p>
<p><span class="math display">\[
\mathbb{E}[\mathbb{E}[Y \mid X]]=\int_{\mathbb{R}^{k}} \mathbb{E}[Y \mid X=x] f_{X}(x) d x .
\]</span></p>
<p>回到我们对男性和女性平均原木工资的调查，简单的法律规定：</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\mathbb{E}[\log (\text { wage }) \mid \text { gender }=\text { man }] \mathbb{P}[\text { gender }=\text { man }] \\
&amp;+\mathbb{E}[\log (\text { wage }) \mid \text { gender }=\text { woman }] \mathbb{P}[\text { gender }=\text { woman }] \\
&amp;=\mathbb{E}[\log (\text { wage })]
\end{aligned}
\]</span></p>
<p>或者在数字上，</p>
<p><span class="math display">\[
3.05 \times 0.57+2.81 \times 0.43=2.95 \text {. }
\]</span></p>
<p>迭代期望的一般规律允许两组条件变量。</p>
<p>定理 2.2 迭代期望定律 如果 <span class="math inline">\(\mathbb{E}|Y|&lt;\infty\)</span> 那么对于任何随机向量 <span class="math inline">\(X_{1}\)</span> 和 <span class="math inline">\(X_{2}\)</span>，</p>
<p><span class="math display">\[
\mathbb{E}\left[\mathbb{E}\left[Y \mid X_{1}, X_{2}\right] \mid X_{1}\right]=\mathbb{E}\left[Y \mid X_{1}\right] .
\]</span></p>
<p>注意法律的适用方式。 <span class="math inline">\(X_{1}\)</span> 和 <span class="math inline">\(X_{2}\)</span> 上的内部期望条件，而外部期望仅在 <span class="math inline">\(X_{1}\)</span> 上条件。迭代的期望产生简单的答案 <span class="math inline">\(\mathbb{E}\left[Y \mid X_{1}\right]\)</span>，期望仅以 <span class="math inline">\(X_{1}\)</span> 为条件。有时我们将其表述为：“较小的信息集获胜。”</p>
<p>举个例子</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\mathbb{E}[\log (\text { wage }) \mid \text { gender }=\text { man, race }=\text { white }] \mathbb{P}[\text { race }=\text { white } \mid \text { gender }=\text { man }] \\
&amp;+\mathbb{E}[\log (\text { wage }) \mid \text { gender }=\text { man, race }=\text { Black }] \mathbb{P}[\text { race }=\text { Black } \mid \text { gender }=\text { man }] \\
&amp;+\mathbb{E}[\log (\text { wage }) \mid \text { gender }=\text { man, race }=\text { other }] \mathbb{P}[\text { race }=\text { other } \mid \text { gender }=\text { man }] \\
&amp;=\mathbb{E}[\log (\text { wage }) \mid \text { gender }=\text { man }]
\end{aligned}
\]</span></p>
<p>或数字上</p>
<p><span class="math display">\[
3.07 \times 0.84+2.86 \times 0.08+3.03 \times 0.08=3.05 \text {. }
\]</span></p>
<p>条件期望的一个属性是，当您以随机向量 <span class="math inline">\(X\)</span> 为条件时，您可以有效地将其视为常数。例如，对于任何函数 <span class="math inline">\(g(\cdot)\)</span>，<span class="math inline">\(\mathbb{E}[X \mid X]=X\)</span> 和 <span class="math inline">\(\mathbb{E}[g(X) \mid X]=g(X)\)</span>。一般性质称为条件定理。</p>
<p>定理 2.3 条件定理 如果 <span class="math inline">\(\mathbb{E}|Y|&lt;\infty\)</span> 那么</p>
<p><span class="math display">\[
\mathbb{E}[g(X) Y \mid X]=g(X) \mathbb{E}[Y \mid X] .
\]</span></p>
<p>如果另外 <span class="math inline">\(\mathbb{E}|g(X)|&lt;\infty\)</span> 那么</p>
<p><span class="math display">\[
\mathbb{E}[g(X) Y]=\mathbb{E}[g(X) \mathbb{E}[Y \mid X]] .
\]</span></p>
<p>定理 2.1、<span class="math inline">\(2.2\)</span> 和 <span class="math inline">\(2.3\)</span> 的证明在 <span class="math inline">\(2.33 .\)</span> 部分给出</p>
</section>
<section id="cef-错误" class="level2">
<h2 class="anchored" data-anchor-id="cef-错误">CEF 错误</h2>
<p>CEF 错误 <span class="math inline">\(e\)</span> 定义为 <span class="math inline">\(Y\)</span> 与在 <span class="math inline">\(X\)</span> 评估的 CEF 之间的差异：</p>
<p><span class="math display">\[
e=Y-m(X) .
\]</span></p>
<p>通过构造，这产生了公式</p>
<p><span class="math display">\[
Y=m(X)+e .
\]</span></p>
<p>在 (2.9) 中，理解误差 <span class="math inline">\(e\)</span> 是从 <span class="math inline">\((Y, X)\)</span> 的联合分布导出的，因此它的性质是从这个构造导出的，这很有用。</p>
<p>许多计量经济学作者使用希腊字母 <span class="math inline">\(\varepsilon\)</span> 来表示 CEF 错误。我不遵循这个约定，因为错误 <span class="math inline">\(e\)</span> 是一个类似于 <span class="math inline">\(Y\)</span> 和 <span class="math inline">\(X\)</span> 的随机变量，并且通常使用拉丁字符作为随机变量。</p>
<p>CEF 错误的一个关键特性是它的条件期望为零。要看到这一点，通过期望的线性、<span class="math inline">\(m(X)=\mathbb{E}[Y \mid X]\)</span> 的定义和条件定理</p>
<p><span class="math display">\[
\begin{aligned}
\mathbb{E}[e \mid X] &amp;=\mathbb{E}[(Y-m(X)) \mid X] \\
&amp;=\mathbb{E}[Y \mid X]-\mathbb{E}[m(X) \mid X] \\
&amp;=m(X)-m(X)=0 .
\end{aligned}
\]</span></p>
<p>这个事实可以结合迭代期望定律来证明无条件期望也是零。</p>
<p><span class="math display">\[
\mathbb{E}[e]=\mathbb{E}[\mathbb{E}[e \mid X]]=\mathbb{E}[0]=0 .
\]</span></p>
<p>我们正式陈述这一点和其他一些结果。</p>
<p>定理 2.4 CEF 误差的性质</p>
<p>如果 <span class="math inline">\(\mathbb{E}|Y|&lt;\infty\)</span> 那么</p>
<ol type="1">
<li><p><span class="math inline">\(\mathbb{E}[e \mid X]=0\)</span>。</p></li>
<li><p><span class="math inline">\(\mathbb{E}[e]=0\)</span>。</p></li>
<li><p>如果 <span class="math inline">\(\mathbb{E}|Y|^{r}&lt;\infty\)</span> 对应 <span class="math inline">\(r \geq 1\)</span> 那么 <span class="math inline">\(\mathbb{E}|e|^{r}&lt;\infty\)</span>。</p></li>
<li><p>对于任何函数 <span class="math inline">\(h(x)\)</span> 使得 <span class="math inline">\(\mathbb{E}|h(X) e|&lt;\infty\)</span> 然后 <span class="math inline">\(\mathbb{E}[h(X) e]=0\)</span>。第三个结果的证明推迟到 2.33 节。第四个结果的证明留给练习 2.3，这意味着 <span class="math inline">\(e\)</span> 与回归量的任何函数都不相关。</p></li>
</ol>
<p>方程</p>
<p><span class="math display">\[
\begin{aligned}
Y &amp;=m(X)+e \\
\mathbb{E}[e \mid X] &amp;=0
\end{aligned}
\]</span></p>
<p>一起暗示 <span class="math inline">\(m(X)\)</span> 是给定 <span class="math inline">\(X\)</span> 的 <span class="math inline">\(Y\)</span> 的 CEF。重要的是要了解这不是限制。根据定义，这些等式成立。</p>
<p>条件 <span class="math inline">\(\mathbb{E}[e \mid X]=0\)</span> 被 <span class="math inline">\(e\)</span> 的定义隐含为 <span class="math inline">\(Y\)</span> 和 CEF <span class="math inline">\(m(X)\)</span> 之间的差。方程 <span class="math inline">\(\mathbb{E}[e \mid X]=0\)</span> 有时称为条件均值限制，因为误差 <span class="math inline">\(e\)</span> 的条件均值被限制为零。该属性有时也称为平均独立性，因为 <span class="math inline">\(e\)</span> 的条件平均值为 0，因此独立于 <span class="math inline">\(X\)</span>。但是，这并不意味着 <span class="math inline">\(e\)</span> 的分布独立于 <span class="math inline">\(X\)</span>。有时添加假设“<span class="math inline">\(e\)</span> 独立于 <span class="math inline">\(X\)</span>”是为了方便简化，但它不是条件均值的通用特征。通常，即使 <span class="math inline">\(e\)</span> 的条件均值为零，<span class="math inline">\(e\)</span> 和 <span class="math inline">\(X\)</span> 也是共同依赖的。</p>
<p>例如，对于与图 2.4 相同的总体，回归误差 <span class="math inline">\(e\)</span> 和经验的联合密度等值线绘制在图 <span class="math inline">\(2.5\)</span> 中。请注意，条件分布的形状随经验水平而变化。</p>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-12.jpg" class="img-fluid"></p>
<p>劳动力市场经验（年）</p>
<p>图 2.5：回归误差和经验的联合密度</p>
<p>作为一个简单的例子，其中 <span class="math inline">\(X\)</span> 和 <span class="math inline">\(e\)</span> 均值独立但相互依赖，让 <span class="math inline">\(e=X u\)</span> 其中 <span class="math inline">\(X\)</span> 和 <span class="math inline">\(u\)</span> 是独立的 <span class="math inline">\(\mathrm{N}(0,1)\)</span>。然后以 <span class="math inline">\(X\)</span> 为条件，错误 <span class="math inline">\(e\)</span> 具有分布 <span class="math inline">\(\mathrm{N}\left(0, X^{2}\right)\)</span>。因此 <span class="math inline">\(\mathbb{E}[e \mid X]=0\)</span> 和 <span class="math inline">\(e\)</span> 均值独立于 <span class="math inline">\(X\)</span>，但 <span class="math inline">\(e\)</span> 并不完全独立于 <span class="math inline">\(X\)</span>。平均独立并不意味着完全独立。</p>
</section>
<section id="仅拦截模型" class="level2">
<h2 class="anchored" data-anchor-id="仅拦截模型">仅拦截模型</h2>
<p>回归模型的一个特例是没有回归变量 <span class="math inline">\(X\)</span>。在这种情况下 <span class="math inline">\(m(X)=\mathbb{E}[Y]=\mu\)</span>，<span class="math inline">\(Y\)</span> 的无条件期望。我们仍然可以为 <span class="math inline">\(Y\)</span> 写出回归格式的方程：</p>
<p><span class="math display">\[
\begin{aligned}
Y &amp;=\mu+e \\
\mathbb{E}[e] &amp;=0 .
\end{aligned}
\]</span></p>
<p>这对于统一符号很有用。</p>
</section>
<section id="回归方差" class="level2">
<h2 class="anchored" data-anchor-id="回归方差">回归方差</h2>
<p>CEF 函数离散度的一个重要度量是 CEF 误差 <span class="math inline">\(e\)</span> 的无条件方差。我们把它写成</p>
<p><span class="math display">\[
\sigma^{2}=\operatorname{var}[e]=\mathbb{E}\left[(e-\mathbb{E}[e])^{2}\right]=\mathbb{E}\left[e^{2}\right] .
\]</span></p>
<p>定理 2.4.3 暗示了以下简单但有用的结果。</p>
<p>定理 2.5 如果 <span class="math inline">\(\mathbb{E}\left[Y^{2}\right]&lt;\infty\)</span> 则 <span class="math inline">\(\sigma^{2}&lt;\infty\)</span>。</p>
<p>我们可以将 <span class="math inline">\(\sigma^{2}\)</span> 称为回归方差或回归误差的方差。 <span class="math inline">\(\sigma^{2}\)</span> 的大小衡量 <span class="math inline">\(Y\)</span> 中的变化量，这在条件期望 <span class="math inline">\(\mathbb{E}[Y \mid X]\)</span> 中没有“解释”或解释。</p>
<p>回归方差取决于回归量 <span class="math inline">\(X\)</span>。考虑两个回归</p>
<p><span class="math display">\[
\begin{aligned}
&amp;Y=\mathbb{E}\left[Y \mid X_{1}\right]+e_{1} \\
&amp;Y=\mathbb{E}\left[Y \mid X_{1}, X_{2}\right]+e_{2} .
\end{aligned}
\]</span></p>
<p>我们将这两个错误清楚地写为 <span class="math inline">\(e_{1}\)</span> 和 <span class="math inline">\(e_{2}\)</span>，因为它们是不同的——改变条件信息会改变条件期望，因此也会改变回归误差。</p>
<p>在我们对迭代期望的讨论中，我们已经看到，通过增加条件集，条件期望揭示了关于 <span class="math inline">\(Y\)</span> 分布的更多细节。回归误差的含义是什么？</p>
<p>事实证明，有一个简单的关系。我们可以将条件期望 <span class="math inline">\(\mathbb{E}[Y \mid X]\)</span> 视为 <span class="math inline">\(Y\)</span> 的“解释部分”。剩余的 <span class="math inline">\(e=Y-\mathbb{E}[Y \mid X]\)</span> 是“无法解释的部分”。我们现在推导出的简单关系表明，当我们以更多变量为条件时，这个无法解释的部分的方差会减小。这种关系是单调的，因为增加信息量总是会降低无法解释部分的方差。</p>
<p>定理 2.6 如果 <span class="math inline">\(\mathbb{E}\left[Y^{2}\right]&lt;\infty\)</span> 那么</p>
<p><span class="math display">\[
\operatorname{var}[Y] \geq \operatorname{var}\left[Y-\mathbb{E}\left[Y \mid X_{1}\right]\right] \geq \operatorname{var}\left[Y-\mathbb{E}\left[Y \mid X_{1}, X_{2}\right]\right] .
\]</span></p>
<p>定理 <span class="math inline">\(2.6\)</span> 表示，每当向条件信息中添加一个附加变量时，<span class="math inline">\(Y\)</span> 与其条件期望之间的差异方差（弱）就会减小。</p>
<p>定理 <span class="math inline">\(2.6\)</span> 的证明在 2.33 节给出。</p>
</section>
<section id="最佳预测者" class="level2">
<h2 class="anchored" data-anchor-id="最佳预测者">最佳预测者</h2>
<p>假设给定一个随机向量 <span class="math inline">\(X\)</span>，我们想要预测或预测 <span class="math inline">\(Y\)</span>。我们可以将任何预测器写成 <span class="math inline">\(X\)</span> 的函数 <span class="math inline">\(g(X)\)</span>。 （事后）预测误差是实现的差异 <span class="math inline">\(Y-g(X)\)</span>。预测误差大小的非随机度量是其平方的期望</p>
<p><span class="math display">\[
\mathbb{E}\left[(Y-g(X))^{2}\right] .
\]</span></p>
<p>我们可以将最佳预测器定义为最小化 (2.10) 的函数 <span class="math inline">\(g(X)\)</span>。什么函数是最好的预测器？事实证明，答案是 CEF <span class="math inline">\(m(X)\)</span>。无论 <span class="math inline">\((Y, X)\)</span> 的联合分布如何，这都成立。</p>
<p>要看到这一点，请注意预测变量 <span class="math inline">\(g(X)\)</span> 的均方误差是</p>
<p><span class="math display">\[
\begin{aligned}
\mathbb{E}\left[(Y-g(X))^{2}\right] &amp;=\mathbb{E}\left[(e+m(X)-g(X))^{2}\right] \\
&amp;=\mathbb{E}\left[e^{2}\right]+2 \mathbb{E}[e(m(X)-g(X))]+\mathbb{E}\left[(m(X)-g(X))^{2}\right] \\
&amp;=\mathbb{E}\left[e^{2}\right]+\mathbb{E}\left[(m(X)-g(X))^{2}\right] \\
&amp; \geq \mathbb{E}\left[e^{2}\right] \\
&amp;=\mathbb{E}\left[(Y-m(X))^{2}\right] .
\end{aligned}
\]</span></p>
<p>第一个等式进行替换 <span class="math inline">\(Y=m(X)+e\)</span>，第三个等式使用定理 2.4.4。通过设置 <span class="math inline">\(g(X)=m(X)\)</span> 最小化第三个等式后的右手边，产生第四行的不等式。如定理 <span class="math inline">\(2.5\)</span> 所示，在假设 <span class="math inline">\(\mathbb{E}\left[Y^{2}\right]&lt;\infty\)</span> 下最小值是有限的。</p>
<p>我们在下面的结果中正式说明了这一点。</p>
<p>定理 2.7 条件期望作为最佳预测器 如果 <span class="math inline">\(\mathbb{E}\left[Y^{2}\right]&lt;\infty\)</span>，那么对于任何预测器 <span class="math inline">\(g(X)\)</span>，</p>
<p><span class="math display">\[
\mathbb{E}\left[(Y-g(X))^{2}\right] \geq \mathbb{E}\left[(Y-m(X))^{2}\right]
\]</span></p>
<p><span class="math inline">\(m(X)=\mathbb{E}[Y \mid X]\)</span></p>
<p>在仅截取模型的上下文中考虑此结果可能会有所帮助</p>
<p><span class="math display">\[
\begin{aligned}
Y &amp;=\mu+e \\
\mathbb{E}[e] &amp;=0 .
\end{aligned}
\]</span></p>
<p>定理 <span class="math inline">\(2.7\)</span> 表明，<span class="math inline">\(Y\)</span>（在常量类中）的最佳预测器是无条件均值 <span class="math inline">\(\mu=\mathbb{E}[Y]\)</span>，因为均值使均方预测误差最小化。</p>
</section>
<section id="条件方差" class="level2">
<h2 class="anchored" data-anchor-id="条件方差">条件方差</h2>
<p>虽然条件均值可以很好地衡量条件分布的位置，但它不能提供有关分布分布的信息。分散度的常用度量是条件方差。我们首先给出随机变量 <span class="math inline">\(Y\)</span> 的条件方差的一般定义。</p>
<p>定义2.1 如果<span class="math inline">\(\mathbb{E}\left[Y^{2}\right]&lt;\infty\)</span>，给定<span class="math inline">\(X=x\)</span>，<span class="math inline">\(Y\)</span>的条件方差为</p>
<p><span class="math display">\[
\sigma^{2}(x)=\operatorname{var}[Y \mid X=x]=\mathbb{E}\left[(Y-\mathbb{E}[Y \mid X=x])^{2} \mid X=x\right] .
\]</span></p>
<p>被视为随机变量的条件方差是 <span class="math inline">\(\operatorname{var}[Y \mid X]=\sigma^{2}(X)\)</span>。</p>
<p>条件方差不同于无条件方差 var <span class="math inline">\([Y]\)</span>。不同之处在于条件方差是条件变量的函数。请注意，条件方差是条件二阶矩，以条件一阶矩为中心。</p>
<p>给定这个定义，我们定义回归误差的条件方差。</p>
<p>定义 2.2 如果 <span class="math inline">\(\mathbb{E}\left[e^{2}\right]&lt;\infty\)</span>，则给定 <span class="math inline">\(X=x\)</span> 的回归误差 <span class="math inline">\(e\)</span> 的条件方差为</p>
<p><span class="math display">\[
\sigma^{2}(x)=\operatorname{var}[e \mid X=x]=\mathbb{E}\left[e^{2} \mid X=x\right] .
\]</span></p>
<p><span class="math inline">\(e\)</span> 被视为随机变量的条件方差是 <span class="math inline">\(\operatorname{var}[e \mid X]=\sigma^{2}(X)\)</span>。</p>
<p>同样，条件方差 <span class="math inline">\(\sigma^{2}(x)\)</span> 与无条件方差 <span class="math inline">\(\sigma^{2}\)</span> 不同。条件方差是回归量的函数，无条件方差不是。通常，<span class="math inline">\(\sigma^{2}(x)\)</span> 是 <span class="math inline">\(x\)</span> 的一个非平凡函数，并且可以采用任何形式，但必须限制它为非负数。考虑 <span class="math inline">\(\sigma^{2}(x)\)</span> 的一种方法是，它是给定 <span class="math inline">\(X\)</span> 的 <span class="math inline">\(e^{2}\)</span> 的条件均值。还要注意 <span class="math inline">\(\sigma^{2}(x)=\operatorname{var}[Y \mid X=x]\)</span> 所以它等效地是因变量的条件方差。</p>
<p><span class="math inline">\(Y\)</span> 的方差与 <span class="math inline">\(Y\)</span> 的度量单位不同。为了将方差转换为相同的度量单位，我们将条件标准差定义为其平方根 <span class="math inline">\(\sigma(x)=\sqrt{\sigma^{2}(x)}\)</span>。</p>
<p>作为条件方差如何依赖于可观察值的示例，比较图 2.2 中显示的男性和女性的条件对数工资密度。密度之间的差异不仅是位置偏移，而且也是传播差异。具体来说，我们可以看到男性的对数工资密度比女性的分布更分散，而女性的工资密度则更峰值。事实上，男性工资的条件标准差是 <span class="math inline">\(3.05\)</span>，女性工资的条件标准差是 <span class="math inline">\(2.81\)</span>。因此，虽然男性的平均工资较高，但他们也更加分散。</p>
<p>无条件方差通过以下恒等式与条件方差相关。</p>
<p>定理 2.8 如果 <span class="math inline">\(\mathbb{E}\left[Y^{2}\right]&lt;\infty\)</span> 那么</p>
<p><span class="math display">\[
\operatorname{var}[Y]=\mathbb{E}[\operatorname{var}[Y \mid X]]+\operatorname{var}[\mathbb{E}[Y \mid X]] .
\]</span></p>
<p>参见经济学家的概率和统计定理 <span class="math inline">\(4.14\)</span>。定理 <span class="math inline">\(2.8\)</span> 将无条件方差分解为有时称为“组内方差”和“组间方差”的变量。例如，如果 <span class="math inline">\(X\)</span> 是教育水平，那么第一项是教育水平的条件期望的期望方差。第二项是控制教育后的方差。</p>
<p>回归误差的条件均值为零，因此它的无条件误差方差等于期望的条件方差，或者等效地可以通过迭代期望定律找到。</p>
<p><span class="math display">\[
\sigma^{2}=\mathbb{E}\left[e^{2}\right]=\mathbb{E}\left[\mathbb{E}\left[e^{2} \mid X\right]\right]=\mathbb{E}\left[\sigma^{2}(X)\right] .
\]</span></p>
<p>也就是说，无条件误差方差是平均条件方差。</p>
<p>给定条件方差，我们可以定义重新调整的误差</p>
<p><span class="math display">\[
u=\frac{e}{\sigma(X)} \text {. }
\]</span></p>
<p>我们计算出，因为 <span class="math inline">\(\sigma(X)\)</span> 是 <span class="math inline">\(X\)</span> 的函数</p>
<p><span class="math display">\[
\mathbb{E}[u \mid X]=\mathbb{E}\left[\frac{e}{\sigma(X)} \mid X\right]=\frac{1}{\sigma(X)} \mathbb{E}[e \mid X]=0
\]</span></p>
<p>和</p>
<p><span class="math display">\[
\operatorname{var}[u \mid X]=\mathbb{E}\left[u^{2} \mid X\right]=\mathbb{E}\left[\frac{e^{2}}{\sigma^{2}(X)} \mid X\right]=\frac{1}{\sigma^{2}(X)} \mathbb{E}\left[e^{2} \mid X\right]=\frac{\sigma^{2}(X)}{\sigma^{2}(X)}=1 .
\]</span></p>
<p>因此 <span class="math inline">\(u\)</span> 的条件期望为零，条件方差为 1。</p>
<p>注意 (2.11) 可以重写为</p>
<p><span class="math display">\[
e=\sigma(X) u .
\]</span></p>
<p>并将其替换为 CEF 方程 (2.9) 中的 <span class="math inline">\(e\)</span>，我们发现</p>
<p><span class="math display">\[
Y=m(X)+\sigma(X) u .
\]</span></p>
<p>这是 CEF 方程的另一种（均值方差）表示。</p>
<p>许多计量经济学研究侧重于条件期望 <span class="math inline">\(m(x)\)</span>，要么忽略条件方差 <span class="math inline">\(\sigma^{2}(x)\)</span>，将其视为常数 <span class="math inline">\(\sigma^{2}(x)=\sigma^{2}\)</span>，要么将其视为令人讨厌的参数（不是主要关注的参数）。当条件分布的主要变化处于均值时，这是合适的，但在其他情况下可能是短视的。分散与许多经济主题相关，包括收入和财富分配、经济不平等和价格分散。条件色散（方差）可能是一个富有成果的研究课题。</p>
<p>在一个经典笑话中模仿了狭隘地关注平均值的反常后果：</p>
<p>一位经济学家一只脚站在一桶开水里，另一只脚站在一桶冰里。当被问及感觉如何时，他回答说：“平均而言，我感觉还不错。”</p>
<p>显然，有问题的经济学家忽略了方差！</p>
</section>
<section id="同方差和异方差" class="level2">
<h2 class="anchored" data-anchor-id="同方差和异方差">同方差和异方差</h2>
<p>当条件方差 <span class="math inline">\(\sigma^{2}(x)\)</span> 是一个常数并且独立于 <span class="math inline">\(x\)</span> 时，会出现一个重要的特殊情况。这称为同方差。</p>
<p>定义 2.3 如果 <span class="math inline">\(\sigma^{2}(x)=\sigma^{2}\)</span> 不依赖于 <span class="math inline">\(x\)</span>，则该误差是同方差的。</p>
<p>在 <span class="math inline">\(\sigma^{2}(x)\)</span> 取决于 <span class="math inline">\(x\)</span> 的一般情况下，我们说错误 <span class="math inline">\(e\)</span> 是异方差的。</p>
<p>定义 2.4 如果 <span class="math inline">\(\sigma^{2}(x)\)</span> 依赖于 <span class="math inline">\(x\)</span>，则误差是异方差的。</p>
<p>理解同方差和异方差的概念与条件方差有关，而不是无条件方差，这是有帮助的。根据定义，无条件方差 <span class="math inline">\(\sigma^{2}\)</span> 是一个常数，并且独立于回归量 <span class="math inline">\(X\)</span>。因此，当我们谈论作为回归量函数的方差时，我们谈论的是条件方差 <span class="math inline">\(\sigma^{2}(x)\)</span>。</p>
<p>一些较旧或介绍性的教科书将异方差描述为“<span class="math inline">\(e\)</span> 的方差随观察而变化”的情况。这是一个糟糕且令人困惑的定义。理解异方差性意味着条件方差 <span class="math inline">\(\sigma^{2}(x)\)</span> 取决于可观察量更具建设性。</p>
<p>较旧的教科书也倾向于将同方差描述为正确回归规范的组成部分，并将异方差描述为异常或偏差。这种描述影响了几代经济学家，但不幸的是它倒退了。正确的观点是异方差是通用的和“标准的”，而同方差是不寻常的和例外的。实证工作的默认设置应该是假设误差是异方差的，而不是相反的。</p>
<p>与上述陈述明显矛盾的是，在对估计和推理方法的性质进行理论研究时，我们仍然会经常强加同方差假设。原因是在很多情况下，同方差极大地简化了理论计算，因此对教学非常有利。然而，应该永远记住，同方差性从未被强加，因为它被认为是经验模型的正确特征，而是因为它的简单性。</p>
</section>
<section id="异方差还是异方差" class="level2">
<h2 class="anchored" data-anchor-id="异方差还是异方差">异方差还是异方差？</h2>
<p>同方差和异方差这两个词的拼写有些争议。早期的计量经济学教科书是分裂的，有些使用“c”作为异方差，有些使用“<span class="math inline">\(\mathrm{k}\)</span>”作为异方差。 McCulloch (1985) 指出这个词来源于希腊语词根。</p>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-17.jpg" class="img-fluid">\ 意思是“分散”。由于在 <span class="math inline">\(\sigma \kappa \varepsilon \delta \alpha v v v \mu \iota\)</span> 中希腊字母 <span class="math inline">\(\kappa\)</span> 的正确音译是“<span class="math inline">\(\mathrm{k}\)</span>”，这意味着这两个单词的正确英文拼写是“<span class="math inline">\(\mathrm{k}\)</span>”，如同方差和异方差。</p>
</section>
<section id="回归导数" class="level2">
<h2 class="anchored" data-anchor-id="回归导数">回归导数</h2>
<p>解释 CEF <span class="math inline">\(m(x)=\mathbb{E}[Y \mid X=x]\)</span> 的一种方法是根据回归量 <span class="math inline">\(X\)</span> 的边际变化如何暗示响应变量 <span class="math inline">\(Y\)</span> 的条件期望的变化。通常考虑单个回归量的边际变化，比如 <span class="math inline">\(X_{1}\)</span>，保持余数不变。当回归量 <span class="math inline">\(X_{1}\)</span> 连续分布时，我们定义 <span class="math inline">\(X_{1}\)</span> 变化的边际效应，保持变量 <span class="math inline">\(X_{2}, \ldots, X_{k}\)</span> 固定，作为 CEF 的偏导数</p>
<p><span class="math display">\[
\frac{\partial}{\partial x_{1}} m\left(x_{1}, \ldots, x_{k}\right)
\]</span></p>
<p>当 <span class="math inline">\(X_{1}\)</span> 是离散的时，我们将边际效应定义为离散差。例如，如果 <span class="math inline">\(X_{1}\)</span> 是二元的，那么 <span class="math inline">\(X_{1}\)</span> 对 CEF 的边际效应是</p>
<p><span class="math display">\[
m\left(1, x_{2}, \ldots, x_{k}\right)-m\left(0, x_{2}, \ldots, x_{k}\right)
\]</span></p>
<p>我们可以用符号统一连续和离散的情况</p>
<p><span class="math display">\[
\nabla_{1} m(x)=\left\{\begin{array}{cc}
\frac{\partial}{\partial x_{1}} m\left(x_{1}, \ldots, x_{k}\right), &amp; \text { if } X_{1} \text { is continuous } \\
m\left(1, x_{2}, \ldots, x_{k}\right)-m\left(0, x_{2}, \ldots, x_{k}\right), &amp; \text { if } X_{1} \text { is binary. }
\end{array}\right.
\]</span></p>
<p>将 <span class="math inline">\(k\)</span> 效应收集到一个 <span class="math inline">\(k \times 1\)</span> 向量中，我们定义关于 <span class="math inline">\(X\)</span> 的回归导数：</p>
<p><span class="math display">\[
\nabla m(x)=\left[\begin{array}{c}
\nabla_{1} m(x) \\
\nabla_{2} m(x) \\
\vdots \\
\nabla_{k} m(x)
\end{array}\right]
\]</span></p>
<p>当 <span class="math inline">\(X\)</span> 的所有元素都是连续的时，我们有简化的 <span class="math inline">\(\nabla m(x)=\frac{\partial}{\partial x} m(x)\)</span>，即偏导数的向量。</p>
<p>关于回归导数的定义，有两点需要记住。首先，在保持其他变量不变的情况下计算每个变量的影响。这是经济学中常用的其他条件不变的概念。但是在回归导数的情况下，条件期望并不能真正保持其他所有条件不变。它只保持条件期望中包含的变量不变。这意味着回归导数取决于包含哪些回归量。例如，在工资对教育、经验、种族和性别的回归中，关于教育的回归导数显示了教育对预期工资的边际效应，保持不变的经验、种族和性别。但它并不保持个人不可观察的特征（如能力）和回归中未包含的变量（如教育质量）保持不变。</p>
<p>其次，回归导数是 <span class="math inline">\(Y\)</span> 的条件期望的变化，而不是 <span class="math inline">\(Y\)</span> 对个人的实际价值的变化。很容易将回归导数视为 <span class="math inline">\(Y\)</span> 实际值的变化，但这不是正确的解释。只有当误差 <span class="math inline">\(e\)</span> 不受回归量 <span class="math inline">\(X\)</span> 变化的影响时，回归导数 <span class="math inline">\(\nabla m(x)\)</span> 才是 <span class="math inline">\(Y\)</span> 实际值的变化。我们回到第 2.30 节中对因果效应的讨论。</p>
</section>
<section id="线性-cef" class="level2">
<h2 class="anchored" data-anchor-id="线性-cef">线性 CEF</h2>
<p>一个重要的特殊情况是 CEF <span class="math inline">\(m(x)=\mathbb{E}[Y \mid X=x]\)</span> 在 <span class="math inline">\(x\)</span> 中是线性的。在这种情况下，我们可以将平均方程写为</p>
<p><span class="math display">\[
m(x)=x_{1} \beta_{1}+x_{2} \beta_{2}+\cdots+x_{k} \beta_{k}+\beta_{k+1} .
\]</span></p>
<p>从符号上讲，把它写成向量 <span class="math inline">\(x\)</span> 的简单函数很方便。一个简单的方法是通过将数字“1”列为元素来增加回归向量 <span class="math inline">\(X\)</span>。我们将此称为“常数”，相应的系数称为“截距”。等效地，指定向量 <span class="math inline">\(x\)</span> 的最后一个元素 <span class="math inline">\({ }^{9}\)</span> 是 <span class="math inline">\(x_{k}=1\)</span>。因此 (2.4) 被重新定义为 <span class="math inline">\(k \times 1\)</span> 向量</p>
<p><span class="math display">\[
X=\left(\begin{array}{c}
X_{1} \\
X_{2} \\
\vdots \\
X_{k-1} \\
1
\end{array}\right)
\]</span></p>
<p>通过这个重新定义，CEF 是</p>
<p><span class="math display">\[
m(x)=x_{1} \beta_{1}+x_{2} \beta_{2}+\cdots+\beta_{k}=x^{\prime} \beta
\]</span></p>
<p>在哪里</p>
<p><span class="math display">\[
\beta=\left(\begin{array}{c}
\beta_{1} \\
\vdots \\
\beta_{k}
\end{array}\right)
\]</span></p>
<p>是一个 <span class="math inline">\(k \times 1\)</span> 系数向量。这是线性 CEF 模型。它也经常被称为线性回归模型，或 <span class="math inline">\(Y\)</span> 对 <span class="math inline">\(X\)</span> 的回归。</p>
<p>在线性 CEF 模型中，回归导数就是系数向量。那是 <span class="math inline">\(\nabla m(x)=\beta\)</span>。这是线性 CEF 模型的吸引人的特征之一。作为改变一个变量而保持其他变量不变的边际效应，这些系数具有简单而自然的解释。</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\text { Linear CEF Model } \\
&amp;\begin{aligned}
Y &amp;=X^{\prime} \beta+e \\
\mathbb{E}[e \mid X] &amp;=0
\end{aligned}
\end{aligned}
\]</span></p>
<p>如果另外误差是同方差的，我们称之为同方差线性 CEF 模型。</p>
</section>
<section id="同方差线性-cef-模型" class="level2">
<h2 class="anchored" data-anchor-id="同方差线性-cef-模型">同方差线性 CEF 模型</h2>
<p><span class="math display">\[
\begin{aligned}
Y &amp;=X^{\prime} \beta+e \\
\mathbb{E}[e \mid X] &amp;=0 \\
\mathbb{E}\left[e^{2} \mid X\right] &amp;=\sigma^{2}
\end{aligned}
\]</span></p>
<p><span class="math inline">\({ }^{9}\)</span> 顺序无关紧要。它可以是任何元素。</p>
</section>
<section id="具有非线性效应的线性-cef" class="level2">
<h2 class="anchored" data-anchor-id="具有非线性效应的线性-cef">具有非线性效应的线性 CEF</h2>
<p>上一节的线性 CEF 模型没有看起来那么严格，因为我们可以将原始变量的非线性变换作为回归量。从这个意义上说，线性 CEF 框架是灵活的，可以捕捉许多非线性效应。</p>
<p>例如，假设我们有两个标量变量 <span class="math inline">\(X_{1}\)</span> 和 <span class="math inline">\(X_{2}\)</span>。 CEF 可以采用二次形式</p>
<p><span class="math display">\[
m\left(x_{1}, x_{2}\right)=x_{1} \beta_{1}+x_{2} \beta_{2}+x_{1}^{2} \beta_{3}+x_{2}^{2} \beta_{4}+x_{1} x_{2} \beta_{5}+\beta_{6} .
\]</span></p>
<p>这个方程在回归变量 <span class="math inline">\(\left(x_{1}, x_{2}\right)\)</span> 中是二次的，但在系数 <span class="math inline">\(\beta=\left(\beta_{1}, \ldots, \beta_{6}\right)^{\prime}\)</span> 中是线性的。我们仍然称 (2.14) 为线性 CEF，因为它是系数的线性函数。同时，它具有非线性效应，因为它在基础变量 <span class="math inline">\(x_{1}\)</span> 和 <span class="math inline">\(x_{2}\)</span> 中是非线性的。关键是要理解 (2.14) 在变量 <span class="math inline">\(\left(x_{1}, x_{2}\right)\)</span> 中是二次的，但在系数 <span class="math inline">\(\beta\)</span> 中是线性的。</p>
<p>为了简化表达式，我们定义了变换 <span class="math inline">\(x_{3}=x_{1}^{2}, x_{4}=x_{2}^{2}, x_{5}=x_{1} x_{2}\)</span> 和 <span class="math inline">\(x_{6}=1\)</span>，并将回归向量重新定义为 <span class="math inline">\(x=\left(x_{1}, \ldots, x_{6}\right)^{\prime}\)</span>。通过这个重新定义，<span class="math inline">\(m\left(x_{1}, x_{2}\right)=x^{\prime} \beta\)</span> 在 <span class="math inline">\(\beta\)</span> 中是线性的。对于大多数计量经济学目的（对 <span class="math inline">\(\beta\)</span> 的估计和推断），<span class="math inline">\(\beta\)</span> 中的线性是最重要的。</p>
<p>一个例外是回归导数的分析。在诸如 (2.14) 等非线性方程中，回归导数应针对原始变量定义，而不是针对转换后的变量。因此</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\frac{\partial}{\partial x_{1}} m\left(x_{1}, x_{2}\right)=\beta_{1}+2 x_{1} \beta_{3}+x_{2} \beta_{5} \\
&amp;\frac{\partial}{\partial x_{2}} m\left(x_{1}, x_{2}\right)=\beta_{2}+2 x_{2} \beta_{4}+x_{1} \beta_{5} .
\end{aligned}
\]</span></p>
<p>我们看到，在模型（2.14）中，回归导数不是一个简单的系数，而是几个系数加上 <span class="math inline">\(\left(x_{1}, x_{2}\right)\)</span> 的水平的函数。因此，很难单独解释这些系数。将它们解释为一个组更有用。</p>
<p>我们通常将 <span class="math inline">\(\beta_{5}\)</span> 称为交互效应。请注意，它出现在两个回归导数方程中，并且在每个方程中都有一个对称的解释。如果 <span class="math inline">\(\beta_{5}&gt;0\)</span> 那么关于 <span class="math inline">\(x_{1}\)</span> 的回归导数在 <span class="math inline">\(x_{2}\)</span> 的水平上增加（并且关于 <span class="math inline">\(x_{2}\)</span> 的回归导数在 <span class="math inline">\(x_{1}\)</span> 的水平上增加），而如果 <span class="math inline">\(\beta_{5}&lt;0\)</span>反之亦然。</p>
</section>
<section id="带有虚拟变量的线性-cef" class="level2">
<h2 class="anchored" data-anchor-id="带有虚拟变量的线性-cef">带有虚拟变量的线性 CEF</h2>
<p>当所有回归量都取一组有限的值时，结果证明 CEF 可以写成回归量的线性函数。</p>
<p>这个最简单的例子是一个二进制变量，它只接受两个不同的值。例如，在传统数据集中，变量性别只取值男人和女人（或男性和女性）。二元变量在计量经济学应用中极为常见，也称为虚拟变量或指标变量。</p>
<p>考虑单个二元回归器的简单情况。在这种情况下，条件期望只能取两个不同的值。例如，</p>
<p><span class="math display">\[
\mathbb{E}[Y \mid \text { gender }]=\left\{\begin{array}{llc}
\mu_{0} &amp; \text { if } \quad \text { gender }=\text { man } \\
\mu_{1} &amp; \text { if gender }=\text { woman. }
\end{array}\right.
\]</span></p>
<p>为了便于数学处理，我们用值 <span class="math inline">\(\{0,1\}\)</span> 记录虚拟变量。例如</p>
<p><span class="math display">\[
X_{1}=\left\{\begin{array}{llc}
0 &amp; \text { if } &amp; \text { gender }=\text { man } \\
1 &amp; \text { if } &amp; \text { gender }=\text { woman } .
\end{array}\right.
\]</span></p>
<p>给定这个符号，我们将条件期望写成虚拟变量 <span class="math inline">\(X_{1}\)</span> 的线性函数。因此 <span class="math inline">\(\mathbb{E}\left[Y \mid X_{1}\right]=\beta_{1} X_{1}+\beta_{2}\)</span> 其中 <span class="math inline">\(\beta_{1}=\mu_{1}-\mu_{0}\)</span> 和 <span class="math inline">\(\beta_{2}=\mu_{0}\)</span>。在这个简单的回归方程中，截距 <span class="math inline">\(\beta_{2}\)</span> 等于 <span class="math inline">\(X_{1}=0\)</span> 子群体（男性）的条件期望 <span class="math inline">\(Y\)</span>，斜率 <span class="math inline">\(\beta_{1}\)</span> 等于两个子群体之间条件期望的差异。</p>
<p>或者，我们可以将 <span class="math inline">\(X_{1}\)</span> 定义为</p>
<p><span class="math display">\[
X_{1}= \begin{cases}1 &amp; \text { if } \quad \text { gender }=\text { man } \\ 0 &amp; \text { if } \quad \text { gender }=\text { woman } .\end{cases}
\]</span></p>
<p>在这种情况下，回归截距是对女性（而不是男性）的期望，并且回归斜率已转换符号。这两个回归是等价的，但系数的解释发生了变化。因此，理解变量的精确定义总是很重要的，并且说明性的标签很有帮助。例如，将 <span class="math inline">\(X_{1}\)</span> 标记为“性别”无助于区分定义 (2.15) 和 (2.16)。相反，如果使用定义 (2.15)，最好将 <span class="math inline">\(X_{1}\)</span> 标记为“女性”或“女性”，如果使用定义 (2.16)，则将其标记为“男性”或“男性”。</p>
<p>现在假设我们有两个虚拟变量 <span class="math inline">\(X_{1}\)</span> 和 <span class="math inline">\(X_{2}\)</span>。例如，如果此人已婚，则为 <span class="math inline">\(X_{2}=1\)</span>，否则为 <span class="math inline">\(X_{2}=0\)</span>。给定 <span class="math inline">\(X_{1}\)</span> 和 <span class="math inline">\(X_{2}\)</span> 的条件期望最多取四个可能的值：</p>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-21.jpg" class="img-fluid"></p>
<p>在这种情况下，我们可以将条件均值写为 <span class="math inline">\(X, X_{2}\)</span> 及其乘积 <span class="math inline">\(X_{1} X_{2}\)</span> 的线性函数：</p>
<p><span class="math display">\[
\mathbb{E}\left[Y \mid X_{1}, X_{2}\right]=\beta_{1} X_{1}+\beta_{2} X_{2}+\beta_{3} X_{1} X_{2}+\beta_{4}
\]</span></p>
<p>其中 <span class="math inline">\(\beta_{1}=\mu_{10}-\mu_{00}, \beta_{2}=\mu_{01}-\mu_{00}, \beta_{3}=\mu_{11}-\mu_{10}-\mu_{01}+\mu_{00}\)</span> 和 <span class="math inline">\(\beta_{4}=\mu_{00}\)</span>。</p>
<p>我们可以将系数 <span class="math inline">\(\beta_{1}\)</span> 视为性别对未婚工薪者预期对数工资的影响，将系数 <span class="math inline">\(\beta_{2}\)</span> 视为婚姻对男性工薪者预期对数工资的影响，并将系数 <span class="math inline">\(\beta_{3}\)</span> 视为差异婚姻对女性和男性预期对数工资的影响之间的关系。或者，它也可以解释为性别对已婚和未婚工资收入者的预期对数工资的影响之间的差异。两种解释同样有效。我们经常将 <span class="math inline">\(\beta_{3}\)</span> 描述为衡量两个虚拟变量之间的交互作用，或交互效应，而将 <span class="math inline">\(\beta_{3}=0\)</span> 描述为交互效应为零的情况。</p>
<p>在这个设置中，我们可以看到 CEF 在三个变量 <span class="math inline">\(\left(X_{1}, X_{2}, X_{1} X_{2}\right)\)</span> 中是线性的。为了将模型放入 <span class="math inline">\(2.15\)</span> 部分的框架中，我们将回归量 <span class="math inline">\(X_{3}=X_{1} X_{2}\)</span> 和回归量向量定义为</p>
<p><span class="math display">\[
X=\left(\begin{array}{c}
X_{1} \\
X_{2} \\
X_{3} \\
1
\end{array}\right) .
\]</span></p>
<p>因此，虽然我们从两个虚拟变量开始，但回归量（包括截距）的数量是四个。</p>
<p>如果有三个虚拟变量 <span class="math inline">\(X_{1}, X_{2}, X_{3}\)</span>，那么 <span class="math inline">\(\mathbb{E}\left[Y \mid X_{1}, X_{2}, X_{3}\right]\)</span> 最多取 <span class="math inline">\(2^{3}=8\)</span> 不同的值，并且可以写成线性函数</p>
<p><span class="math display">\[
\mathbb{E}\left[Y \mid X_{1}, X_{2}, X_{3}\right]=\beta_{1} X_{1}+\beta_{2} X_{2}+\beta_{3} X_{3}+\beta_{4} X_{1} X_{2}+\beta_{5} X_{1} X_{3}+\beta_{6} X_{2} X_{3}+\beta_{7 X 1} X_{2} X_{3}+\beta_{8}
\]</span></p>
<p>它有八个回归量，包括截距。一般来说，如果有 <span class="math inline">\(p\)</span> 虚拟变量 <span class="math inline">\(X_{1}, \ldots, X_{p}\)</span> 那么 CEF <span class="math inline">\(\mathbb{E}\left[Y \mid X_{1}, X_{2}, \ldots, X_{p}\right]\)</span> 最多取 <span class="math inline">\(2^{p}\)</span> 不同的值，并且可以写成 <span class="math inline">\(2^{p}\)</span> 回归量的线性函数，包括 <span class="math inline">\(X_{1}, X_{2}, \ldots, X_{p}\)</span> 和所有交叉产品。包含所有 <span class="math inline">\(2^{p}\)</span> 二元相互作用的线性回归模型称为饱和虚拟变量回归模型。它是条件期望的完整模型。相反，没有交互作用的模型等于</p>
<p><span class="math display">\[
\mathbb{E}\left[Y \mid X_{1}, X_{2}, \ldots, X_{p}\right]=\beta_{1} X_{1}+\beta_{2} X_{2}+\cdots+\beta_{p} X_{p}+\beta_{p} .
\]</span></p>
<p>这有 <span class="math inline">\(p+1\)</span> 系数而不是 <span class="math inline">\(2^{p}\)</span>。</p>
<p>我们在本节开始时说，只要所有回归器只取有限数量的可能值，条件期望就是线性的。我们怎么能看到这个？取一个分类变量，例如种族。例如，我们之前将种族分为三类。我们可以记录分类变量，使用数字来表示每个类别，例如</p>
<p><span class="math display">\[
X_{3}=\left\{\begin{array}{lll}
1 &amp; \text { if } &amp; \text { white } \\
2 &amp; \text { if } &amp; \text { Black } \\
3 &amp; \text { if } &amp; \text { other. }
\end{array}\right.
\]</span></p>
<p>这样做时，<span class="math inline">\(X_{3}\)</span> 的值在量级方面没有意义，它们只是表示相关类别。</p>
<p>当回归量是分类的时，给定 <span class="math inline">\(X_{3}\)</span> 的条件期望 <span class="math inline">\(Y\)</span> 对每种可能性取一个不同的值：</p>
<p><span class="math display">\[
\mathbb{E}\left[Y \mid X_{3}\right]=\left\{\begin{array}{lll}
\mu_{1} &amp; \text { if } &amp; X_{3}=1 \\
\mu_{2} &amp; \text { if } &amp; X_{3}=2 \\
\mu_{3} &amp; \text { if } &amp; X_{3}=3 .
\end{array}\right.
\]</span></p>
<p>这不是 <span class="math inline">\(X_{3}\)</span> 本身的线性函数，但可以通过为三个类别中的两个构建虚拟变量来使其成为线性函数。例如</p>
<p><span class="math display">\[
\begin{aligned}
&amp;X_{4}=\left\{\begin{array}{llc}
1 &amp; \text { if } &amp; \text { Black } \\
0 &amp; \text { if } &amp; \text { not Black }
\end{array}\right. \\
&amp;X_{5}=\left\{\begin{array}{lll}
1 &amp; \text { if } &amp; \text { other } \\
0 &amp; \text { if } &amp; \text { not other. }
\end{array}\right.
\end{aligned}
\]</span></p>
<p>在这种情况下，分类变量 <span class="math inline">\(X_{3}\)</span> 等价于一对虚拟变量 <span class="math inline">\(\left(X_{4}, X_{5}\right)\)</span>。显式关系是</p>
<p><span class="math display">\[
X_{3}=\left\{\begin{array}{lll}
1 &amp; \text { if } &amp; X_{4}=0 \text { and } X_{5}=0 \\
2 &amp; \text { if } &amp; X_{4}=1 \text { and } X_{5}=0 \\
3 &amp; \text { if } &amp; X_{4}=0 \text { and } X_{5}=1
\end{array}\right.
\]</span></p>
<p>鉴于这些转换，我们可以将 <span class="math inline">\(Y\)</span> 的条件期望写成 <span class="math inline">\(X_{4}\)</span> 和 <span class="math inline">\(X_{5}\)</span> 的线性函数</p>
<p><span class="math display">\[
\mathbb{E}\left[Y \mid X_{3}\right]=\mathbb{E}\left[Y \mid X_{4}, X_{5}\right]=\beta_{1} X_{4}+\beta_{2} X_{5}+\beta_{3} .
\]</span></p>
<p>我们可以将 CEF 写成 <span class="math inline">\(\mathbb{E}\left[Y \mid X_{3}\right]\)</span> 或 <span class="math inline">\(\mathbb{E}\left[Y \mid X_{4}, X_{5}\right]\)</span>（它们是等价的），但它只是 <span class="math inline">\(X_{4}\)</span> 和 <span class="math inline">\(X_{5}\)</span> 的线性函数。</p>
<p>此设置类似于两个虚拟变量的情况，不同之处在于我们没有包括交互项 <span class="math inline">\(X_{4} X_{5}\)</span>。这是因为事件 <span class="math inline">\(\left\{X_{4}=1\right.\)</span> 和 <span class="math inline">\(\left.X_{5}=1\right\}\)</span> 在构造上是空的，所以 <span class="math inline">\(X_{4} X_{5}=0\)</span> 根据定义。</p>
</section>
<section id="最佳线性预测器" class="level2">
<h2 class="anchored" data-anchor-id="最佳线性预测器">最佳线性预测器</h2>
<p>虽然条件期望 <span class="math inline">\(m(X)=\mathbb{E}[Y \mid X]\)</span> 是 <span class="math inline">\(X\)</span> 的所有函数中 <span class="math inline">\(Y\)</span> 的最佳预测器，但它的函数形式通常是未知的。特别是，线性 CEF 模型在经验上不太可能准确，除非 <span class="math inline">\(X\)</span> 是离散且低维的，因此包含所有交互作用。因此，在大多数情况下，将线性规范 (2.13) 视为近似值更为现实。在本节中，我们通过简单的解释得出一个特定的近似值。</p>
<p>定理 <span class="math inline">\(2.7\)</span> 表明条件期望 <span class="math inline">\(m(X)\)</span> 是最好的预测器，因为它在所有预测器中均方误差最低。通过扩展，我们可以通过所有线性预测变量中均方误差最小的线性函数来定义 CEF 的近似值。</p>
<p>对于这个推导，我们需要以下正则性条件。</p>
<p>假设 <span class="math inline">\(2.1\)</span></p>
<ol type="1">
<li><span class="math inline">\(\mathbb{E}\left[Y^{2}\right]&lt;\infty\)</span></li>
<li><span class="math inline">\(\mathbb{E}\|X\|^{2}&lt;\infty\)</span></li>
<li><span class="math inline">\(\boldsymbol{Q}_{X X}=\mathbb{E}\left[X X^{\prime}\right]\)</span> 是正定的。</li>
</ol>
<p>在假设 2.1.2 中，我们使用 <span class="math inline">\(\|x\|=\left(x^{\prime} x\right)^{1 / 2}\)</span> 来表示向量 <span class="math inline">\(x\)</span> 的欧几里得长度。</p>
<p>假设 <span class="math inline">\(2.1\)</span> 的前两部分暗示变量 <span class="math inline">\(Y\)</span> 和 <span class="math inline">\(X\)</span> 具有有限的均值、方差和协方差。假设的第三部分更具技术性，其作用很快就会显现出来。相当于强加矩阵 <span class="math inline">\(\boldsymbol{Q}_{X X}=\mathbb{E}\left[X X^{\prime}\right]\)</span> 的列是线性独立的并且矩阵是可逆的。</p>
<p><span class="math inline">\(Y\)</span> 的线性预测器是某个 <span class="math inline">\(\beta \in \mathbb{R}^{k}\)</span> 的函数 <span class="math inline">\(X^{\prime} \beta\)</span>。均方预测误差为</p>
<p><span class="math display">\[
S(\beta)=\mathbb{E}\left[\left(Y-X^{\prime} \beta\right)^{2}\right] .
\]</span></p>
<p>给定 <span class="math inline">\(X\)</span> 的 <span class="math inline">\(Y\)</span> 的最佳线性预测器，写成 <span class="math inline">\(\mathscr{P}[Y \mid X]\)</span>，是通过选择使 <span class="math inline">\(S(\beta)\)</span> 最小化的 <span class="math inline">\(\beta\)</span> 来找到的。</p>
<p>定义 2.5 给定 <span class="math inline">\(X\)</span> 的 <span class="math inline">\(Y\)</span> 的最佳线性预测器是</p>
<p><span class="math display">\[
\mathscr{P}[Y \mid X]=X^{\prime} \beta
\]</span></p>
<p>其中 <span class="math inline">\(\beta\)</span> 最小化均方预测误差</p>
<p><span class="math display">\[
S(\beta)=\mathbb{E}\left[\left(Y-X^{\prime} \beta\right)^{2}\right] .
\]</span></p>
<p>最小化器</p>
<p><span class="math display">\[
\beta=\underset{b \in \mathbb{R}^{k}}{\operatorname{argmin}} S(b)
\]</span></p>
<p>称为线性投影系数。我们现在计算其值的显式表达式。均方预测误差 (2.17) 可以写成 <span class="math inline">\(\beta\)</span> 的二次函数：</p>
<p><span class="math display">\[
S(\beta)=\mathbb{E}\left[Y^{2}\right]-2 \beta^{\prime} \mathbb{E}[X Y]+\beta^{\prime} \mathbb{E}\left[X X^{\prime}\right] \beta .
\]</span></p>
<p><span class="math inline">\(S(\beta)\)</span> 的二次结构意味着我们可以显式求解最小化器。最小化的一阶条件（来自附录 A.20）是</p>
<p><span class="math display">\[
0=\frac{\partial}{\partial \beta} S(\beta)=-2 \mathbb{E}[X Y]+2 \mathbb{E}\left[X X^{\prime}\right] \beta .
\]</span></p>
<p>将 <span class="math inline">\((2.20)\)</span> 重写为</p>
<p><span class="math display">\[
2 \mathbb{E}[X Y]=2 \mathbb{E}\left[X X^{\prime}\right] \beta
\]</span></p>
<p>并除以 2 ，这个方程的形式为</p>
<p><span class="math display">\[
\boldsymbol{Q}_{X Y}=\boldsymbol{Q}_{X X} \beta
\]</span></p>
<p>其中 <span class="math inline">\(\boldsymbol{Q}_{X Y}=\mathbb{E}[X Y]\)</span> 是 <span class="math inline">\(k \times 1\)</span> 而 <span class="math inline">\(\boldsymbol{Q}_{X X}=\mathbb{E}\left[X X^{\prime}\right]\)</span> 是 <span class="math inline">\(k \times k\)</span>。通过反转矩阵 <span class="math inline">\(\boldsymbol{Q}_{X X}\)</span> 找到解决方案，并写成</p>
<p><span class="math display">\[
\beta=\boldsymbol{Q}_{X X}^{-1} \boldsymbol{Q}_{X Y}
\]</span></p>
<p>或者</p>
<p><span class="math display">\[
\beta=\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X Y] .
\]</span></p>
<p>值得花时间理解表达式（2.22）中涉及的符号。 <span class="math inline">\(\boldsymbol{Q}_{X X}\)</span> 是 <span class="math inline">\(k \times k\)</span> 矩阵，<span class="math inline">\(\boldsymbol{Q}_{X Y}\)</span> 是 <span class="math inline">\(k \times 1\)</span> 列向量。因此，<span class="math inline">\(\frac{\mathbb{E}[X Y]}{\mathbb{E}\left[X X^{\prime}\right]}\)</span> 或 <span class="math inline">\(\mathbb{E}[X Y]\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1}\)</span> 等替代表达式是不连贯且不正确的。我们现在也可以看到假设 2.1.3 的作用。这等价于假设 <span class="math inline">\(\boldsymbol{Q}_{X X}\)</span> 有一个逆 <span class="math inline">\(\boldsymbol{Q}_{X X}^{-1}\)</span>，这是正规方程 (2.21) 的解唯一所必需的，并且等效地，对于 <span class="math inline">\((2.22)\)</span> 是唯一定义的。在没有假设 <span class="math inline">\(2.1 .3\)</span> 的情况下，方程 (2.21) 可能有多个解。</p>
<p>我们现在有一个最佳线性预测器的显式表达式：</p>
<p><span class="math display">\[
\mathscr{P}[Y \mid X]=X^{\prime}\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X Y] .
\]</span></p>
<p>这个表达式也被称为 <span class="math inline">\(Y\)</span> 在 <span class="math inline">\(X\)</span> 上的线性投影。</p>
<p>投影误差为</p>
<p><span class="math display">\[
e=Y-X^{\prime} \beta .
\]</span></p>
<p>当（且仅当）条件期望在 <span class="math inline">\(X\)</span> 中为线性时，这等于回归方程的误差 (2.9)，否则它们是不同的。</p>
<p>重写，我们将 <span class="math inline">\(Y\)</span> 分解为线性预测器和误差</p>
<p><span class="math display">\[
Y=X^{\prime} \beta+e .
\]</span></p>
<p>一般来说，我们称方程 (2.24) 或 <span class="math inline">\(X^{\prime} \beta\)</span> 为给定 <span class="math inline">\(X\)</span> 的 <span class="math inline">\(Y\)</span> 的最佳线性预测器，或 <span class="math inline">\(Y\)</span> 在 <span class="math inline">\(X\)</span> 上的线性投影。等式 (2.24) 也经常被称为 <span class="math inline">\(Y\)</span> 对 <span class="math inline">\(X\)</span> 的回归，但由于经济学家在许多情况下使用术语“回归”，这有时会令人困惑。 （回想一下，我们在 <span class="math inline">\(2.15\)</span> 节中说过，线性 CEF 模型也称为线性回归模型。）</p>
<p>投影误差 <span class="math inline">\(e\)</span> 的一个重要性质是</p>
<p><span class="math display">\[
\mathbb{E}[X e]=0 .
\]</span></p>
<p>要看到这一点，使用定义 (2.23) 和 (2.22) 以及矩阵属性 <span class="math inline">\(\boldsymbol{A} \boldsymbol{A}^{-1}=\boldsymbol{I}\)</span> 和 <span class="math inline">\(\boldsymbol{I} \boldsymbol{a}=\boldsymbol{a}\)</span>，</p>
<p><span class="math display">\[
\begin{aligned}
\mathbb{E}[X e] &amp;=\mathbb{E}\left[X\left(Y-X^{\prime} \beta\right)\right] \\
&amp;=\mathbb{E}[X Y]-\mathbb{E}\left[X X^{\prime}\right]\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X Y] \\
&amp;=0
\end{aligned}
\]</span></p>
<p>如声称的那样。</p>
<p>方程 (2.25) 是一组 <span class="math inline">\(k\)</span> 方程，每个回归量一个。换句话说，(2.25) 等价于</p>
<p><span class="math display">\[
\mathbb{E}\left[X_{j} e\right]=0
\]</span></p>
<p>对于 <span class="math inline">\(j=1, \ldots, k\)</span>。与 (2.12) 中一样，回归向量 <span class="math inline">\(X\)</span> 通常包含一个常数，例如<span class="math inline">\(X_{k}=1\)</span>。在这种情况下，<span class="math inline">\(j=k\)</span> 的 (2.27) 与</p>
<p><span class="math display">\[
\mathbb{E}[e]=0 .
\]</span></p>
<p>因此，当回归向量包含一个常数时，投影误差的平均值为零。 （当 <span class="math inline">\(X\)</span> 没有常数 (2.28) 时，不能保证。因为希望 <span class="math inline">\(e\)</span> 具有零均值，这是在任何回归模型中始终包含常数的一个很好的理由。）</p>
<p>观察到因为 <span class="math inline">\(\operatorname{cov}\left(X_{j}, e\right)=\mathbb{E}\left[X_{j} e\right]-\mathbb{E}\left[X_{j}\right] \mathbb{E}[e]\)</span>, then (2.27)-(2.28) 一起暗示变量 <span class="math inline">\(X_{j}\)</span> 和 <span class="math inline">\(e\)</span> 不相关也很有用。</p>
<p>这样就完成了模型的推导。我们总结了一些最重要的属性。</p>
<p>定理 2.9 线性投影模型的性质 在假设 2.1 下，</p>
<ol type="1">
<li>矩 <span class="math inline">\(\mathbb{E}\left[X X^{\prime}\right]\)</span> 和 <span class="math inline">\(\mathbb{E}[X Y]\)</span> 存在于有限元中。</li>
</ol>
<p>2.线性投影系数(2.18)存在，唯一，等于</p>
<p><span class="math display">\[
\beta=\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X Y] .
\]</span></p>
<ol type="1">
<li>给定 <span class="math inline">\(X\)</span> 的 <span class="math inline">\(Y\)</span> 的最佳线性预测器是</li>
</ol>
<p><span class="math display">\[
\mathscr{P}(Y \mid X)=X^{\prime}\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X Y] .
\]</span></p>
<p>1.存在投影误差<span class="math inline">\(e=Y-X^{\prime} \beta\)</span>。它满足 <span class="math inline">\(\mathbb{E}\left[e^{2}\right]&lt;\infty\)</span> 和 <span class="math inline">\(\mathbb{E}[X e]=0\)</span>。</p>
<ol start="2" type="1">
<li><p>如果<span class="math inline">\(X\)</span> 包含一个常数，那么<span class="math inline">\(\mathbb{E}[e]=0\)</span>。</p></li>
<li><p>如果 <span class="math inline">\(\mathbb{E}|Y|^{r}&lt;\infty\)</span> 和 <span class="math inline">\(\mathbb{E}\|X\|^{r}&lt;\infty\)</span> 对应 <span class="math inline">\(r \geq 2\)</span>，那么 <span class="math inline">\(\mathbb{E}|e|^{r}&lt;\infty\)</span>。</p></li>
</ol>
<p>定理 <span class="math inline">\(2.9\)</span> 的完整证明在第 2.33 节中给出。</p>
<p>反思定理 2.9 的一般性是有用的。唯一的限制是假设 2.1。因此，对于任何具有有限方差的随机变量 <span class="math inline">\((Y, X)\)</span>，我们可以定义一个具有定理 2.9 中列出的性质的线性方程 (2.24)。不需要更强的假设（例如线性 CEF 模型）。在这个意义上，线性模型（2.24）相当普遍地存在。但是，重要的是不要误解该声明的一般性。线性方程 (2.24) 被定义为最佳线性预测器。它不一定是条件均值，也不一定是结构或因果经济模型的参数。线性投影模型</p>
<p><span class="math display">\[
\begin{aligned}
Y &amp;=X^{\prime} \beta+e \\
\mathbb{E}[X e] &amp;=0 \\
\beta &amp;=\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X Y]
\end{aligned}
\]</span></p>
</section>
<section id="可逆性和识别" class="level2">
<h2 class="anchored" data-anchor-id="可逆性和识别">可逆性和识别</h2>
<p>只要 <span class="math inline">\(k \times k\)</span> 矩阵 <span class="math inline">\(\boldsymbol{Q}_{X X}=\mathbb{E}\left[X X^{\prime}\right]\)</span> 可逆，线性投影系数 <span class="math inline">\(\beta=\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X Y]\)</span> 就存在并且是唯一的。矩阵 <span class="math inline">\(\boldsymbol{Q}_{X X}\)</span> 通常被称为设计矩阵，因为在实验设置中，研究人员能够通过操纵回归量 <span class="math inline">\(X\)</span> 的分布来控制 <span class="math inline">\(\boldsymbol{Q}_{X X}\)</span>。</p>
<p>观察任何非零 <span class="math inline">\(\alpha \in \mathbb{R}^{k}\)</span>，</p>
<p><span class="math display">\[
\alpha^{\prime} \boldsymbol{Q}_{X X} \alpha=\mathbb{E}\left[\alpha^{\prime} X X^{\prime} \alpha\right]=\mathbb{E}\left[\left(\alpha^{\prime} X\right)^{2}\right] \geq 0
\]</span></p>
<p>所以 <span class="math inline">\(\boldsymbol{Q}_{X X}\)</span> 通过构造是半正定的，通常写为 <span class="math inline">\(\boldsymbol{Q}_{X X} \geq 0\)</span>。它是正定的假设意味着这是一个严格的不等式<span class="math inline">\(\mathbb{E}\left[\left(\alpha^{\prime} X\right)^{2}\right]&gt;0\)</span>。这通常写为 <span class="math inline">\(\boldsymbol{Q}_{X X}&gt;0\)</span>。这个条件意味着不存在与 <span class="math inline">\(\alpha^{\prime} X=0\)</span> 相同的非零向量 <span class="math inline">\(\alpha\)</span>。正定矩阵是可逆的。因此，当 <span class="math inline">\(\boldsymbol{Q}_{X X}&gt;0\)</span> 时 <span class="math inline">\(\beta=\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X Y]\)</span> 存在并且是唯一定义的。换句话说，如果我们可以排除 <span class="math inline">\(X\)</span> 的线性函数退化的可能性，那么 <span class="math inline">\(\beta\)</span> 是唯一定义的。</p>
<p>定理 <span class="math inline">\(2.5\)</span> 表明线性投影系数 <span class="math inline">\(\beta\)</span> 在假设 2.1 下被识别（唯一确定）。关键是 <span class="math inline">\(\boldsymbol{Q}_{X X}\)</span> 的可逆性。否则，方程没有唯一解</p>
<p><span class="math display">\[
\boldsymbol{Q}_{X X} \beta=\boldsymbol{Q}_{X Y} .
\]</span></p>
<p>当 <span class="math inline">\(\boldsymbol{Q}_{X X}\)</span> 不可逆时，(2.29) 有多种解。在这种情况下，系数 <span class="math inline">\(\beta\)</span> 没有被识别，因为它没有唯一值。</p>
</section>
<section id="最小化" class="level2">
<h2 class="anchored" data-anchor-id="最小化">最小化</h2>
<p>均方预测误差 (2.19) 是具有形式向量参数的函数</p>
<p><span class="math display">\[
f(x)=a-2 b^{\prime} x+x^{\prime} \boldsymbol{C} x
\]</span></p>
<p>其中 <span class="math inline">\(\boldsymbol{C}&gt;0\)</span>。对于这种形式的任何函数，唯一的最小化器是</p>
<p><span class="math display">\[
x=\boldsymbol{C}^{-1} b .
\]</span></p>
<p>为了看到这是唯一的最小化器，我们提供了两个证明。第一个使用矩阵微积分。来自附录 A.20</p>
<p><span class="math display">\[
\begin{gathered}
\frac{\partial}{\partial x}\left(b^{\prime} x\right)=b \\
\frac{\partial}{\partial x}\left(x^{\prime} \boldsymbol{C} x\right)=2 \boldsymbol{C} x \\
\frac{\partial^{2}}{\partial x \partial x^{\prime}}\left(x^{\prime} \boldsymbol{C} x\right)=2 \boldsymbol{C} .
\end{gathered}
\]</span></p>
<p>使用 (2.31) 和 (2.32)，我们发现</p>
<p><span class="math display">\[
\frac{\partial}{\partial x} f(x)=-2 b+2 \boldsymbol{C} x .
\]</span></p>
<p>最小化的一阶条件将此导数设置为零。因此解满足<span class="math inline">\(-2 b+2 \boldsymbol{C} x=0\)</span>。求解 <span class="math inline">\(x\)</span> 我们找到 (2.30)。使用 (2.33) 我们还发现</p>
<p><span class="math display">\[
\frac{\partial^{2}}{\partial x \partial x^{\prime}} f(x)=2 \boldsymbol{C}&gt;0
\]</span></p>
<p>这是最小化的二阶条件。这表明 (2.30) 是 <span class="math inline">\(f(x)\)</span> 的唯一最小值。</p>
<p>我们的第二个证明是代数的。将 <span class="math inline">\(f(x)\)</span> 重写为</p>
<p><span class="math display">\[
f(x)=\left(a-b^{\prime} \boldsymbol{C}^{-1} b\right)+\left(x-\boldsymbol{C}^{-1} b\right)^{\prime} \boldsymbol{C}\left(x-\boldsymbol{C}^{-1} b\right) .
\]</span></p>
<p>第一项不依赖于 <span class="math inline">\(x\)</span>，因此不影响最小化器。第二项是正定矩阵中的二次形式。这意味着对于任何非零 <span class="math inline">\(\alpha, \alpha^{\prime} \boldsymbol{C} \alpha&gt;0\)</span>。因此对于 <span class="math inline">\(x \neq C^{-1} b\)</span>，第二项是严格正数，而对于 <span class="math inline">\(x=C^{-1} b\)</span>，这个项等于 0。因此，如所声称的，它被最小化为 <span class="math inline">\(x=C^{-1} b\)</span>。</p>
</section>
<section id="最佳线性预测器的插图" class="level2">
<h2 class="anchored" data-anchor-id="最佳线性预测器的插图">最佳线性预测器的插图</h2>
<p>我们使用前面部分介绍的三个对数工资方程来说明最佳线性预测器（投影）。</p>
<p>对于我们的第一个示例，我们考虑一个具有性别和种族两个虚拟变量的模型，类似于表 2.1。正如我们在 2.17 节中了解到的，该表中的条目可以等效地用线性 CEF 表示。为简单起见，让我们将 <span class="math inline">\(\log (\)</span> 工资 <span class="math inline">\()\)</span> 的 CEF 视为 Black 和 female 的函数。</p>
<p><span class="math display">\[
\mathbb{E}[\log (\text { wage }) \mid \text { Black, female }]=-0.20 \text { Black }-0.24 \text { female }+0.10 \text { Black } \times \text { female }+3.06 \text {. }
\]</span></p>
<p>这是一个 CEF，因为变量是二元的并且包括所有交互。</p>
<p>现在考虑一个省略交互作用的更简单的模型。这是变量 Black 和 female 的线性投影</p>
<p><span class="math display">\[
\mathscr{P}[\log (\text { wage }) \mid \text { Black, female }]=-0.15 \text { Black }-0.23 \text { female }+3.06 .
\]</span></p>
<p>有什么区别？完整的 CEF (2.34) 表明种族差距按性别区分：黑人男性（相对于非黑人男性）为 <span class="math inline">\(20 %\)</span>，黑人女性（相对于非黑人女性）为 <span class="math inline">\(10 %\)</span>。投影模型 (2.35) 简化了这一分析，计算了黑人工薪阶层的平均 <span class="math inline">\(15 %\)</span> 工资差距，而忽略了性别的作用。请注意，尽管（2.35）中包含了性别这一事实。</p>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-28.jpg" class="img-fluid"></p>
<ol type="a">
<li>对教育的预测</li>
</ol>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-28(1).jpg" class="img-fluid"></p>
<ol start="2" type="a">
<li>对经验的预测</li>
</ol>
<p>图 2.6：对数工资对教育和经验的预测</p>
<p>对于我们的第二个示例，我们将对数工资的 CEF 视为白人男性受教育年限的函数，如图 <span class="math inline">\(2.3\)</span> 所示，并在图 2.6(a) 中重复。叠加在图上的是两个投影。第一个（由虚线给出）是对数工资对教育年限的线性投影</p>
<p><span class="math display">\[
\mathscr{P}[\log (\text { wage }) \mid \text { education }]=0.11 \text { education }+1.5 \text {. }
\]</span></p>
<p>这个简单的等式表明每受教育年的工资平均增加 <span class="math inline">\(11 %\)</span>。对该图的检查表明，这种近似值对教育 <span class="math inline">\(\geq 9\)</span> 很有效，但对教育水平较低的个人预测不足。为了纠正这种不平衡，我们使用了一个线性样条方程，它允许高于和低于 9 年教育的不同回报率：</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\mathscr{P}[\log (\text { wage }) \mid \text { education, }(\text { education }-9) \times \mathbb{1} \text { education }&gt;9\}] \\
&amp;=0.02 \text { education }+0.10 \times(\text { education }-9) \times \mathbb{1} \text { education }&gt;9\}+2.3 .
\end{aligned}
\]</span></p>
<p>这个方程用实线显示在图 2.6(a) 中，看起来拟合得更好。它表明每教育年低于 9 的平均工资增加 <span class="math inline">\(2 %\)</span>，并且每教育年超过 9 的平均工资增加 <span class="math inline">\(12 %\)</span>。它仍然是条件均值的近似值，但似乎相当合理。</p>
<p>对于我们的第三个示例，我们将受过 12 年教育的白人男性的对数工资的 CEF 作为多年经验的函数，如图 <span class="math inline">\(2.4\)</span> 所示，并在图 2.6(b) 中以实线重复。叠加在图上的是两个投影。第一个（由点划线给出）是经验的线性投影</p>
<p><span class="math display">\[
\mathscr{P}[\log (\text { wage }) \mid \text { experience }]=0.011 \text { experience }+2.5
\]</span></p>
<p>第二个（由虚线给出）是经验的线性投影及其平方</p>
<p><span class="math display">\[
\mathscr{P}[\log (\text { wage }) \mid \text { experience }]=0.046 \text { experience }-0.0007 \text { experience }^{2}+2.3 \text {. }
\]</span></p>
<p>从图 <span class="math inline">\(2.6(\mathrm{~b})\)</span> 的检查中可以清楚地看出，第一个线性投影是一个很差的近似值。它高估了年轻和年长工人的工资，低估了其余工人的工资，并错过了年长工薪阶层预期工资的强劲下滑。第二个投影更合适。我们可以称这个方程为二次投影，因为这个函数在经验上是二次的。</p>
</section>
<section id="线性预测误差方差" class="level2">
<h2 class="anchored" data-anchor-id="线性预测误差方差">线性预测误差方差</h2>
<p>与 CEF 模型一样，我们将误差方差定义为 <span class="math inline">\(\sigma^{2}=\mathbb{E}\left[e^{2}\right]\)</span>。设置 <span class="math inline">\(Q_{Y Y}=\mathbb{E}\left[Y^{2}\right]\)</span> 和 <span class="math inline">\(\boldsymbol{Q}_{Y X}=\)</span> <span class="math inline">\(\mathbb{E}\left[Y X^{\prime}\right]\)</span> 我们可以将 <span class="math inline">\(\sigma^{2}\)</span> 写为</p>
<p><span class="math display">\[
\begin{aligned}
\sigma^{2} &amp;=\mathbb{E}\left[\left(Y-X^{\prime} \beta\right)^{2}\right] \\
&amp;=\mathbb{E}\left[Y^{2}\right]-2 \mathbb{E}\left[Y X^{\prime}\right] \beta+\beta^{\prime} \mathbb{E}\left[X X^{\prime}\right] \beta \\
&amp;=Q_{Y Y}-2 \boldsymbol{Q}_{Y X} \boldsymbol{Q}_{X X}^{-1} \boldsymbol{Q}_{X Y}+\boldsymbol{Q}_{Y X} \boldsymbol{Q}_{X X}^{-1} \boldsymbol{Q}_{X X} \boldsymbol{Q}_{X X}^{-1} \boldsymbol{Q}_{X Y} \\
&amp;=Q_{Y Y}-\boldsymbol{Q}_{Y X} \boldsymbol{Q}_{X X}^{-1} \boldsymbol{Q}_{X Y} \\
&amp; \stackrel{\text { def }}{=} Q_{Y Y \cdot X} .
\end{aligned}
\]</span></p>
<p>这个公式的一个有用特征是它表明 <span class="math inline">\(Q_{Y Y \cdot X}=Q_{Y Y}-\boldsymbol{Q}_{Y X} \boldsymbol{Q}_{X X}^{-1} \boldsymbol{Q}_{X Y}\)</span> 等于 <span class="math inline">\(Y\)</span> 在 <span class="math inline">\(X\)</span> 上的线性投影的误差方差。</p>
</section>
<section id="回归系数" class="level2">
<h2 class="anchored" data-anchor-id="回归系数">回归系数</h2>
<p>有时将常数与其他回归量分开并将线性投影方程写成格式是有用的</p>
<p><span class="math display">\[
Y=X^{\prime} \beta+\alpha+e
\]</span></p>
<p>其中 <span class="math inline">\(\alpha\)</span> 是截距，<span class="math inline">\(X\)</span> 不包含常数。</p>
<p>考虑这个方程的期望，我们发现</p>
<p><span class="math display">\[
\mathbb{E}[Y]=\mathbb{E}\left[X^{\prime} \beta\right]+\mathbb{E}[\alpha]+\mathbb{E}[e]
\]</span></p>
<p>或 <span class="math inline">\(\mu_{Y}=\mu_{X}^{\prime} \beta+\alpha\)</span> 其中 <span class="math inline">\(\mu_{Y}=\mathbb{E}[Y]\)</span> 和 <span class="math inline">\(\mu_{X}=\mathbb{E}[X]\)</span>，因为 <span class="math inline">\(\mathbb{E}[e]=0\)</span> 来自 (2.28)。 （虽然 <span class="math inline">\(X\)</span> 不包含常数，但方程（2.28）仍然适用。）重新排列，我们找到 <span class="math inline">\(\alpha=\mu_{Y}-\mu_{X}^{\prime} \beta\)</span>。从（2.37）中减去这个方程，我们发现</p>
<p><span class="math display">\[
Y-\mu_{Y}=\left(X-\mu_{X}\right)^{\prime} \beta+e,
\]</span></p>
<p>中心变量 <span class="math inline">\(Y-\mu_{Y}\)</span> 和 <span class="math inline">\(X-\mu_{X}\)</span> 之间的线性方程。 （它们以均值为中心，均值为零的随机变量也是如此。）因为 <span class="math inline">\(X-\mu_{X}\)</span> 与 <span class="math inline">\(e\)</span> 不相关，所以 (2.38) 也是一个线性投影。因此由线性投影模型的公式，</p>
<p><span class="math display">\[
\begin{aligned}
\beta &amp;=\left(\mathbb{E}\left[\left(X-\mu_{X}\right)\left(X-\mu_{X}\right)^{\prime}\right]\right)^{-1} \mathbb{E}\left[\left(X-\mu_{X}\right)\left(Y-\mu_{Y}\right)\right] \\
&amp;=\operatorname{var}[X]^{-1} \operatorname{cov}(X, Y)
\end{aligned}
\]</span></p>
<p>仅是 <span class="math inline">\(X\)</span> 和 <span class="math inline">\(Y\)</span> 的协方差 <span class="math inline">\({ }^{10}\)</span> 的函数。</p>
<p>定理 2.10 在线性投影模型 <span class="math inline">\(Y=X^{\prime} \beta+\alpha+e\)</span> 中，</p>
<p><span class="math display">\[
\alpha=\mu_{Y}-\mu_{X}^{\prime} \beta
\]</span></p>
<p>和</p>
<p><span class="math display">\[
\beta=\operatorname{var}[X]^{-1} \operatorname{cov}(X, Y) .
\]</span></p>
</section>
<section id="回归子向量" class="level2">
<h2 class="anchored" data-anchor-id="回归子向量">回归子向量</h2>
<p>让回归量被划分为</p>
<p><span class="math display">\[
X=\left(\begin{array}{l}
X_{1} \\
X_{2}
\end{array}\right)
\]</span></p>
<p>我们可以将 <span class="math inline">\(Y\)</span> 在 <span class="math inline">\(X\)</span> 上的投影写成</p>
<p><span class="math display">\[
\begin{aligned}
Y &amp;=X^{\prime} \beta+e \\
&amp;=X_{1}^{\prime} \beta_{1}+X_{2}^{\prime} \beta_{2}+e \\
\mathbb{E}[X e] &amp;=0 .
\end{aligned}
\]</span></p>
<p>在本节中，我们推导出子向量 <span class="math inline">\(\beta_{1}\)</span> 和 <span class="math inline">\(\beta_{2}\)</span> 的公式。</p>
<p>分区 <span class="math inline">\(\boldsymbol{Q}_{X X}\)</span> 与 <span class="math inline">\(X\)</span> 一致</p>
<p><span class="math display">\[
\boldsymbol{Q}_{X X}=\left[\begin{array}{ll}
\boldsymbol{Q}_{11} &amp; \boldsymbol{Q}_{12} \\
\boldsymbol{Q}_{21} &amp; \boldsymbol{Q}_{22}
\end{array}\right]=\left[\begin{array}{ll}
\mathbb{E}\left[X_{1} X_{1}^{\prime}\right] &amp; \mathbb{E}\left[X_{1} X_{2}^{\prime}\right] \\
\mathbb{E}\left[X_{2} X_{1}^{\prime}\right] &amp; \mathbb{E}\left[X_{2} X_{2}^{\prime}\right]
\end{array}\right]
\]</span></p>
<p>同样地</p>
<p><span class="math display">\[
\boldsymbol{Q}_{X Y}=\left[\begin{array}{l}
\boldsymbol{Q}_{1 Y} \\
\boldsymbol{Q}_{2 Y}
\end{array}\right]=\left[\begin{array}{c}
\mathbb{E}\left[X_{1} Y\right] \\
\mathbb{E}\left[X_{2} Y\right]
\end{array}\right] .
\]</span></p>
<p>由分区矩阵求逆公式（A.3）</p>
<p><span class="math display">\[
\boldsymbol{Q}_{X X}^{-1}=\left[\begin{array}{ll}
\boldsymbol{Q}_{11} &amp; \boldsymbol{Q}_{12} \\
\boldsymbol{Q}_{21} &amp; \boldsymbol{Q}_{22}
\end{array}\right]^{-1} \stackrel{\operatorname{def}}{=}\left[\begin{array}{ll}
\boldsymbol{Q}^{11} &amp; \boldsymbol{Q}^{12} \\
\boldsymbol{Q}^{21} &amp; \boldsymbol{Q}^{22}
\end{array}\right]=\left[\begin{array}{cc}
\boldsymbol{Q}_{11 \cdot 2}^{-1} &amp; -\boldsymbol{Q}_{11 \cdot 2}^{-1} \boldsymbol{Q}_{12} \boldsymbol{Q}_{22}^{-1} \\
-\boldsymbol{Q}_{22 \cdot 1}^{-1} \boldsymbol{Q}_{21} \boldsymbol{Q}_{11}^{-1} &amp; \boldsymbol{Q}_{22 \cdot 1}^{-1}
\end{array}\right]
\]</span></p>
<p><span class="math inline">\({ }^{10}\)</span> 向量 <span class="math inline">\(X\)</span> 和 <span class="math inline">\(Z\)</span> 之间的协方差矩阵是 <span class="math inline">\(\operatorname{cov}(X, Z)=\mathbb{E}\left[(X-\mathbb{E}[X])(Z-\mathbb{E}[Z])^{\prime}\right]\)</span>。 <span class="math inline">\(\operatorname{vector} X\)</span> 的协方差矩阵是 <span class="math inline">\(\operatorname{var}[X]=\operatorname{cov}(X, X)=\mathbb{E}\left[(X-\mathbb{E}[X])(X-\mathbb{E}[X])^{\prime}\right]\)</span>。其中 <span class="math inline">\(\boldsymbol{Q}_{11 \cdot 2} \stackrel{\text { def }}{=} \boldsymbol{Q}_{11}-\boldsymbol{Q}_{12} \boldsymbol{Q}_{22}^{-1} \boldsymbol{Q}_{21}\)</span> 和 <span class="math inline">\(\boldsymbol{Q}_{22 \cdot 1} \stackrel{\text { def }}{=} \boldsymbol{Q}_{22}-\boldsymbol{Q}_{21} \boldsymbol{Q}_{11}^{-1} \boldsymbol{Q}_{12}\)</span>。因此</p>
<p><span class="math display">\[
\begin{aligned}
\beta &amp;=\left(\begin{array}{l}
\beta_{1} \\
\beta_{2}
\end{array}\right) \\
&amp;=\left[\begin{array}{cc}
\boldsymbol{Q}_{11 \cdot 2}^{-1} &amp; -\boldsymbol{Q}_{11 \cdot 2}^{-1} \boldsymbol{Q}_{12} \boldsymbol{Q}_{22}^{-1} \\
-\boldsymbol{Q}_{22 \cdot 1}^{-1} \boldsymbol{Q}_{21} \boldsymbol{Q}_{11}^{-1} &amp; \boldsymbol{Q}_{22 \cdot 1}^{-1}
\end{array}\right]\left[\begin{array}{l}
\boldsymbol{Q}_{1 Y} \\
\boldsymbol{Q}_{2 Y}
\end{array}\right] \\
&amp;=\left(\begin{array}{c}
\boldsymbol{Q}_{11 \cdot 2}^{-1}\left(\boldsymbol{Q}_{1 y}-\boldsymbol{Q}_{12} \boldsymbol{Q}_{22}^{-1} \boldsymbol{Q}_{2 Y}\right) \\
\boldsymbol{Q}_{22 \cdot 1}^{-1}\left(\boldsymbol{Q}_{2 y}-\boldsymbol{Q}_{21} \boldsymbol{Q}_{11}^{-1} \boldsymbol{Q}_{1 Y}\right)
\end{array}\right) \\
&amp;=\left(\begin{array}{c}
\boldsymbol{Q}_{11 \cdot 2}^{-1} \boldsymbol{Q}_{1 Y \cdot 2} \\
\boldsymbol{Q}_{22 \cdot 1}^{-1} \boldsymbol{Q}_{2 Y \cdot 1}
\end{array}\right)
\end{aligned}
\]</span></p>
<p>我们已经证明了 <span class="math inline">\(\beta_{1}=\boldsymbol{Q}_{11 \cdot 2}^{-1} \boldsymbol{Q}_{1 Y \cdot 2}\)</span> 和 <span class="math inline">\(\beta_{2}=\boldsymbol{Q}_{22 \cdot 1}^{-1} \boldsymbol{Q}_{2 Y \cdot 1}\)</span>。</p>
</section>
<section id="系数分解" class="level2">
<h2 class="anchored" data-anchor-id="系数分解">系数分解</h2>
<p>在上一节中，我们导出了系数子向量 <span class="math inline">\(\beta_{1}\)</span> 和 <span class="math inline">\(\beta_{2}\)</span> 的公式。我们现在使用这些公式根据迭代投影给出对系数的有用解释。</p>
<p>对案例 <span class="math inline">\(\operatorname{dim}\left(X_{1}\right)=1\)</span> 取等式 (2.42)，使得 <span class="math inline">\(\beta_{1} \in \mathbb{R}\)</span>。</p>
<p><span class="math display">\[
Y=X_{1} \beta_{1}+X_{2}^{\prime} \beta_{2}+e .
\]</span></p>
<p>现在考虑 <span class="math inline">\(X_{1}\)</span> 在 <span class="math inline">\(X_{2}\)</span> 上的投影：</p>
<p><span class="math display">\[
\begin{aligned}
X_{1} &amp;=X_{2}^{\prime} \gamma_{2}+u_{1} \\
\mathbb{E}\left[X_{2} u_{1}\right] &amp;=0 .
\end{aligned}
\]</span></p>
<p>从 (2.22) 和 (2.36)，<span class="math inline">\(\gamma_{2}=\boldsymbol{Q}_{22}^{-1} \boldsymbol{Q}_{21}\)</span> 和 <span class="math inline">\(\mathbb{E}\left[u_{1}^{2}\right]=\boldsymbol{Q}_{11 \cdot 2}=\boldsymbol{Q}_{11}-\boldsymbol{Q}_{12} \boldsymbol{Q}_{22}^{-1} \boldsymbol{Q}_{21}\)</span>。我们也可以计算出</p>
<p><span class="math display">\[
\mathbb{E}\left[u_{1} Y\right]=\mathbb{E}\left[\left(X_{1}-\gamma_{2}^{\prime} X_{2}\right) Y\right]=\mathbb{E}\left[X_{1} Y\right]-\gamma_{2}^{\prime} \mathbb{E}\left[X_{2} Y\right]=\boldsymbol{Q}_{1 Y}-\boldsymbol{Q}_{12} \boldsymbol{Q}_{22}^{-1} \boldsymbol{Q}_{2 Y}=\boldsymbol{Q}_{1 Y \cdot 2} .
\]</span></p>
<p>我们发现</p>
<p><span class="math display">\[
\beta_{1}=\boldsymbol{Q}_{11 \cdot 2}^{-1} \boldsymbol{Q}_{1 Y \cdot 2}=\frac{\mathbb{E}\left[u_{1} Y\right]}{\mathbb{E}\left[u_{1}^{2}\right]}
\]</span></p>
<p>来自 <span class="math inline">\(Y\)</span> 对 <span class="math inline">\(u_{1}\)</span> 的简单回归的系数。</p>
<p>这意味着在多元投影方程 (2.44) 中，系数 <span class="math inline">\(\beta_{1}\)</span> 等于 <span class="math inline">\(Y\)</span> 在 <span class="math inline">\(u_{1}\)</span> 上的回归的投影系数，<span class="math inline">\(X_{1}\)</span> 在其他回归器 <span class="math inline">\(NA\)</span>u_{1}$ 可以被认为是 <span class="math inline">\(X_{1}\)</span> 的组成部分，其他回归量不能线性解释。因此，系数 <span class="math inline">\(\beta_{1}\)</span> 等于 <span class="math inline">\(X_{1}\)</span> 在去除其他变量的影响后对 <span class="math inline">\(Y\)</span> 的线性影响。</p>
<p>变量 <span class="math inline">\(X_{1}\)</span> 的选择没有什么特别之处。该推导对称地应用于线性投影中的所有系数。每个系数等于 <span class="math inline">\(Y\)</span> 对来自该回归量在所有其他回归量上的投影的误差的简单回归。在线性控制所有其他回归变量之后，每个系数等于该变量对 <span class="math inline">\(Y\)</span> 的线性影响。</p>
</section>
<section id="省略变量偏差" class="level2">
<h2 class="anchored" data-anchor-id="省略变量偏差">省略变量偏差</h2>
<p>同样，让回归量按 (2.41) 进行划分。仅考虑 <span class="math inline">\(Y\)</span> 在 <span class="math inline">\(X_{1}\)</span> 上的投影。也许这样做是因为没有观察到变量 <span class="math inline">\(X_{2}\)</span>。这是等式</p>
<p><span class="math display">\[
\begin{aligned}
Y &amp;=X_{1}^{\prime} \gamma_{1}+u \\
\mathbb{E}\left[X_{1} u\right] &amp;=0 .
\end{aligned}
\]</span></p>
<p>请注意，我们将系数写成 <span class="math inline">\(\gamma_{1}\)</span> 而不是 <span class="math inline">\(\beta_{1}\)</span>，误差写成 <span class="math inline">\(u\)</span> 而不是 <span class="math inline">\(e\)</span>。这是因为 (2.45) 与 (2.42) 不同。 Goldberger (1991) 为 (2.42) 引入了长回归和 (2.45) 的短回归以强调区别。</p>
<p>通常为 <span class="math inline">\(\beta_{1} \neq \gamma_{1}\)</span>，特殊情况除外。为了看到这一点，我们计算</p>
<p><span class="math display">\[
\begin{aligned}
\gamma_{1} &amp;=\left(\mathbb{E}\left[X_{1} X_{1}^{\prime}\right]\right)^{-1} \mathbb{E}\left[X_{1} Y\right] \\
&amp;=\left(\mathbb{E}\left[X_{1} X_{1}^{\prime}\right]\right)^{-1} \mathbb{E}\left[X_{1}\left(X_{1}^{\prime} \beta_{1}+X_{2}^{\prime} \beta_{2}+e\right)\right] \\
&amp;=\beta_{1}+\left(\mathbb{E}\left[X_{1} X_{1}^{\prime}\right]\right)^{-1} \mathbb{E}\left[X_{1} X_{2}^{\prime}\right] \beta_{2} \\
&amp;=\beta_{1}+\Gamma_{12} \beta_{2}
\end{aligned}
\]</span></p>
<p>其中 <span class="math inline">\(\Gamma_{12}=\boldsymbol{Q}_{11}^{-1} \boldsymbol{Q}_{12}\)</span> 是 <span class="math inline">\(X_{2}\)</span> 在 <span class="math inline">\(X_{1}\)</span> 上的投影的系数矩阵，我们使用第 <span class="math inline">\(2.22\)</span> 中的符号。</p>
<p>观察 <span class="math inline">\(\gamma_{1}=\beta_{1}+\Gamma_{12} \beta_{2} \neq \beta_{1}\)</span>，除非 <span class="math inline">\(\Gamma_{12}=0\)</span> 或 <span class="math inline">\(\beta_{2}=0\)</span>。因此，短期和长期回归具有不同的系数。它们仅在两种条件之一下是相同的。首先，如果 <span class="math inline">\(X_{2}\)</span> 在 <span class="math inline">\(X_{1}\)</span> 上的投影产生一组零系数（它们不相关），或者其次，如果 (2.42) 中 <span class="math inline">\(X_{2}\)</span> 上的系数为零。 <span class="math inline">\(\gamma_{1}\)</span> 和 <span class="math inline">\(\beta_{1}\)</span> 之间的差异 <span class="math inline">\(\Gamma_{12} \beta_{2}\)</span> 称为遗漏变量偏差。这是遗漏相关相关变量的结果。</p>
<p>为避免遗漏变量偏差，标准建议是在估计模型中包含所有可能相关的变量。通过构造，一般模型将没有这种偏差。不幸的是，在许多情况下，完全遵循此建议是不可行的，因为没有观察到许多所需的变量。在这种情况下，应在实证调查过程中承认和讨论遗漏变量偏差的可能性。</p>
<p>例如，假设 <span class="math inline">\(Y\)</span> 是对数工资，<span class="math inline">\(X_{1}\)</span> 是教育，<span class="math inline">\(X_{2}\)</span> 是智力。假设教育和智力能力呈正相关（能力强的人获得更高水平的教育）似乎是合理的，这意味着 <span class="math inline">\(\Gamma_{12}&gt;0\)</span>。假设以教育为条件，智力较高的人平均会获得较高的工资，这似乎也是合理的，因此 <span class="math inline">\(\beta_{2}&gt;0\)</span>。这意味着 <span class="math inline">\(\Gamma_{12} \beta_{2}&gt;0\)</span> 和 <span class="math inline">\(\gamma_{1}=\beta_{1}+\Gamma_{12} \beta_{2}&gt;\beta_{1}\)</span>。因此，似乎可以合理地预期，在忽略智力的工资对教育的回归中（因为后者没有被测量），教育的系数高于在包括智力的回归中。换句话说，在这种情况下，被遗漏的变量使回归系数向上偏移。例如，有可能 <span class="math inline">\(\beta_{1}=0\)</span> 使得教育对工资没有直接影响，但 <span class="math inline">\(\gamma_{1}=\Gamma_{12} \beta_{2}&gt;0\)</span> 意味着仅教育的回归系数是正的，但它是教育和智力之间未建模相关性的结果。</p>
<p>不幸的是，正如 Luca、Magnus 和 Peracchi (2018) 所发现的，上述对遗漏变量偏差的简单表征并没有立即延续到更复杂的设置。例如，假设我们比较三个嵌套投影</p>
<p><span class="math display">\[
\begin{aligned}
&amp;Y=X_{1}^{\prime} \gamma_{1}+u_{1} \\
&amp;Y=X_{1}^{\prime} \delta_{1}+X_{2}^{\prime} \delta_{2}+u_{2} \\
&amp;Y=X_{1}^{\prime} \beta_{1}+X_{2}^{\prime} \beta_{2}+X_{3}^{\prime} \beta_{3}+e .
\end{aligned}
\]</span></p>
<p>我们可以称它们为短期、中期和长期回归。假设在长回归中感兴趣的参数是 <span class="math inline">\(\beta_{1}\)</span>。我们对在估计中回归时省略 <span class="math inline">\(X_{3}\)</span> 以及在估计短回归时同时省略 <span class="math inline">\(X_{2}\)</span> 和 <span class="math inline">\(X_{3}\)</span> 的后果感兴趣。特别是我们对这个问题感兴趣：估计短期回归还是中期回归更好，因为两者都省略了 <span class="math inline">\(X_{3}\)</span> ？直觉表明，中等回归应该“偏差较小”，但值得更详细地研究。通过与上述类似的计算，我们发现</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\gamma_{1}=\beta_{1}+\Gamma_{12} \beta_{2}+\Gamma_{13} \beta_{3} \\
&amp;\delta_{1}=\beta_{1}+\Gamma_{13 \cdot 2} \beta_{3}
\end{aligned}
\]</span></p>
<p>其中 <span class="math inline">\(\Gamma_{13 \cdot 2}=\boldsymbol{Q}_{11 \cdot 2}^{-1} \boldsymbol{Q}_{13 \cdot 2}\)</span> 使用 <span class="math inline">\(2.22\)</span> 节中的符号。</p>
<p>我们看到，短回归系数的偏差是 <span class="math inline">\(\Gamma_{12} \beta_{2}+\Gamma_{13} \beta_{3}\)</span>，它同时依赖于 <span class="math inline">\(\beta_{2}\)</span> 和 <span class="math inline">\(\beta_{3}\)</span>，而中等回归系数的偏差是 <span class="math inline">\(\Gamma_{13 \cdot 2} \beta_{3}\)</span>，它只依赖于 <span class="math inline">\(\beta_{3}\)</span>。因此，中回归的偏差不那么复杂，直观上似乎比短回归的偏差更小。但是，不可能对两者进行严格的排名。 <span class="math inline">\(\gamma_{1}\)</span> 的偏差很可能比 <span class="math inline">\(\delta_{1}\)</span> 小。因此，作为一般规则，中回归的估计是否会比短回归的估计更小偏差是未知的。</p>
</section>
<section id="最佳线性逼近" class="level2">
<h2 class="anchored" data-anchor-id="最佳线性逼近">最佳线性逼近</h2>
<p>有其他方法可以构建条件期望 <span class="math inline">\(m(X)\)</span> 的线性逼近 <span class="math inline">\(X^{\prime} \beta\)</span>。在本节中，我们展示了一种替代方法可以产生与最佳线性预测器相同的答案。</p>
<p>我们首先将 <span class="math inline">\(X^{\prime} \beta\)</span> 到 <span class="math inline">\(m(X)\)</span> 的均方逼近误差定义为 <span class="math inline">\(X^{\prime} \beta\)</span> 和条件期望 <span class="math inline">\(m(X)\)</span> 之间的期望平方差</p>
<p><span class="math display">\[
d(\beta)=\mathbb{E}\left[\left(m(X)-X^{\prime} \beta\right)^{2}\right] .
\]</span></p>
<p>函数 <span class="math inline">\(d(\beta)\)</span> 是对 <span class="math inline">\(X^{\prime} \beta\)</span> 与 <span class="math inline">\(m(X)\)</span> 偏差的度量。如果两个函数相同，则为 <span class="math inline">\(d(\beta)=0\)</span>，否则为 <span class="math inline">\(d(\beta)&gt;0\)</span>。我们还可以将均方差 <span class="math inline">\(d(\beta)\)</span> 视为函数 <span class="math inline">\(\left(m(X)-X^{\prime} \beta\right)^{2}\)</span> 的密度加权平均值，因为</p>
<p><span class="math display">\[
d(\beta)=\int_{\mathbb{R}^{k}}\left(m(x)-x^{\prime} \beta\right)^{2} f_{X}(x) d x
\]</span></p>
<p>其中 <span class="math inline">\(f_{X}(x)\)</span> 是 <span class="math inline">\(X\)</span> 的边际密度。</p>
<p>然后，我们可以将条件 <span class="math inline">\(m(X)\)</span> 的最佳线性近似定义为通过选择 <span class="math inline">\(\beta\)</span> 以最小化 <span class="math inline">\(d(\beta)\)</span> 获得的函数 <span class="math inline">\(X^{\prime} \beta\)</span>：</p>
<p><span class="math display">\[
\beta=\underset{b \in \mathbb{R}^{k}}{\operatorname{argmin}} d(b) .
\]</span></p>
<p>与最佳线性预测器类似，我们通过预期平方误差来测量准确性。不同之处在于最佳线性预测器 (2.18) 选择 <span class="math inline">\(\beta\)</span> 以最小化预期平方预测误差，而最佳线性近似 (2.46) 选择 <span class="math inline">\(\beta\)</span> 以最小化预期平方逼近误差。</p>
<p>尽管定义不同，但事实证明最佳线性预测器和最佳线性近似值是相同的。通过与（2.18）中相同的步骤加上条件期望的应用，我们可以发现</p>
<p><span class="math display">\[
\begin{aligned}
\beta &amp;=\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X m(X)] \\
&amp;=\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X Y]
\end{aligned}
\]</span></p>
<p>（见习题 2.19）。因此 (2.46) 等于 (2.18)。我们得出结论，定义（2.46）可以被视为线性投影系数的替代动机。</p>
</section>
<section id="回归均值" class="level2">
<h2 class="anchored" data-anchor-id="回归均值">回归均值</h2>
<p>回归一词起源于弗朗西斯·高尔顿（Francis Galton）（1886 年）的一篇有影响力的论文，他在该论文中研究了父母和孩子的身高（身高）的联合分布。实际上，他是在根据父母的身高估计孩子身高的条件期望。高尔顿发现这个条件期望与 <span class="math inline">\(2 / 3\)</span> 的斜率近似线性。这意味着平均而言，孩子的身高比他或她父母的身高更平庸（平均）。高尔顿将这种现象称为均值回归，而标签回归至今仍用于描述大多数条件关系。</p>
<p>高尔顿的基本见解之一是认识到如果 <span class="math inline">\(Y\)</span> 和 <span class="math inline">\(X\)</span> 的边际分布相同（例如，在稳定环境中孩子和父母的身高），那么线性投影中的回归斜率总是小于 1 .</p>
<p>更准确地说，采用简单的线性投影</p>
<p><span class="math display">\[
Y=X \beta+\alpha+e
\]</span></p>
<p>其中 <span class="math inline">\(Y\)</span> 等于孩子的身高，<span class="math inline">\(X\)</span> 等于父母的身高。假设 <span class="math inline">\(Y\)</span> 和 <span class="math inline">\(X\)</span> 具有相同的期望，因此 <span class="math inline">\(\mu_{Y}=\mu_{X}=\mu\)</span>。然后从 (2.39) <span class="math inline">\(\alpha=(1-\beta) \mu\)</span> 所以我们可以将线性投影 (2.49) 写为</p>
<p><span class="math display">\[
\mathscr{P}(Y \mid X)=(1-\beta) \mu+X \beta .
\]</span></p>
<p>这表明孩子的预计身高是人口期望 <span class="math inline">\(\mu\)</span> 和父母身高 <span class="math inline">\(X\)</span> 的加权平均值，权重为 <span class="math inline">\(\beta\)</span> 和 <span class="math inline">\(1-\beta\)</span>。当高度分布在各代之间是稳定的使得 <span class="math inline">\(\operatorname{var}[Y]=\operatorname{var}[X]\)</span>，那么这个斜率就是 <span class="math inline">\(Y\)</span> 和 <span class="math inline">\(X\)</span> 的简单相关。使用 (2.40)</p>
<p><span class="math display">\[
\beta=\frac{\operatorname{cov}(X, Y)}{\operatorname{var}[X]}=\operatorname{corr}(X, Y) .
\]</span></p>
<p>根据 Cauchy-Schwarz 不等式 (B.32)，<span class="math inline">\(-1 \leq \operatorname{corr}(X, Y) \leq 1\)</span>，<span class="math inline">\(\operatorname{corr}(X, Y)=1\)</span> 仅在退化情况 <span class="math inline">\(Y=X\)</span> 中。因此，如果我们排除退化，<span class="math inline">\(\beta\)</span> 严格小于 1。</p>
<p>这意味着平均而言，孩子的身高比父母的身高更平庸（接近人口平均水平）。</p>
<p>一个常见的错误 - 称为回归谬误 - 是从 <span class="math inline">\(\beta&lt;1\)</span> 推断总体正在收敛，这意味着其方差正在向零下降。这是一个谬误，因为我们在均值和方差不变的假设下推导出了蕴涵 <span class="math inline">\(\beta&lt;1\)</span>。所以当然 <span class="math inline">\(\beta&lt;1\)</span> 并不意味着方差 <span class="math inline">\(Y\)</span> 小于 <span class="math inline">\(X\)</span> 的方差。</p>
<p>另一种看待这一点的方法是在方程（2.49）的上下文中检查收敛条件。由于 <span class="math inline">\(X\)</span> 和 <span class="math inline">\(e\)</span> 不相关，因此得出</p>
<p><span class="math display">\[
\operatorname{var}[Y]=\beta^{2} \operatorname{var}[X]+\operatorname{var}[e] .
\]</span></p>
<p>那么 <span class="math inline">\(\operatorname{var}[Y]&lt;\operatorname{var}[X]\)</span> 当且仅当</p>
<p><span class="math display">\[
\beta^{2}&lt;1-\frac{\operatorname{var}[e]}{\operatorname{var}[X]}
\]</span></p>
<p>简单条件 <span class="math inline">\(|\beta|&lt;1\)</span> 并未暗示这一点。</p>
<p>回归谬误出现在相关的经验情况下。假设您按父母的身高将家庭分组，然后绘制随时间变化的每一代的平均身高。如果人口是稳定的，回归属性意味着地块线将收敛 - 孩子的身高将比他们的父母更平均。回归谬误是错误地得出人口正在收敛的结论。从这个例子中学到的一个信息是，这样的图会误导关于收敛的推断。回归谬误是微妙的。聪明的经济学家很容易屈服于它的诱惑。一个著名的例子是 Horace Secrist 于 1933 年出版的《商业中的平庸的胜利》。在这本书中，Secrist 仔细而详尽地记录了在 19201930 年以上的百货公司样本中，他根据 1920-1921 年将商店分组利润，并绘制了这些群体随后 10 年的平均利润，他发现了清晰而有说服力的证据表明趋同于“趋于平庸”。当然，没有发现——回归均值是稳定分布的必要特征。</p>
</section>
<section id="反向回归" class="level2">
<h2 class="anchored" data-anchor-id="反向回归">反向回归</h2>
<p>高尔顿注意到二元分布的另一个有趣特征。 <span class="math inline">\(Y\)</span> 在 <span class="math inline">\(X\)</span> 上的回归没有什么特别之处。我们还可以在 <span class="math inline">\(Y\)</span> 上回归 <span class="math inline">\(X\)</span>。 （在他的遗传例子中，这是给定孩子身高的父母身高的最佳线性预测因子。）这种回归采用以下形式</p>
<p><span class="math display">\[
X=Y \beta^{*}+\alpha^{*}+e^{*} .
\]</span></p>
<p>这有时被称为反向回归。在这个等式中，系数 <span class="math inline">\(\alpha^{*}, \beta^{*}\)</span> 和误差 <span class="math inline">\(e^{*}\)</span> 由线性投影定义。在一个稳定的人群中，我们发现</p>
<p><span class="math display">\[
\begin{gathered}
\beta^{*}=\operatorname{corr}(X, Y)=\beta \\
\alpha^{*}=(1-\beta) \mu=\alpha
\end{gathered}
\]</span></p>
<p>这与 <span class="math inline">\(Y\)</span> 在 <span class="math inline">\(X\)</span> 上的投影完全相同！截距和斜率在正向和反向投影中具有完全相同的值！ [这种平等并不是特别重要；这是假设 <span class="math inline">\(X\)</span> 和 <span class="math inline">\(Y\)</span> 具有相同方差的产物。]</p>
<p>虽然这个代数发现非常简单，但它是违反直觉的。相反，对逆回归形式的一个常见但错误的猜测是取方程 (2.49)，除以 <span class="math inline">\(\beta\)</span> 并重写以找到方程</p>
<p><span class="math display">\[
X=Y \frac{1}{\beta}-\frac{\alpha}{\beta}-\frac{1}{\beta} e
\]</span></p>
<p>表明 <span class="math inline">\(X\)</span> 在 <span class="math inline">\(Y\)</span> 上的投影应该有 <span class="math inline">\(1 / \beta\)</span> 而不是 <span class="math inline">\(\beta\)</span> 的斜率系数，并且截距是 <span class="math inline">\(-\alpha / \beta\)</span> 而不是 <span class="math inline">\(\alpha\)</span>。什么地方出了错？方程（2.51）是完全有效的，因为它是对有效方程（2.49）的简单操作。问题是 (2.51) 既不是 CEF 也不是线性投影。反转投影（或 CEF）不会产生投影（或 CEF）。相反，(2.50) 是有效的投影，而不是 (2.51)。</p>
<p>无论如何，Galton 的发现是，当变量标准化时，两个投影（<span class="math inline">\(X\)</span> 上的 <span class="math inline">\(Y\)</span> 和 <span class="math inline">\(Y\)</span> 上的 <span class="math inline">\(X\)</span>）的斜率等于相关性，并且两个方程都显示出均值回归。它不是因果关系，而是联合分布的自然特征。</p>
</section>
<section id="最佳线性投影的局限性" class="level2">
<h2 class="anchored" data-anchor-id="最佳线性投影的局限性">最佳线性投影的局限性</h2>
<p>让我们比较一下线性投影和线性 CEF 模型。</p>
<p>从定理 2.4.4 我们知道 CEF 错误具有属性 <span class="math inline">\(\mathbb{E}[X e]=0\)</span>。因此线性 CEF 是最好的线性投影。然而，反之则不成立，因为投影误差不一定满足 <span class="math inline">\(\mathbb{E}[e \mid X]=0\)</span>。此外，线性投影可能不是 CEF 的近似值。</p>
<p>为了在一个简单的例子中看到这些点，假设真正的过程是 <span class="math inline">\(Y=X+X^{2}\)</span> 和 <span class="math inline">\(X \sim \mathrm{N}(0,1)\)</span>。在这种情况下，真正的 CEF 是 <span class="math inline">\(m(x)=x+x^{2}\)</span> 并且没有错误。现在考虑 <span class="math inline">\(Y\)</span> 在 <span class="math inline">\(X\)</span> 上的线性投影和一个常数，即模型 <span class="math inline">\(Y=\beta X+\alpha+e\)</span>。由于 <span class="math inline">\(X \sim \mathrm{N}(0,1)\)</span> 那么 <span class="math inline">\(X\)</span> 和 <span class="math inline">\(X^{2}\)</span> 是不相关的，并且线性投影采用 <span class="math inline">\(\mathscr{P}[Y \mid X]=X+1\)</span> 的形式。这与真正的 CEF <span class="math inline">\(m(X)=\)</span> <span class="math inline">\(X+X^{2}\)</span> 完全不同。投影误差等于 <span class="math inline">\(e=X^{2}-1\)</span>，它是 <span class="math inline">\(X\)</span> 的确定性函数，但与 <span class="math inline">\(X\)</span> 不相关。我们在这个例子中看到，投影误差不一定是 CEF 误差，线性投影可能不是 CEF 的近似值。</p>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-36.jpg" class="img-fluid"></p>
<p>图 2.7：条件期望和两个线性预测</p>
<p>线性投影的另一个缺陷是当条件均值非线性时，它对回归量的边际分布很敏感。我们在图 <span class="math inline">\(2.7\)</span> 中说明了 <span class="math inline">\(Y\)</span> 和 <span class="math inline">\(X\)</span> 的构造 <span class="math inline">\({ }^{11}\)</span> 联合分布的问题。粗线是给定 <span class="math inline">\(X\)</span> 的 <span class="math inline">\(Y\)</span> 的非线性 CEF。数据分为两组 - 第 1 组和第 2 组 - 回归量 <span class="math inline">\(X\)</span> 的边际分布不同，第 1 组的 <span class="math inline">\(X\)</span> 平均值低于第 2 组。<span class="math inline">\(Y\)</span> 的单独线性投影这两组的 <span class="math inline">\(X\)</span> 在图中用细线显示。这两个预测是 CEF 的不同近似值。线性投影的一个缺陷是它会导致错误的结论，即 <span class="math inline">\(X\)</span> 对 <span class="math inline">\(Y\)</span> 的影响对于两组中的个人来说是不同的。这个结论是不正确的，因为实际上条件期望函数没有区别。明显的差异是非线性期望的线性近似与条件变量的不同边际分布相结合的副产品。</p>
<p><span class="math inline">\({ }^{11}\)</span> 第 1 组中的 <span class="math inline">\(X\)</span> 是 <span class="math inline">\(\mathrm{N}(2,1)\)</span>，第 2 组中的是 <span class="math inline">\(\mathrm{N}(4,1)\)</span>，<span class="math inline">\(Y\)</span> 给定 <span class="math inline">\(X\)</span> 的条件分布是 <span class="math inline">\(\mathrm{N}(m(X), 1)\)</span>，其中 <span class="math inline">\(m(x)=2 x-x^{2} / 6\)</span>。这些函数绘制在 <span class="math inline">\(0 \leq x \leq 6\)</span> 上。</p>
</section>
<section id="随机系数模型" class="level2">
<h2 class="anchored" data-anchor-id="随机系数模型">随机系数模型</h2>
<p>一个在符号上与线性 CEF 模型相似但在概念上不同的模型是线性随机系数模型。它采用 <span class="math inline">\(Y=X^{\prime} \eta\)</span> 的形式，其中个体特定系数 <span class="math inline">\(\eta\)</span> 是随机的并且独立于 <span class="math inline">\(X\)</span>。例如，如果 <span class="math inline">\(X\)</span> 是受教育年限，<span class="math inline">\(Y\)</span> 是对数工资，则 <span class="math inline">\(\eta\)</span> 是个人特定的受教育回报。如果一个人获得额外一年的教育，<span class="math inline">\(\eta\)</span> 是他们工资的实际变化。随机系数模型允许受教育的回报因人口而异。有些人的教育回报率可能很高（高 <span class="math inline">\(\eta\)</span> ），而另一些人的回报率低，可能是 0 ，甚至是负数。</p>
<p>在线性 CEF 模型中，回归系数等于回归导数 - 由于回归变量 <span class="math inline">\(\beta=\nabla m(X)\)</span> 的变化而导致的条件期望的变化。这不是对特定个体的影响，而是对总体平均数的影响。相反，在随机系数模型中，随机向量 <span class="math inline">\(\eta=\nabla\left(X^{\prime} \eta\right)\)</span> 是真正的因果效应——响应变量 <span class="math inline">\(Y\)</span> 本身由于回归量的变化而发生的变化。</p>
<p>然而，有趣的是发现线性随机系数模型意味着线性 CEF。要看到这一点，让 <span class="math inline">\(\beta=\mathbb{E}[\eta]\)</span> 和 <span class="math inline">\(\Sigma=\operatorname{var}[\eta]\)</span> 表示 <span class="math inline">\(\eta\)</span> 的均值和协方差矩阵，然后将随机系数分解为 <span class="math inline">\(\eta=\beta+u\)</span>，其中 <span class="math inline">\(u\)</span> 独立于 <span class="math inline">\(X\)</span> 分布，均值为零，协方差矩阵 <span class="math inline">\(数学7\)</span>。然后我们可以写</p>
<p><span class="math display">\[
\mathbb{E}[Y \mid X]=X^{\prime} \mathbb{E}[\eta \mid X]=X^{\prime} \mathbb{E}[\eta]=X^{\prime} \beta
\]</span></p>
<p>所以 CEF 在 <span class="math inline">\(X\)</span> 中是线性的，系数 <span class="math inline">\(\beta\)</span> 等于随机系数 <span class="math inline">\(\eta\)</span> 的期望值。</p>
<p>因此，我们可以将方程写为线性 CEF <span class="math inline">\(Y=X^{\prime} \beta+e\)</span>，其中 <span class="math inline">\(e=X^{\prime} u\)</span> 和 <span class="math inline">\(u=\eta-\beta\)</span>。错误在条件下为零：<span class="math inline">\(\mathbb{E}[e \mid X]=0\)</span>。此外</p>
<p><span class="math display">\[
\operatorname{var}[e \mid X]=X^{\prime} \operatorname{var}[\eta] X=X^{\prime} \Sigma X
\]</span></p>
<p>所以误差是条件异方差的，其方差是 <span class="math inline">\(X\)</span> 的二次函数。</p>
<p>定理 2.11 在线性随机系数模型 <span class="math inline">\(Y=X^{\prime} \eta\)</span> 中，<span class="math inline">\(\eta\)</span> 独立于 <span class="math inline">\(X, \mathbb{E}\|X\|^{2}&lt;\infty\)</span> 和 <span class="math inline">\(\mathbb{E}\|\eta\|^{2}&lt;\infty\)</span>，则</p>
<p><span class="math display">\[
\begin{aligned}
\mathbb{E}[Y \mid X] &amp;=X^{\prime} \beta \\
\operatorname{var}[Y \mid X] &amp;=X^{\prime} \Sigma X
\end{aligned}
\]</span></p>
<p>其中 <span class="math inline">\(\beta=\mathbb{E}[\eta]\)</span> 和 <span class="math inline">\(\Sigma=\operatorname{var}[\eta]\)</span></p>
</section>
<section id="因果效应" class="level2">
<h2 class="anchored" data-anchor-id="因果效应">因果效应</h2>
<p>到目前为止，我们已经避免了因果关系的概念，但计量经济分析的基本目标通常是衡量变量之间的因果关系。了解决策、行动和政策的原因和影响通常具有极大的兴趣。例如，我们可能对班级规模对考试成绩的影响、警察支出对犯罪率的影响、气候变化对经济活动的影响、受教育年限对工资的影响、制度结构对增长的影响、奖励对行为的有效性、健康结果的医疗程序，或任何各种可能的因果关系。在每种情况下，目标都是了解输入变化对结果的实际影响是什么。我们不仅对条件期望或线性投影感兴趣，我们还想知道实际的变化。</p>
<p>两个固有的障碍是：（1）因果效应通常是特定于个人的； (2) 因果效应通常是无法观察到的。</p>
<p>考虑学校教育对工资的影响。因果效应是如果我们可以在其他所有条件不变的情况下改变他们的教育水平，一个人将获得的实际工资差异。这是针对每个人的，因为他们在这两种不同情况下的就业结果是个人的。因果效应是未观察到的，因为我们能观察到的最多的是他们的实际教育水平和实际工资，但如果他们的教育不同，则不是反事实工资。</p>
<p>具体假设有两个人，詹妮弗和乔治，他们都有可能成为高中毕业生或大学毕业生，并且根据他们的选择，他们都会得到不同的工资。例如，假设 Jennifer 大学毕业生每小时可赚取 <span class="math inline">\(\$ 10\)</span> an hour as a high-school graduate and <span class="math inline">\(\$ 20\)</span>，而 George 作为大学毕业生每小时可赚取 <span class="math inline">\(\$ 8\)</span> as a high-school graduate and <span class="math inline">\(\$ 12\)</span>。在这个例子中，对于乔治来说，学校教育的因果效应是每小时 <span class="math inline">\(\$ 10\)</span> a hour for Jennifer and <span class="math inline">\(\$ 4\)</span>。因果效应是特定于个体的，没有观察到因果效应。</p>
<p>Rubin (1974) 开发了潜在结果框架（也称为 Rubin 因果模型）来阐明这些问题。令 <span class="math inline">\(Y\)</span> 为标量结果（例如，工资），<span class="math inline">\(D\)</span> 为二元处理（例如，大学入学率）。作为二进制处理的规范不是必需的，但简化了符号。描述治疗对结果影响的灵活模型是</p>
<p><span class="math display">\[
Y=h(D, U)
\]</span></p>
<p>其中 <span class="math inline">\(U\)</span> 是 <span class="math inline">\(\ell \times 1\)</span> 未观察到的随机因子，<span class="math inline">\(h\)</span> 是函数关系。分别使用简化符号 <span class="math inline">\(Y(0)=h(0, U)\)</span> 和 <span class="math inline">\(Y(1)=h(1, U)\)</span> 来表示与非治疗和治疗相关的潜在结果也很常见。该符号隐含地保持 <span class="math inline">\(U\)</span> 固定。潜在结果因每个人而异，因为它们取决于 <span class="math inline">\(U\)</span>。例如，如果 <span class="math inline">\(Y\)</span> 是个人的工资，则不可观察的 <span class="math inline">\(U\)</span> 可能包括个人的能力、技能、职业道德、人际关系和偏好等特征，所有这些都可能影响他们的工资。在我们的示例中，这些因素通过标签“Jennifer”和“George”进行了总结。</p>
<p>当我们改变 <span class="math inline">\(D\)</span> 而保持 <span class="math inline">\(U\)</span> 不变时，鲁宾将这种影响描述为因果关系。在我们的示例中，这意味着在保持其他属性不变的同时改变个人的教育。</p>
<p>定义 2.6 在模型 (2.52) 中，<span class="math inline">\(D\)</span> 对 <span class="math inline">\(Y\)</span> 的因果效应是</p>
<p><span class="math display">\[
C(U)=Y(1)-Y(0)=h(1, U)-h(0, U),
\]</span></p>
<p>在保持 <span class="math inline">\(U\)</span> 不变的情况下，由于治疗引起的 <span class="math inline">\(Y\)</span> 的变化。</p>
<p>理解 (2.53) 是一个定义，并不一定描述基本或实验意义上的因果关系，这可能会有所帮助。也许将（2.53）标记为结构效应（结构模型内的效应）会更合适。</p>
<p>(2.53) 中定义的治疗 <span class="math inline">\(C(U)\)</span> 的因果效应是异质和随机的，因为潜在结果 <span class="math inline">\(Y(0)\)</span> 和 <span class="math inline">\(Y(1)\)</span> 因个体而异。此外，对于给定的个人，我们不会同时观察 <span class="math inline">\(Y(0)\)</span> 和 <span class="math inline">\(Y(1)\)</span>，而只观察到已实现的价值</p>
<p><span class="math display">\[
Y=\left\{\begin{array}{lll}
Y(0) &amp; \text { if } &amp; D=0 \\
Y(1) &amp; \text { if } &amp; D=1 .
\end{array}\right.
\]</span></p>
<p>表 2.3：示例分布</p>
<p>|College Graduate|0|0|6|10|<span class="math inline">\(\$ 17.00\)</span>| |:—————|:|:|:|-:|———:| |Difference | | | | | <span class="math inline">\(\$ 8.25\)</span>|</p>
<p>因此，没有观察到因果效应 <span class="math inline">\(C(U)\)</span>。</p>
<p>Rubin 的目标是学习 <span class="math inline">\(C(U)\)</span> 的分布特征，包括其预期值，他称之为平均因果效应。他定义如下。</p>
<p>定义 2.7 在模型 (2.52) 中，<span class="math inline">\(D\)</span> 对 <span class="math inline">\(Y\)</span> 的平均因果效应为</p>
<p><span class="math display">\[
\mathrm{ACE}=\mathbb{E}[C(U)]=\int_{\mathbb{R}^{\ell}} C(u) f(u) d u
\]</span></p>
<p>其中 <span class="math inline">\(f(u)\)</span> 是 <span class="math inline">\(U\)</span> 的密度。</p>
<p>ACE 是因果效应的总体平均值。扩展我们的 Jennifer&amp;George 示例，假设一半的人口像 Jennifer，而另一半像 George。那么大学对工资的平均因果效应是 <span class="math inline">\((10+4) / 2=\$ 7\)</span> an hour.</p>
<p>估计 ACE 的一个合理起点是比较治疗和未治疗个体的平均 <span class="math inline">\(Y\)</span>。在我们的示例中，这是大学毕业生和高中毕业生的平均工资之间的差异。这与结果 <span class="math inline">\(Y\)</span> 对治疗 <span class="math inline">\(D\)</span> 的回归系数相同。这等于 ACE 吗？</p>
<p>答案取决于处理 <span class="math inline">\(D\)</span> 和未观察到的分量 <span class="math inline">\(U\)</span> 之间的关系。如果 <span class="math inline">\(D\)</span> 在实验中是随机分配的，那么 <span class="math inline">\(D\)</span> 和 <span class="math inline">\(U\)</span> 是独立的并且回归系数等于 ACE。但是，如果 <span class="math inline">\(D\)</span> 和 <span class="math inline">\(U\)</span> 是相关的，那么回归系数和 ACE 是不同的。为了看到这一点，观察治疗和未治疗人群的平均结果之间的差异是</p>
<p><span class="math display">\[
\mathbb{E}[Y \mid D=1]-\mathbb{E}[Y \mid D=0]=\int_{\mathbb{R}^{\ell}} h(1, u) f(u \mid D=1) d u-\int_{\mathbb{R}^{\ell}} h(1, u) f(u \mid D=0) d u
\]</span></p>
<p>其中 <span class="math inline">\(f(u \mid D)\)</span> 是给定 <span class="math inline">\(D\)</span> 的 <span class="math inline">\(U\)</span> 的条件密度。如果 <span class="math inline">\(U\)</span> 独立于 <span class="math inline">\(D\)</span> 则 <span class="math inline">\(f(u \mid D)=f(u)\)</span> 和上面的表达式等于 <span class="math inline">\(\int_{\mathbb{R}^{\ell}}(h(1, u)-h(0, u)) f(u) d u=\)</span> ACE。但是，如果 <span class="math inline">\(U\)</span> 和 <span class="math inline">\(D\)</span> 是相关的，则此等式将失败。</p>
<p>为了说明，让我们回到詹妮弗和乔治的例子。假设所有高中生都参加了能力倾向测试。如果学生获得高 <span class="math inline">\((\mathrm{H})\)</span> 分数，他们以 <span class="math inline">\(3 / 4\)</span> 的概率上大学，如果学生获得低 (L) 分，他们以 <span class="math inline">\(1 / 4\)</span> 的概率上大学。进一步假设 Jennifer 以 3/4 的概率获得 <span class="math inline">\(\mathrm{H}\)</span> 的能力得分，而 George 以 <span class="math inline">\(1 / 4\)</span> 的概率获得 <span class="math inline">\(\mathrm{H}\)</span> 的得分。在这种情况下，Jennifer 的 <span class="math inline">\(62.5 %\)</span> 将上大学 <span class="math inline">\({ }^{12}\)</span>，而 George 的 <span class="math inline">\(37.5 %\)</span> 将上大学 <span class="math inline">\({ }^{13}\)</span>。</p>
<p>一位计量经济学家随机抽样 32 个人并收集有关教育程度和工资的数据，会发现表 2.3 中显示的工资分布。</p>
<p><span class="math inline">\(12 \mathbb{P}[\)</span> 大学 <span class="math inline">\(\mid\)</span> 詹妮弗 <span class="math inline">\(]=\mathbb{P}[\)</span> 大学 <span class="math inline">\(\mid H] \mathbb{P}[H \mid\)</span> 詹妮弗 <span class="math inline">\(]+\mathbb{P}[\)</span> 大学 <span class="math inline">\(\mid L] \mathbb{P}[L \mid\)</span> 詹妮弗 <span class="math inline">\(]=(3 / 4)^{2}+(1 / 4)^{2} .\)</span></p>
<p><span class="math inline">\(13 \mathbb{P}[\)</span> 大学 <span class="math inline">\(\mid\)</span> 乔治 <span class="math inline">\(]=\mathbb{P}[\)</span> 大学 <span class="math inline">\(\mid H] \mathbb{P}[H \mid\)</span> 乔治 <span class="math inline">\(]+\mathbb{P}[\)</span> 大学 <span class="math inline">\(\mid L] \mathbb{P}[L \mid\)</span> 乔治 <span class="math inline">\(]=(3 / 4)(1 / 4)+(1 / 4)(3 / 4)\)</span>.我们的计量经济学家发现高中毕业生的平均工资是 <span class="math inline">\(\$ 8.75\)</span> while the average wage among college graduates is <span class="math inline">\(\$ 17.00\)</span>。 <span class="math inline">\(\$ 8.25\)</span> is the econometrician’s regression coefficient for the effect of college on wages. But <span class="math inline">\(\$ 8.25\)</span> 的差异夸大了 <span class="math inline">\(\$ 7\)</span>NA</p>
<p>要可视化表 <span class="math inline">\(2.3\)</span>，请查看图 2.8。这四个点是表中的四个教育/工资对，点的大小根据工资分布进行了校准。这两条线是计量经济学家的回归线和平均因果效应。人口中的 Jennifer’s 对应于两条线以上的点，人口中的 George’s 对应于两条线以下的点。因为大多数 Jennifer 上过大学，而大多数 George 没有上过大学，所以回归线从平均因果效应向两个大点倾斜。</p>
<p><img src="images//2022_09_17_efa0deee3441d06e0b66g-40.jpg" class="img-fluid"></p>
<p>图 2.8：平均因果效应与回归</p>
<p>我们从这个分析中得到的第一个教训是，我们需要谨慎地将回归系数解释为因果效应。除非回归量（例如教育程度）可以解释为随机分配，否则不适合因果解释回归系数。</p>
<p>我们的第二课是，如果我们以一组足够丰富的协变量为条件，就可以获得因果解释。我们现在探讨这个问题。</p>
<p>假设除了结果 <span class="math inline">\(Y\)</span> 和处理 <span class="math inline">\(D\)</span> 之外，可观察量还包括一组协变量 <span class="math inline">\(X\)</span>。我们扩展潜在结果模型 (2.52) 以包括 <span class="math inline">\(X\)</span> ：</p>
<p><span class="math display">\[
Y=h(D, X, U) .
\]</span></p>
<p>我们还扩展了因果效应的定义，以允许对 <span class="math inline">\(X\)</span> 进行调节。</p>
<p>定义 <span class="math inline">\(2.8\)</span> 在模型 (2.54) 中，<span class="math inline">\(D\)</span> 对 <span class="math inline">\(Y\)</span> 的因果效应是</p>
<p><span class="math display">\[
C(X, U)=h(1, X, U)-h(0, X, U),
\]</span></p>
<p>由于保持 <span class="math inline">\(X\)</span> 和 <span class="math inline">\(U\)</span> 不变的治疗，<span class="math inline">\(Y\)</span> 的变化。</p>
<p>以 <span class="math inline">\(X=x\)</span> 为条件的 <span class="math inline">\(D\)</span> 对 <span class="math inline">\(Y\)</span> 的条件平均因果效应是</p>
<p><span class="math display">\[
\operatorname{ACE}(x)=\mathbb{E}[C(X, U) \mid X=x]=\int_{\mathbb{R}^{\ell}} C(x, u) f(u \mid x) d u
\]</span></p>
<p>其中 <span class="math inline">\(f(u \mid x)\)</span> 是给定 <span class="math inline">\(X\)</span> 的 <span class="math inline">\(U\)</span> 的条件密度。</p>
<p><span class="math inline">\(D\)</span> 对 <span class="math inline">\(Y\)</span> 的无条件平均因果效应为</p>
<p><span class="math display">\[
\mathrm{ACE}=\mathbb{E}[C(X, U)]=\int \operatorname{ACE}(x) f(x) d x
\]</span></p>
<p>其中 <span class="math inline">\(f(x)\)</span> 是 <span class="math inline">\(X\)</span> 的密度。</p>
<p>条件平均因果效应 <span class="math inline">\(\operatorname{ACE}(x)\)</span> 是具有特征 <span class="math inline">\(X=x\)</span> 的子群体的 ACE。给定对 <span class="math inline">\((Y, D, X)\)</span> 的观察，我们想测量 <span class="math inline">\(D\)</span> 对 <span class="math inline">\(Y\)</span> 的因果影响，并且感兴趣是否可以通过 <span class="math inline">\(Y\)</span> 对 <span class="math inline">\((D, X)\)</span> 的回归来获得。我们想将 <span class="math inline">\(D\)</span> 上的系数解释为因果效应。这合适吗？</p>
<p>我们之前的分析表明，当 <span class="math inline">\(U\)</span> 独立于回归变量时，可以获得因果解释。虽然这已经足够了，但它比必要的要强。相反，以下内容就足够了。</p>
<p>定义 2.9 条件独立假设 (CIA)。以 <span class="math inline">\(X\)</span> 为条件，随机变量 <span class="math inline">\(D\)</span> 和 <span class="math inline">\(U\)</span> 在统计上是独立的。</p>
<p>CIA 暗示给定 <span class="math inline">\((D, X)\)</span> 的 <span class="math inline">\(U\)</span> 的条件密度仅取决于 <span class="math inline">\(X\)</span>，因此 <span class="math inline">\(f(u \mid D, X)=\)</span> <span class="math inline">\(f(u \mid X)\)</span>。这意味着 <span class="math inline">\(Y\)</span> 对 <span class="math inline">\((D, X)\)</span> 的回归等于</p>
<p><span class="math display">\[
\begin{aligned}
m(d, x) &amp;=\mathbb{E}[Y \mid D=d, X=x] \\
&amp;=\mathbb{E}[h(d, x, U) \mid D=d, X=x] \\
&amp;=\int h(d, x, u) f(u \mid x) d u .
\end{aligned}
\]</span></p>
<p>在 CIA 下，回归测量的治疗效果是</p>
<p><span class="math display">\[
\begin{aligned}
\nabla m(d, x) &amp;=m(1, x)-m(0, x) \\
&amp;=\int h(1, x, u) f(u \mid x) d u-\int h(0, x, u) f(u \mid x) d u \\
&amp;=\int C(x, u) f(u \mid x) d u \\
&amp;=\operatorname{ACE}(x) .
\end{aligned}
\]</span></p>
<p>这是有条件的 ACE。因此，在 CIA 下，回归系数等于 ACE。</p>
<p>我们推断 <span class="math inline">\(Y\)</span> 对 <span class="math inline">\((D, X)\)</span> 的回归揭示了当 CIA 成立时治疗的因果影响。这意味着，当我们可以证明回归量 <span class="math inline">\(X\)</span> 足以控制与治疗相关的因素时，可以对回归分析进行因果解释。</p>
<p>定理 2.12 在结构模型 (2.54) 中，条件独立假设意味着 <span class="math inline">\(\nabla m(d, x)=\operatorname{ACE}(x)\)</span>，即关于治疗的回归导数等于条件 ACE。</p>
<p>这是一个令人着迷的结果。它表明，只要在以适当的回归量为条件后，不可观察变量独立于处理变量，回归导数就等于条件因果效应。这意味着 CEF 具有因果经济意义，为 CEF 的估计提供了强有力的理由。</p>
<p>了解中央情报局的关键作用很重要。如果 CIA 失败，则回归导数和 ACE 的等式 (2.55) 失败。 CIA 声明以 <span class="math inline">\(X\)</span> 为条件，变量 <span class="math inline">\(U\)</span> 和 <span class="math inline">\(D\)</span> 是独立的。这意味着处理 <span class="math inline">\(D\)</span> 不受未观察到的个体因素 <span class="math inline">\(U\)</span> 的影响，并且实际上是随机的。这是一个强有力的假设。在工资/教育示例中，这意味着个人不会根据他们未观察到的特征来选择教育。</p>
<p>然而，了解 CIA 弱于 <span class="math inline">\(U\)</span> 与回归量 <span class="math inline">\((D, X)\)</span> 的完全独立性也有帮助。只需要 <span class="math inline">\(U\)</span> 和 <span class="math inline">\(D\)</span> 在以 <span class="math inline">\(X\)</span> 为条件后是独立的。如果 <span class="math inline">\(X\)</span> 足够丰富，这可能不是限制性的。</p>
<p>回到我们的例子，我们需要一个变量 <span class="math inline">\(X\)</span>，它打破了 <span class="math inline">\(D\)</span> 和 <span class="math inline">\(U\)</span> 之间的依赖关系。在我们的示例中，此变量是能力倾向测试分数，因为上大学的决定是基于测试分数。因此，一旦我们以考试成绩为条件，教育程度和类型是独立的。</p>
<p>要看到这一点，请观察如果学生的考试成绩是 <span class="math inline">\(\mathrm{H}\)</span>，那么对于 Jennifers 和 Georges，他们上大学 <span class="math inline">\((D=1)\)</span> 的概率是 <span class="math inline">\(3 / 4\)</span>。同样，如果他们的考试成绩是 <span class="math inline">\(\mathrm{L}\)</span>，那么他们上大学的概率对于这两种类型都是 <span class="math inline">\(1 / 4\)</span>。这意味着大学入学率与类型无关，取决于能力倾向测试分数。</p>
<p>有条件的 ACE 取决于考试成绩。在获得高分的学生中，<span class="math inline">\(3 / 4\)</span> 是 Jennifers，<span class="math inline">\(1 / 4\)</span> 是 Georges。因此，分数为 <span class="math inline">\(\mathrm{H}\)</span> 的学生的条件 ACE 是 <span class="math inline">\((3 / 4) \times 10+\)</span> <span class="math inline">\((1 / 4) \times 4=\$ 8.50\)</span>. Among students who receive a low test score, <span class="math inline">\(1 / 4\)</span> are Jennifers and <span class="math inline">\(3 / 4\)</span> are Georges. Thus the ACE for students with a score of <span class="math inline">\(\mathrm{L}\)</span> is <span class="math inline">\((1 / 4) \times 10 +(3 / 4) \times 4=\$ 5.50\)</span>。无条件 ACE 是平均值，<span class="math inline">\(\mathrm{ACE}=(8.50+5.50) / 2=\$ 7\)</span>, because <span class="math inline">\(50 %\)</span> of students each receive scores of <span class="math inline">\(\mathrm{H}\)</span> and <span class="math inline">\(\mathrm{L}\)</span>.</p>
<p>定理 <span class="math inline">\(2.12\)</span> 表明条件 ACE 由包含测试分数的回归揭示。要在工资分布中看到这一点，假设计量经济学家收集有关能力倾向测试分数以及教育和工资的数据。给定 32 个人的随机样本，我们期望在表 <span class="math inline">\(2.4\)</span> 中找到工资分布。</p>
<p>定义一个虚拟高分来表示获得高分的学生。工资对大学出勤率和考试成绩及其交互作用的回归是</p>
<p><span class="math display">\[
\mathbb{E}[\text { wage } \mid \text { college, highscore }]=1.00 \text { highscore }+5.50 \text { college }+3.00 \text { highscore } \times \text { college }+8.50 \text {. }
\]</span></p>
<p>大学的系数，<span class="math inline">\(\$ 5.50\)</span>, is the regression derivative of college attendance for those with low test scores, and the sum of this coefficient with the interaction coefficient <span class="math inline">\(\$ 3.00\)</span> 等于 <span class="math inline">\(\$ 8.50\)</span> which is the Table 2.4: Example Distribution 2</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\$ 8\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\$ 10\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\$ 12\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\$ 20\)</span></th>
<th style="text-align: right;">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">High-School Graduate + High Test Score</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;"><span class="math inline">\(\$ 9.50\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">College Graduate + High Test Score</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;"><span class="math inline">\(\$ 18.00\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">High-School Graduate + Low Test Score</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;"><span class="math inline">\(\$ 8.50\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">College Graduate + Low Test Score</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"><span class="math inline">\(\$ 14.00\)</span></td>
</tr>
</tbody>
</table>
<p>高分学生的大学出勤率的回归导数。 <span class="math inline">\(\$ 5.50\)</span> and <span class="math inline">\(\$ 8.50\)</span> 等于上面计算的条件因果效应。</p>
<p>这表明，从回归 (2.56) 中，计量经济学家会发现大学对工资的影响是 <span class="math inline">\(\$ 8.50\)</span> for those with high test scores and <span class="math inline">\(\$ 5.50\)</span> 对于那些测试成绩低的人，平均影响为 <span class="math inline">\(\$ 7\)</span> (because <span class="math inline">\(50 %\)</span> of students receive high and low test scores). This is the true average causal effect of college on wages. Thus the regression coefficient on college in (2.56) can be interpreted causally, while a regression omitting the aptitude test score does not reveal the causal effect of education.</p>
<p>为了总结我们的发现，我们已经展示了一个简单的回归如何可能对因果效应进行错误的测量，但更仔细的回归可以揭示真正的因果效应。关键是要以一组适当丰富的协变量为条件，以使影响结果的其余未观察到的因素与治疗变量无关。</p>
</section>
<section id="条件期望的存在性和唯一性" class="level2">
<h2 class="anchored" data-anchor-id="条件期望的存在性和唯一性">条件期望的存在性和唯一性*</h2>
<p>在 <span class="math inline">\(2.3\)</span> 和 <span class="math inline">\(2.6\)</span> 部分中，我们定义了条件变量 <span class="math inline">\(X\)</span> 是离散的并且变量 <span class="math inline">\((Y, X)\)</span> 具有联合密度时的条件期望。我们已经探索了这些情况，因为这些情况是条件均值最容易描述和理解的情况。然而，条件均值的存在相当普遍，不涉及离散或连续随机变量的性质。</p>
<p>为了证明这一说法的合理性，我们现在提出了概率论的一个深刻结果。它所说的是条件均值存在于所有联合分布 <span class="math inline">\((Y, X)\)</span> 中，其中 <span class="math inline">\(Y\)</span> 具有有限均值。</p>
<p>定理 2.13 条件期望的存在 如果 <span class="math inline">\(\mathbb{E}|Y|&lt;\infty\)</span> 则存在一个函数 <span class="math inline">\(m(x)\)</span> 使得对于定义了 <span class="math inline">\(\mathbb{P}[X \in \mathscr{X}]\)</span> 的所有集合 <span class="math inline">\(\mathscr{X}\)</span>，</p>
<p><span class="math display">\[
\mathbb{E}[\mathbb{1}\{X \in \mathscr{X}\} Y]=\mathbb{E}[\mathbb{1}\{X \in \mathscr{X}\} m(X)]
\]</span></p>
<p>函数 <span class="math inline">\(m(X)\)</span> 几乎在任何地方都是唯一的，即如果 <span class="math inline">\(h(x)\)</span> 满足 (2.57)，则存在一个集合 <span class="math inline">\(S\)</span>，使得 <span class="math inline">\(\mathbb{P}[S]=1\)</span> 和 <span class="math inline">\(m(x)=h(x)\)</span> 对应于 <span class="math inline">\(x \in S\)</span>。函数 <span class="math inline">\(m(x)\)</span> 称为条件期望，写成 <span class="math inline">\(m(x)=\mathbb{E}[Y \mid X=x]\)</span></p>
<p>例如，参见 Ash (1972)，定理 6.3.3。</p>
<p>当 <span class="math inline">\((Y, X)\)</span> 具有联合密度时，由 (2.57) 定义的条件期望 <span class="math inline">\(m(x)\)</span> 专门用于 (2.6)。定义 (2.57) 的用处在于定理 <span class="math inline">\(2.13\)</span> 表明条件期望 <span class="math inline">\(m(X)\)</span> 对于所有有限均值分布都存在。这个定义允许 <span class="math inline">\(Y\)</span> 是离散的或连续的，对于 <span class="math inline">\(X\)</span> 是标量或向量值的，并且对于 <span class="math inline">\(X\)</span> 的组件是离散的或连续分布的。</p>
<p>您可能已经注意到定理 <span class="math inline">\(2.13\)</span> 仅适用于定义了 <span class="math inline">\(\mathbb{P}[X \in \mathscr{X}]\)</span> 的集合 <span class="math inline">\(\mathscr{X}\)</span>。这是一个技术问题——可测量性——我们在这本教科书中很大程度上回避了这个问题。形式概率论仅适用于可测量的集合（为其定义了概率），因为事实证明并非所有集合都满足可测量性。这不是应用程序的实际问题，因此我们将这种区别推迟到正式的理论处理中。</p>
</section>
<section id="鉴别" class="level2">
<h2 class="anchored" data-anchor-id="鉴别">鉴别*</h2>
<p>结构计量经济学建模中的一个关键和重要问题是识别，这意味着参数由观察到的变量的分布唯一确定。在无条件和有条件的期望的上下文中，它相对简单，但为了清楚起见，在这一点上引入和探索这个概念是值得的。</p>
<p>令 <span class="math inline">\(F\)</span> 表示观测数据的分布，例如 <span class="math inline">\((Y, X)\)</span> 对的分布。令 <span class="math inline">\(\mathscr{F}\)</span> 是分布 <span class="math inline">\(F\)</span> 的集合。让 <span class="math inline">\(\theta\)</span> 成为感兴趣的参数（例如，期望 <span class="math inline">\(\mathbb{E}[Y])\)</span>.</p>
<p>定义 2.10 如果对于所有 <span class="math inline">\(F \in \mathscr{F}\)</span>，存在唯一确定的 <span class="math inline">\(\theta\)</span> 值，则在 <span class="math inline">\(\mathscr{F}\)</span> 上标识参数 <span class="math inline">\(\theta \in \mathbb{R}\)</span>。</p>
<p>等效地，如果我们可以将 <span class="math inline">\(\theta\)</span> 写为集合 <span class="math inline">\(\mathscr{F}\)</span> 上的映射 <span class="math inline">\(\theta=g(F)\)</span>，则它被识别。对集合 <span class="math inline">\(\mathscr{F}\)</span> 的限制很重要。大多数参数仅在所有分布空间的严格子集上被识别。</p>
<p>以期望 <span class="math inline">\(\mu=\mathbb{E}[Y]\)</span> 为例。 <span class="math inline">\(\mathbb{E}|Y|&lt;\infty\)</span> 是唯一确定的，因此 <span class="math inline">\(\mu\)</span> 被标识为集合 <span class="math inline">\(\mathscr{F}=\{F: \mathbb{E}|Y|&lt;\infty\}\)</span>。</p>
<p>接下来，考虑条件期望。定理 <span class="math inline">\(2.13\)</span> 证明 <span class="math inline">\(\mathbb{E}|Y|&lt;\infty\)</span> 是识别的充分条件。</p>
<p>定理 2.14 条件期望的识别 如果 <span class="math inline">\(\mathbb{E}|Y|&lt;\infty\)</span>，则条件期望 <span class="math inline">\(m(x)=\mathbb{E}[Y \mid X=x]\)</span> 几乎在任何地方都可以识别。</p>
<p>只要我们排除退化情况，识别似乎是参数的一般属性。这对于观察数据的时刻是正确的，但对于更复杂的模型则不一定。作为一个恰当的例子，考虑审查的背景。令 <span class="math inline">\(Y\)</span> 为分布为 <span class="math inline">\(F\)</span> 的随机变量。我们没有观察 <span class="math inline">\(Y\)</span>，而是观察由审查规则定义的 <span class="math inline">\(Y^{*}\)</span></p>
<p><span class="math display">\[
Y^{*}=\left\{\begin{array}{cc}
Y &amp; \text { if } Y \leq \tau \\
\tau &amp; \text { if } Y&gt;\tau
\end{array}\right.
\]</span></p>
<p>也就是说，<span class="math inline">\(Y^{*}\)</span> 的上限为 <span class="math inline">\(\tau\)</span>。一个常见的例子是收入调查，其中收入回答是“最高编码”，这意味着高于最高代码 <span class="math inline">\(\tau\)</span> 的收入被记录为最高代码。观察到的变量 <span class="math inline">\(Y^{*}\)</span> 有分布</p>
<p><span class="math display">\[
F^{*}(u)=\left\{\begin{array}{cc}
F(u) &amp; \text { for } u \leq \tau \\
1 &amp; \text { for } u \geq \tau .
\end{array}\right.
\]</span></p>
<p>我们对分布 <span class="math inline">\(F\)</span> 的特征感兴趣，而不是审查分布 <span class="math inline">\(F^{*}\)</span>。例如，我们对预期工资 <span class="math inline">\(\mu=\mathbb{E}[Y]\)</span> 感兴趣。困难在于我们不能从 <span class="math inline">\(F^{*}\)</span> 计算 <span class="math inline">\(\mu\)</span>，除非在没有审查 <span class="math inline">\(\mathbb{P}[Y \geq \tau]=0\)</span> 的普通情况下。因此，期望 <span class="math inline">\(\mu\)</span> 不是从审查分布中普遍识别出来的。</p>
<p>识别问题的典型解决方案是假设参数分布。例如，令 <span class="math inline">\(\mathscr{F}\)</span> 为正态分布 <span class="math inline">\(Y \sim \mathrm{N}\left(\mu, \sigma^{2}\right)\)</span> 的集合。可以证明参数 <span class="math inline">\(\left(\mu, \sigma^{2}\right)\)</span> 是为所有 <span class="math inline">\(F \in \mathscr{F}\)</span> 识别的。也就是说，如果我们知道未经审查的分布是正态的，我们可以唯一地确定来自审查分布的参数。这通常称为参数识别，因为识别仅限于参数类分布。在现代计量经济学中，这通常被视为次优解决方案，因为只有通过使用任意且无法验证的参数假设才能实现识别。</p>
<p>一个悲观的结论可能是，如果没有参数假设，就不可能从审查数据中识别出感兴趣的参数。有趣的是，这种悲观情绪是没有根据的。事实证明，我们可以识别 <span class="math inline">\(\alpha \leq \mathbb{P}[Y \leq \tau]\)</span> 的 <span class="math inline">\(F\)</span> 的分位数 <span class="math inline">\(q_{\alpha}\)</span>。例如，如果分布的 <span class="math inline">\(20 %\)</span> 被删失，我们可以识别 <span class="math inline">\(\alpha \in(0,0.8)\)</span> 的所有分位数。这通常称为非参数识别，因为参数的识别不受参数类的限制。</p>
<p>我们从这个小练习中学到的是，在删失数据的背景下，只能通过参数识别矩，而非删失分位数是非参数识别。部分信息是，对识别的研究可以帮助将注意力集中在可以从可用数据分布中学到的东西上。</p>
</section>
<section id="技术证明" class="level2">
<h2 class="anchored" data-anchor-id="技术证明">技术证明*</h2>
<p>定理 2.1 的证明 为方便起见，假设变量具有联合密度 <span class="math inline">\(f(y, x)\)</span>。由于 <span class="math inline">\(\mathbb{E}[Y \mid X]\)</span> 只是随机向量 <span class="math inline">\(X\)</span> 的函数，为了计算它的期望，我们对 <span class="math inline">\(X\)</span> 的密度 <span class="math inline">\(f_{X}(x)\)</span> 进行积分，即</p>
<p><span class="math display">\[
\mathbb{E}[\mathbb{E}[Y \mid X]]=\int_{\mathbb{R}^{k}} \mathbb{E}[Y \mid X] f_{X}(x) d x .
\]</span></p>
<p>代入 (2.6) 并注意到 <span class="math inline">\(f_{Y \mid X}(y \mid x) f_{X}(x)=f(y, x)\)</span>，我们发现上面的表达式等于</p>
<p><span class="math display">\[
\int_{\mathbb{R}^{k}}\left(\int_{\mathbb{R}} y f_{Y \mid X}(y \mid x) d y\right) f_{X}(x) d x=\int_{\mathbb{R}^{k}} \int_{\mathbb{R}} y f(y, x) d y d x=\mathbb{E}[Y]
\]</span></p>
<p><span class="math inline">\(Y\)</span> 的无条件期望。</p>
<p>定理 2.2 的证明 再次假设变量具有联合密度。观察这一点很有用</p>
<p><span class="math display">\[
f\left(y \mid x_{1}, x_{2}\right) f\left(x_{2} \mid x_{1}\right)=\frac{f\left(y, x_{1}, x_{2}\right)}{f\left(x_{1}, x_{2}\right)} \frac{f\left(x_{1}, x_{2}\right)}{f\left(x_{1}\right)}=f\left(y, x_{2} \mid x_{1}\right)
\]</span></p>
<p>给定 <span class="math inline">\(X_{1}\)</span> 的 <span class="math inline">\(\left(Y, X_{2}\right)\)</span> 的密度。在这里，我们滥用了符号并使用单个符号 <span class="math inline">\(f\)</span> 来表示各种无条件和条件密度，以减少符号混乱。</p>
<p>注意</p>
<p><span class="math display">\[
\mathbb{E}\left[Y \mid X_{1}=x_{1}, X_{2}=x_{2}\right]=\int_{\mathbb{R}} y f\left(y \mid x_{1}, x_{2}\right) d y .
\]</span></p>
<p>在给定 <span class="math inline">\(X_{1}\)</span> 的情况下，对 <span class="math inline">\(X_{2}\)</span> 的条件密度积分 (2.59)，并应用 (2.58) 我们发现</p>
<p><span class="math display">\[
\begin{aligned}
\mathbb{E}\left[\mathbb{E}\left[Y \mid X_{1}, X_{2}\right] \mid X_{1}=x_{1}\right] &amp;=\int_{\mathbb{R}^{k_{2}}} \mathbb{E}\left[Y \mid X_{1}=x_{1}, X_{2}=x_{2}\right] f\left(x_{2} \mid x_{1}\right) d x_{2} \\
&amp;=\int_{\mathbb{R}^{k_{2}}}\left(\int_{\mathbb{R}} y f\left(y \mid x_{1}, x_{2}\right) d y\right) f\left(x_{2} \mid x_{1}\right) d x_{2} \\
&amp;=\int_{\mathbb{R}^{k_{2}}} \int_{\mathbb{R}} y f\left(y \mid x_{1}, x_{2}\right) f\left(x_{2} \mid x_{1}\right) d y d x_{2} \\
&amp;=\int_{\mathbb{R}^{k_{2}}} \int_{\mathbb{R}} y f\left(y, x_{2} \mid x_{1}\right) d y d x_{2} \\
&amp;=\mathbb{E}\left[Y \mid X_{1}=x_{1}\right] .
\end{aligned}
\]</span></p>
<p>这意味着如上所述的 <span class="math inline">\(\mathbb{E}\left[\mathbb{E}\left[Y \mid X_{1}, X_{2}\right] \mid X_{1}\right]=\mathbb{E}\left[Y \mid X_{1}\right]\)</span>。</p>
<p>定理 2.3 的证明</p>
<p><span class="math display">\[
\mathbb{E}[g(X) Y \mid X=x]=\int_{\mathbb{R}} g(x) y f_{Y \mid X}(y \mid x) d y=g(x) \int_{\mathbb{R}} y f_{Y \mid X}(y \mid x) d y=g(x) \mathbb{E}[Y \mid X=x]
\]</span></p>
<p>这意味着 <span class="math inline">\(\mathbb{E}[g(X) Y \mid X]=g(X) \mathbb{E}[Y \mid X]\)</span> 是 (2.7)。方程 (2.8) 将迭代期望的简单定律 (定理 2.1) 应用于 (2.7)。</p>
<p>定理 2.4 的证明将 Minkowski 不等式 (B.34) 应用于 <span class="math inline">\(e=Y-m(X)\)</span>，</p>
<p><span class="math display">\[
\left(\mathbb{E}|e|^{r}\right)^{1 / r}=\left(\mathbb{E}|Y-m(X)|^{r}\right)^{1 / r} \leq\left(\mathbb{E}|Y|^{r}\right)^{1 / r}+\left(\mathbb{E}|m(X)|^{r}\right)^{1 / r}&lt;\infty,
\]</span></p>
<p>其中右侧的两部分是有限的，因为假设 <span class="math inline">\(\mathbb{E}|Y|^{r}&lt;\infty\)</span> 和条件期望不等式 <span class="math inline">\(\mathbb{E}|m(X)|^{r}&lt;\)</span> <span class="math inline">\(\infty\)</span> (B.29)。 <span class="math inline">\(\left(\mathbb{E}|e|^{r}\right)^{1 / r}&lt;\infty\)</span> 意味着 <span class="math inline">\(\mathbb{E}|e|^{r}&lt;\infty\)</span> 的事实。</p>
<p>定理 2.6 的证明 <span class="math inline">\(\mathbb{E}\left[Y^{2}\right]&lt;\infty\)</span> 的假设意味着以下所有条件期望都存在。</p>
<p>使用迭代期望定律（定理 2.2）<span class="math inline">\(\mathbb{E}\left[Y \mid X_{1}\right]=\mathbb{E}\left(\mathbb{E}\left[Y \mid X_{1}, X_{2}\right] \mid X_{1}\right)\)</span> 和条件 Jensen 不等式（B.28），</p>
<p><span class="math display">\[
\left(\mathbb{E}\left[Y \mid X_{1}\right]\right)^{2}=\left(\mathbb{E}\left(\mathbb{E}\left[Y \mid X_{1}, X_{2}\right] \mid X_{1}\right)\right)^{2} \leq \mathbb{E}\left[\left(\mathbb{E}\left[Y \mid X_{1}, X_{2}\right]\right)^{2} \mid X_{1}\right] .
\]</span></p>
<p>采取无条件的期望，这意味着</p>
<p><span class="math display">\[
\mathbb{E}\left[\left(\mathbb{E}\left[Y \mid X_{1}\right]\right)^{2}\right] \leq \mathbb{E}\left[\left(\mathbb{E}\left[Y \mid X_{1}, X_{2}\right]\right)^{2}\right] .
\]</span></p>
<p>相似地，</p>
<p><span class="math display">\[
(\mathbb{E}[Y])^{2} \leq \mathbb{E}\left[\left(\mathbb{E}\left[Y \mid X_{1}\right]\right)^{2}\right] \leq \mathbb{E}\left[\left(\mathbb{E}\left[Y \mid X_{1}, X_{2}\right]\right)^{2}\right] .
\]</span></p>
<p>变量 <span class="math inline">\(Y, \mathbb{E}\left[Y \mid X_{1}\right]\)</span> 和 <span class="math inline">\(\mathbb{E}\left[Y \mid X_{1}, X_{2}\right]\)</span> 都具有相同的期望 <span class="math inline">\(\mathbb{E}[Y]\)</span>，因此不等式 (2.60) 意味着方差是单调排列的：</p>
<p><span class="math display">\[
0 \leq \operatorname{var}\left(\mathbb{E}\left[Y \mid X_{1}\right]\right) \leq \operatorname{var}\left(\mathbb{E}\left[Y \mid X_{1}, X_{2}\right]\right) .
\]</span></p>
<p>定义 <span class="math inline">\(e=Y-\mathbb{E}[Y \mid X]\)</span> 和 <span class="math inline">\(u=\mathbb{E}[Y \mid X]-\mu\)</span> 以便我们得到分解 <span class="math inline">\(Y-\mu=e+u\)</span>。注意 <span class="math inline">\(\mathbb{E}[e \mid X]=0\)</span> 和 <span class="math inline">\(u\)</span> 是 <span class="math inline">\(X\)</span> 的函数。因此根据条件定理（定理 2.3），<span class="math inline">\(\mathbb{E}[e u]=0\)</span> 所以 <span class="math inline">\(e\)</span> 和 <span class="math inline">\(u\)</span> 是不相关的。它遵循</p>
<p><span class="math display">\[
\operatorname{var}[Y]=\operatorname{var}[e]+\operatorname{var}[u]=\operatorname{var}[Y-\mathbb{E}[Y \mid X]]+\operatorname{var}[\mathbb{E}[Y \mid X]]
\]</span></p>
<p>应用于方差分解 (2.62) 的条件期望 (2.61) 的方差的单调性意味着差异方差的反向单调性，从而完成了证明。</p>
<p>定理 2.9 的证明 对于第 1 部分，由期望不等式 (B.30)、(A.17) 和假设 2.1，</p>
<p><span class="math display">\[
\left\|\mathbb{E}\left[X X^{\prime}\right]\right\| \leq \mathbb{E}\left\|X X^{\prime}\right\|=\mathbb{E}\|X\|^{2}&lt;\infty .
\]</span></p>
<p>类似地，使用期望不等式 (B.30)、Cauchy-Schwarz 不等式 (B.32) 和假设 2.1，</p>
<p><span class="math display">\[
\|\mathbb{E}[X Y]\| \leq \mathbb{E}\|X Y\| \leq\left(\mathbb{E}\|X\|^{2}\right)^{1 / 2}\left(\mathbb{E}\left[Y^{2}\right]\right)^{1 / 2}&lt;\infty .
\]</span></p>
<p>因此，矩 <span class="math inline">\(\mathbb{E}[X Y]\)</span> 和 <span class="math inline">\(\mathbb{E}\left[X X^{\prime}\right]\)</span> 是有限且明确定义的。</p>
<p>对于第 2 部分，系数 <span class="math inline">\(\beta=\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X Y]\)</span> 定义明确，因为在假设 2.1 下存在 <span class="math inline">\(\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1}\)</span>。</p>
<p>第 3 部分来自定义 <span class="math inline">\(2.5\)</span> 和部分 <span class="math inline">\(2 .\)</span></p>
<p>对于第 4 部分，首先请注意</p>
<p><span class="math display">\[
\begin{aligned}
\mathbb{E}\left[e^{2}\right] &amp;=\mathbb{E}\left[\left(Y-X^{\prime} \beta\right)^{2}\right] \\
&amp;=\mathbb{E}\left[Y^{2}\right]-2 \mathbb{E}\left[Y X^{\prime}\right] \beta+\beta^{\prime} \mathbb{E}\left[X X^{\prime}\right] \beta \\
&amp;=\mathbb{E}\left[Y^{2}\right]-\mathbb{E}\left[Y X^{\prime}\right]\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X Y] \\
&amp; \leq \mathbb{E}\left[Y^{2}\right]&lt;\infty .
\end{aligned}
\]</span></p>
<p>第一个不等式成立，因为 <span class="math inline">\(\mathbb{E}\left[Y X^{\prime}\right]\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X Y]\)</span> 是二次形式，因此必然是非负的。其次，通过期望不等式（B.30）、Cauchy-Schwarz 不等式（B.32）和假设 2.1，</p>
<p><span class="math display">\[
\|\mathbb{E}[X e]\| \leq \mathbb{E}\|X e\|=\left(\mathbb{E}\|X\|^{2}\right)^{1 / 2}\left(\mathbb{E}\left[e^{2}\right]\right)^{1 / 2}&lt;\infty .
\]</span></p>
<p>由此可见，期望 <span class="math inline">\(\mathbb{E}[X e]\)</span> 是有限的，并且通过计算 (2.26) 为零。</p>
<p>对于第 6 部分，将 Minkowski 不等式 (B.34) 应用于 <span class="math inline">\(e=Y-X^{\prime} \beta\)</span>，</p>
<p><span class="math display">\[
\begin{aligned}
\left(\mathbb{E}|e|^{r}\right)^{1 / r} &amp;=\left(\mathbb{E}\left|Y-X^{\prime} \beta\right|^{r}\right)^{1 / r} \\
&amp; \leq\left(\mathbb{E}|Y|^{r}\right)^{1 / r}+\left(\mathbb{E}\left|X^{\prime} \beta\right|^{r}\right)^{1 / r} \\
&amp; \leq\left(\mathbb{E}|Y|^{r}\right)^{1 / r}+\left(\mathbb{E}\|X\|^{r}\right)^{1 / r}\|\beta\|&lt;\infty,
\end{aligned}
\]</span></p>
<p>假设的最终不等式。</p>
</section>
<section id="练习" class="level2">
<h2 class="anchored" data-anchor-id="练习">练习</h2>
<p>练习 2.1 找到 <span class="math inline">\(\mathbb{E}\left[\mathbb{E}\left[\mathbb{E}\left[Y \mid X_{1}, X_{2}, X_{3}\right] \mid X_{1}, X_{2}\right] \mid X_{1}\right]\)</span></p>
<p>练习 2.2 如果 <span class="math inline">\(\mathbb{E}[Y \mid X]=a+b X\)</span>，求 <span class="math inline">\(\mathbb{E}[Y X]\)</span> 作为 <span class="math inline">\(X\)</span> 矩的函数。</p>
<p>练习 2.3 使用迭代期望定律证明定理 2.4.4。练习 2.4 假设随机变量 <span class="math inline">\(Y\)</span> 和 <span class="math inline">\(X\)</span> 只取值 0 和 1 ，并且具有以下联合概率分布</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(X=0\)</span></th>
<th><span class="math inline">\(X=1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(Y=0\)</span></td>
<td><span class="math inline">\(.1\)</span></td>
<td><span class="math inline">\(.2\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(Y=1\)</span></td>
<td><span class="math inline">\(.4\)</span></td>
<td><span class="math inline">\(.3\)</span></td>
</tr>
</tbody>
</table>
<p>为 <span class="math inline">\(X=0\)</span> 和 <span class="math inline">\(X=1\)</span> 找到 <span class="math inline">\(\mathbb{E}[Y \mid X], \mathbb{E}\left[Y^{2} \mid X\right]\)</span> 和 <span class="math inline">\(\operatorname{var}[Y \mid X]\)</span></p>
<p>练习 2.5 证明 <span class="math inline">\(\sigma^{2}(X)\)</span> 是给定 <span class="math inline">\(X\)</span> 的 <span class="math inline">\(e^{2}\)</span> 的最佳预测器：</p>
<ol type="a">
<li><p>写下 <span class="math inline">\(e^{2}\)</span> 的预测变量 <span class="math inline">\(h(X)\)</span> 的均方误差。</p></li>
<li><p>预测 <span class="math inline">\(e^{2}\)</span> 是什么意思？</p></li>
<li><p>证明 <span class="math inline">\(\sigma^{2}(X)\)</span> 最小化均方误差，因此是最好的预测器。</p></li>
</ol>
<p>练习 2.6 用 <span class="math inline">\(Y=m(X)+e\)</span> 证明 <span class="math inline">\(\operatorname{var}[Y]=\operatorname{var}[m(X)]+\sigma^{2}\)</span></p>
<p>练习 2.7 证明条件方差可以写成 <span class="math inline">\(\sigma^{2}(X)=\mathbb{E}\left[Y^{2} \mid X\right]-(\mathbb{E}[Y \mid X])^{2}\)</span>。</p>
<p>练习 2.8 假设 <span class="math inline">\(Y\)</span> 是离散值的，只取非负整数的值，并且 <span class="math inline">\(Y\)</span> 的条件分布给定 <span class="math inline">\(X=x\)</span> 是泊松：</p>
<p><span class="math display">\[
\mathbb{P}[Y=j \mid X=x]=\frac{\exp \left(-x^{\prime} \beta\right)\left(x^{\prime} \beta\right)^{j}}{j !}, \quad j=0,1,2, \ldots
\]</span></p>
<p>计算 <span class="math inline">\(\mathbb{E}[Y \mid X]\)</span> 和 <span class="math inline">\(\operatorname{var}[Y \mid X]\)</span>。这是否证明了 <span class="math inline">\(Y=X^{\prime} \beta+e\)</span> 形式的线性回归模型？</p>
<p><span class="math display">\[
\text { Hint: If } \mathbb{P}[Y=j]=\frac{\exp (-\lambda) \lambda^{j}}{j !} \text { then } \mathbb{E}[Y]=\lambda \text { and } \operatorname{var}[Y]=\lambda \text {. }
\]</span></p>
<p>练习 2.9 假设你有两个回归量：<span class="math inline">\(X_{1}\)</span> 是二元的（取值 0 和 1），<span class="math inline">\(X_{2}\)</span> 是分类的，有 3 个类别 <span class="math inline">\((A, B, C)\)</span>。将 <span class="math inline">\(\mathbb{E}\left[Y \mid X_{1}, X_{2}\right]\)</span> 写为线性回归。</p>
<p>练习 2.10 对或错。如果 <span class="math inline">\(Y=X \beta+e, X \in \mathbb{R}\)</span> 和 <span class="math inline">\(\mathbb{E}[e \mid X]=0\)</span>，那么 <span class="math inline">\(\mathbb{E}\left[X^{2} e\right]=0\)</span>。</p>
<p>练习 2.11 对或错。如果 <span class="math inline">\(Y=X \beta+e, X \in \mathbb{R}\)</span> 和 <span class="math inline">\(\mathbb{E}[X e]=0\)</span>，那么 <span class="math inline">\(\mathbb{E}\left[X^{2} e\right]=0\)</span>。</p>
<p>练习 2.12 对或错。如果 <span class="math inline">\(Y=X^{\prime} \beta+e\)</span> 和 <span class="math inline">\(\mathbb{E}[e \mid X]=0\)</span>，则 <span class="math inline">\(e\)</span> 独立于 <span class="math inline">\(X\)</span>。</p>
<p>练习 2.13 对或错。如果 <span class="math inline">\(Y=X^{\prime} \beta+e\)</span> 和 <span class="math inline">\(\mathbb{E}[X e]=0\)</span>，那么 <span class="math inline">\(\mathbb{E}[e \mid X]=0\)</span>。</p>
<p>练习 2.14 对或错。如果 <span class="math inline">\(Y=X^{\prime} \beta+e, \mathbb{E}[e \mid X]=0\)</span> 和 <span class="math inline">\(\mathbb{E}\left[e^{2} \mid X\right]=\sigma^{2}\)</span>，则 <span class="math inline">\(e\)</span> 独立于 <span class="math inline">\(X\)</span>。</p>
<p>练习 2.15 考虑仅截距模型 <span class="math inline">\(Y=\alpha+e\)</span>，<span class="math inline">\(\alpha\)</span> 是最好的线性预测器。证明 <span class="math inline">\(\alpha=\mathbb{E}[Y]\)</span></p>
<p>练习 2.16 让 <span class="math inline">\(X\)</span> 和 <span class="math inline">\(Y\)</span> 在 <span class="math inline">\(0 \leq x \leq 1,0 \leq y \leq 1\)</span> 上有联合密度 <span class="math inline">\(f(x, y)=\frac{3}{2}\left(x^{2}+y^{2}\right)\)</span>。计算最佳线性预测器 <span class="math inline">\(Y=\alpha+\beta X+e\)</span> 的系数。计算条件期望 <span class="math inline">\(m(x)=\)</span> <span class="math inline">\(\mathbb{E}[Y \mid X=x]\)</span>。最佳线性预测器和条件期望是否不同？练习 2.17 设 <span class="math inline">\(X\)</span> 是一个随机变量，<span class="math inline">\(\mu=\mathbb{E}[X]\)</span> 和 <span class="math inline">\(\sigma^{2}=\operatorname{var}[X]\)</span>。定义</p>
<p><span class="math display">\[
g\left(x, \mu, \sigma^{2}\right)=\left(\begin{array}{c}
x-\mu \\
(x-\mu)^{2}-\sigma^{2}
\end{array}\right) .
\]</span></p>
<p>证明 <span class="math inline">\(\mathbb{E}[g(X, m, s)]=0\)</span> 当且仅当 <span class="math inline">\(m=\mu\)</span> 和 <span class="math inline">\(s=\sigma^{2}\)</span>。</p>
<p>练习 2.18 假设 <span class="math inline">\(X=\left(1, X_{2}, X_{3}\right)\)</span> 其中 <span class="math inline">\(X_{3}=\alpha_{1}+\alpha_{2} X_{2}\)</span> 是 <span class="math inline">\(X_{2}\)</span> 的线性函数。</p>
<ol type="a">
<li><p>证明 <span class="math inline">\(\boldsymbol{Q}_{X X}=\mathbb{E}\left[X X^{\prime}\right]\)</span> 不可逆。</p></li>
<li><p>使用 <span class="math inline">\(X\)</span> 的线性变换来找到给定 <span class="math inline">\(X\)</span> 的 <span class="math inline">\(Y\)</span> 的最佳线性预测器的表达式。 （要明确，不要只使用广义逆公式。）</p></li>
</ol>
<p>习题 2.19 显示 (2.47)-(2.48)，即对于</p>
<p><span class="math display">\[
d(\beta)=\mathbb{E}\left[\left(m(X)-X^{\prime} \beta\right)^{2}\right]
\]</span></p>
<p>然后</p>
<p><span class="math display">\[
\beta=\underset{b \in \mathbb{R}^{k}}{\operatorname{argmin}} d(b)=\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X m(X)]=\left(\mathbb{E}\left[X X^{\prime}\right]\right)^{-1} \mathbb{E}[X Y] .
\]</span></p>
<p>提示：要显示 <span class="math inline">\(\mathbb{E}[X m(X)]=\mathbb{E}[X Y]\)</span>，请使用迭代期望定律。</p>
<p>练习 2.20 当 <span class="math inline">\((Y, X)\)</span> 具有联合密度 <span class="math inline">\(f(y, x)\)</span> 时，验证 (2.57) 与 (2.6) 中定义的 <span class="math inline">\(m(X)\)</span> 成立。</p>
<p>练习 2.21 考虑短期和长期预测</p>
<p><span class="math display">\[
\begin{gathered}
Y=X \gamma_{1}+e \\
Y=X \beta_{1}+X^{2} \beta_{2}+u
\end{gathered}
\]</span></p>
<ol type="a">
<li><p>在什么条件下 <span class="math inline">\(\gamma_{1}=\beta_{1}\)</span> ？</p></li>
<li><p>取长投影为 <span class="math inline">\(Y=X \theta_{1}+X^{3} \theta_{2}+v\)</span>。是否存在 <span class="math inline">\(\gamma_{1}=\theta_{1}\)</span> 的条件？</p></li>
</ol>
<p>练习 2.22 取同方差模型</p>
<p><span class="math display">\[
\begin{aligned}
Y &amp;=X_{1}^{\prime} \beta_{1}+X_{2}^{\prime} \beta_{2}+e \\
\mathbb{E}\left[e \mid X_{1}, X_{2}\right] &amp;=0 \\
\mathbb{E}\left[e^{2} \mid X_{1}, X_{2}\right] &amp;=\sigma^{2} \\
\mathbb{E}\left[X_{2} \mid X_{1}\right] &amp;=\Gamma X_{1} .
\end{aligned}
\]</span></p>
<p>假设 <span class="math inline">\(\Gamma \neq 0\)</span>。假设参数 <span class="math inline">\(\beta_{1}\)</span> 是感兴趣的。我们知道，排除 <span class="math inline">\(X_{2}\)</span> 会在 <span class="math inline">\(X_{2}\)</span> 上的投影系数中产生遗漏变量偏差。它还改变了方程误差。我们的问题是：对诱导方程误差的同方差性有什么影响？排除 <span class="math inline">\(X_{2}\)</span> 是否会引起异方差？请明确点。</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chpt02-ce.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Conditional Expectation and Projection</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chpt03-algebra.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Algebra of Least Squares</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>